/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BannerContentLocalization service. Represents a row in the &quot;BannerContentLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.BannerContentLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.BannerContentLocalizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerContentLocalization
 * @generated
 */
@ProviderType
public interface BannerContentLocalizationModel
	extends BaseModel<BannerContentLocalization>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a banner content localization model instance should use the {@link BannerContentLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this banner content localization.
	 *
	 * @return the primary key of this banner content localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this banner content localization.
	 *
	 * @param primaryKey the primary key of this banner content localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this banner content localization.
	 *
	 * @return the mvcc version of this banner content localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this banner content localization.
	 *
	 * @param mvccVersion the mvcc version of this banner content localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the banner content localization ID of this banner content localization.
	 *
	 * @return the banner content localization ID of this banner content localization
	 */
	public long getBannerContentLocalizationId();

	/**
	 * Sets the banner content localization ID of this banner content localization.
	 *
	 * @param bannerContentLocalizationId the banner content localization ID of this banner content localization
	 */
	public void setBannerContentLocalizationId(
		long bannerContentLocalizationId);

	/**
	 * Returns the content ID of this banner content localization.
	 *
	 * @return the content ID of this banner content localization
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this banner content localization.
	 *
	 * @param contentId the content ID of this banner content localization
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the language ID of this banner content localization.
	 *
	 * @return the language ID of this banner content localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this banner content localization.
	 *
	 * @param languageId the language ID of this banner content localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the banner image of this banner content localization.
	 *
	 * @return the banner image of this banner content localization
	 */
	@AutoEscape
	public String getBannerImage();

	/**
	 * Sets the banner image of this banner content localization.
	 *
	 * @param bannerImage the banner image of this banner content localization
	 */
	public void setBannerImage(String bannerImage);

	/**
	 * Returns the image overlay of this banner content localization.
	 *
	 * @return the image overlay of this banner content localization
	 */
	@AutoEscape
	public String getImageOverlay();

	/**
	 * Sets the image overlay of this banner content localization.
	 *
	 * @param imageOverlay the image overlay of this banner content localization
	 */
	public void setImageOverlay(String imageOverlay);

	/**
	 * Returns the link type of this banner content localization.
	 *
	 * @return the link type of this banner content localization
	 */
	@AutoEscape
	public String getLinkType();

	/**
	 * Sets the link type of this banner content localization.
	 *
	 * @param linkType the link type of this banner content localization
	 */
	public void setLinkType(String linkType);

	/**
	 * Returns the url of this banner content localization.
	 *
	 * @return the url of this banner content localization
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this banner content localization.
	 *
	 * @param url the url of this banner content localization
	 */
	public void setUrl(String url);

	/**
	 * Returns the title value of this banner content localization.
	 *
	 * @return the title value of this banner content localization
	 */
	@AutoEscape
	public String getTitleValue();

	/**
	 * Sets the title value of this banner content localization.
	 *
	 * @param titleValue the title value of this banner content localization
	 */
	public void setTitleValue(String titleValue);

	/**
	 * Returns the description value of this banner content localization.
	 *
	 * @return the description value of this banner content localization
	 */
	@AutoEscape
	public String getDescriptionValue();

	/**
	 * Sets the description value of this banner content localization.
	 *
	 * @param descriptionValue the description value of this banner content localization
	 */
	public void setDescriptionValue(String descriptionValue);

	@Override
	public BannerContentLocalization cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}