/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ConfigurationEntity service. Represents a row in the &quot;ConfigurationEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.ConfigurationEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.ConfigurationEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConfigurationEntity
 * @generated
 */
@ProviderType
public interface ConfigurationEntityModel
	extends BaseModel<ConfigurationEntity>, GroupedModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a configuration entity model instance should use the {@link ConfigurationEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this configuration entity.
	 *
	 * @return the primary key of this configuration entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this configuration entity.
	 *
	 * @param primaryKey the primary key of this configuration entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this configuration entity.
	 *
	 * @return the ID of this configuration entity
	 */
	public long getId();

	/**
	 * Sets the ID of this configuration entity.
	 *
	 * @param id the ID of this configuration entity
	 */
	public void setId(long id);

	/**
	 * Returns the url of this configuration entity.
	 *
	 * @return the url of this configuration entity
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this configuration entity.
	 *
	 * @param url the url of this configuration entity
	 */
	public void setUrl(String url);

	/**
	 * Returns the old data of this configuration entity.
	 *
	 * @return the old data of this configuration entity
	 */
	@AutoEscape
	public String getOldData();

	/**
	 * Sets the old data of this configuration entity.
	 *
	 * @param oldData the old data of this configuration entity
	 */
	public void setOldData(String oldData);

	/**
	 * Returns the new data of this configuration entity.
	 *
	 * @return the new data of this configuration entity
	 */
	@AutoEscape
	public String getNewData();

	/**
	 * Sets the new data of this configuration entity.
	 *
	 * @param newData the new data of this configuration entity
	 */
	public void setNewData(String newData);

	/**
	 * Returns the entity type of this configuration entity.
	 *
	 * @return the entity type of this configuration entity
	 */
	@AutoEscape
	public String getEntityType();

	/**
	 * Sets the entity type of this configuration entity.
	 *
	 * @param entityType the entity type of this configuration entity
	 */
	public void setEntityType(String entityType);

	/**
	 * Returns the entity ID of this configuration entity.
	 *
	 * @return the entity ID of this configuration entity
	 */
	@AutoEscape
	public String getEntityId();

	/**
	 * Sets the entity ID of this configuration entity.
	 *
	 * @param entityId the entity ID of this configuration entity
	 */
	public void setEntityId(String entityId);

	/**
	 * Returns the group ID of this configuration entity.
	 *
	 * @return the group ID of this configuration entity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this configuration entity.
	 *
	 * @param groupId the group ID of this configuration entity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this configuration entity.
	 *
	 * @return the company ID of this configuration entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this configuration entity.
	 *
	 * @param companyId the company ID of this configuration entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this configuration entity.
	 *
	 * @return the user ID of this configuration entity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this configuration entity.
	 *
	 * @param userId the user ID of this configuration entity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this configuration entity.
	 *
	 * @return the user uuid of this configuration entity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this configuration entity.
	 *
	 * @param userUuid the user uuid of this configuration entity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this configuration entity.
	 *
	 * @return the user name of this configuration entity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this configuration entity.
	 *
	 * @param userName the user name of this configuration entity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this configuration entity.
	 *
	 * @return the create date of this configuration entity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this configuration entity.
	 *
	 * @param createDate the create date of this configuration entity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this configuration entity.
	 *
	 * @return the modified date of this configuration entity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this configuration entity.
	 *
	 * @param modifiedDate the modified date of this configuration entity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this configuration entity.
	 *
	 * @return the status of this configuration entity
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this configuration entity.
	 *
	 * @param status the status of this configuration entity
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this configuration entity.
	 *
	 * @return the status by user ID of this configuration entity
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this configuration entity.
	 *
	 * @param statusByUserId the status by user ID of this configuration entity
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this configuration entity.
	 *
	 * @return the status by user uuid of this configuration entity
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this configuration entity.
	 *
	 * @param statusByUserUuid the status by user uuid of this configuration entity
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this configuration entity.
	 *
	 * @return the status by user name of this configuration entity
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this configuration entity.
	 *
	 * @param statusByUserName the status by user name of this configuration entity
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this configuration entity.
	 *
	 * @return the status date of this configuration entity
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this configuration entity.
	 *
	 * @param statusDate the status date of this configuration entity
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this configuration entity.
	 *
	 * @return the uuid_ of this configuration entity
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this configuration entity.
	 *
	 * @param uuid_ the uuid_ of this configuration entity
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the workflow action of this configuration entity.
	 *
	 * @return the workflow action of this configuration entity
	 */
	@AutoEscape
	public String getWorkflowAction();

	/**
	 * Sets the workflow action of this configuration entity.
	 *
	 * @param workflowAction the workflow action of this configuration entity
	 */
	public void setWorkflowAction(String workflowAction);

	/**
	 * Returns <code>true</code> if this configuration entity is approved.
	 *
	 * @return <code>true</code> if this configuration entity is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this configuration entity is denied.
	 *
	 * @return <code>true</code> if this configuration entity is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this configuration entity is a draft.
	 *
	 * @return <code>true</code> if this configuration entity is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this configuration entity is expired.
	 *
	 * @return <code>true</code> if this configuration entity is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this configuration entity is inactive.
	 *
	 * @return <code>true</code> if this configuration entity is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this configuration entity is incomplete.
	 *
	 * @return <code>true</code> if this configuration entity is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this configuration entity is pending.
	 *
	 * @return <code>true</code> if this configuration entity is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this configuration entity is scheduled.
	 *
	 * @return <code>true</code> if this configuration entity is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public ConfigurationEntity cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}