/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Feature service. Represents a row in the &quot;FEATURE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.FeatureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.FeatureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Feature
 * @generated
 */
@ProviderType
public interface FeatureModel
	extends BaseModel<Feature>, GroupedModel, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feature model instance should use the {@link Feature} interface instead.
	 */

	/**
	 * Returns the primary key of this feature.
	 *
	 * @return the primary key of this feature
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this feature.
	 *
	 * @param primaryKey the primary key of this feature
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the feature ID of this feature.
	 *
	 * @return the feature ID of this feature
	 */
	public long getFeatureId();

	/**
	 * Sets the feature ID of this feature.
	 *
	 * @param featureId the feature ID of this feature
	 */
	public void setFeatureId(long featureId);

	/**
	 * Returns the feature name of this feature.
	 *
	 * @return the feature name of this feature
	 */
	@AutoEscape
	public String getFeatureName();

	/**
	 * Sets the feature name of this feature.
	 *
	 * @param featureName the feature name of this feature
	 */
	public void setFeatureName(String featureName);

	/**
	 * Returns the page type of this feature.
	 *
	 * @return the page type of this feature
	 */
	@AutoEscape
	public String getPageType();

	/**
	 * Sets the page type of this feature.
	 *
	 * @param pageType the page type of this feature
	 */
	public void setPageType(String pageType);

	/**
	 * Returns the parent page of this feature.
	 *
	 * @return the parent page of this feature
	 */
	public long getParentPage();

	/**
	 * Sets the parent page of this feature.
	 *
	 * @param parentPage the parent page of this feature
	 */
	public void setParentPage(long parentPage);

	/**
	 * Returns the route ID of this feature.
	 *
	 * @return the route ID of this feature
	 */
	@AutoEscape
	public String getRouteId();

	/**
	 * Sets the route ID of this feature.
	 *
	 * @param routeId the route ID of this feature
	 */
	public void setRouteId(String routeId);

	/**
	 * Returns the feature status of this feature.
	 *
	 * @return the feature status of this feature
	 */
	public Boolean getFeatureStatus();

	/**
	 * Sets the feature status of this feature.
	 *
	 * @param featureStatus the feature status of this feature
	 */
	public void setFeatureStatus(Boolean featureStatus);

	/**
	 * Returns the block ID of this feature.
	 *
	 * @return the block ID of this feature
	 */
	public long getBlockId();

	/**
	 * Sets the block ID of this feature.
	 *
	 * @param blockId the block ID of this feature
	 */
	public void setBlockId(long blockId);

	/**
	 * Returns the channel ID of this feature.
	 *
	 * @return the channel ID of this feature
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this feature.
	 *
	 * @param channelId the channel ID of this feature
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the group ID of this feature.
	 *
	 * @return the group ID of this feature
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this feature.
	 *
	 * @param groupId the group ID of this feature
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this feature.
	 *
	 * @return the company ID of this feature
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this feature.
	 *
	 * @param companyId the company ID of this feature
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this feature.
	 *
	 * @return the user ID of this feature
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this feature.
	 *
	 * @param userId the user ID of this feature
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this feature.
	 *
	 * @return the user uuid of this feature
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this feature.
	 *
	 * @param userUuid the user uuid of this feature
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this feature.
	 *
	 * @return the user name of this feature
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this feature.
	 *
	 * @param userName the user name of this feature
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this feature.
	 *
	 * @return the create date of this feature
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this feature.
	 *
	 * @param createDate the create date of this feature
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this feature.
	 *
	 * @return the modified date of this feature
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this feature.
	 *
	 * @param modifiedDate the modified date of this feature
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this feature.
	 *
	 * @return the status of this feature
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this feature.
	 *
	 * @param status the status of this feature
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this feature.
	 *
	 * @return the status by user ID of this feature
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this feature.
	 *
	 * @param statusByUserId the status by user ID of this feature
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this feature.
	 *
	 * @return the status by user uuid of this feature
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this feature.
	 *
	 * @param statusByUserUuid the status by user uuid of this feature
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this feature.
	 *
	 * @return the status by user name of this feature
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this feature.
	 *
	 * @param statusByUserName the status by user name of this feature
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this feature.
	 *
	 * @return the status date of this feature
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this feature.
	 *
	 * @param statusDate the status date of this feature
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this feature.
	 *
	 * @return the uuid_ of this feature
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this feature.
	 *
	 * @param uuid_ the uuid_ of this feature
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the original entity ID of this feature.
	 *
	 * @return the original entity ID of this feature
	 */
	public long getOriginalEntityId();

	/**
	 * Sets the original entity ID of this feature.
	 *
	 * @param originalEntityId the original entity ID of this feature
	 */
	public void setOriginalEntityId(long originalEntityId);

	/**
	 * Returns the entity resource ID of this feature.
	 *
	 * @return the entity resource ID of this feature
	 */
	public long getEntityResourceId();

	/**
	 * Sets the entity resource ID of this feature.
	 *
	 * @param entityResourceId the entity resource ID of this feature
	 */
	public void setEntityResourceId(long entityResourceId);

	/**
	 * Returns the child resource ID of this feature.
	 *
	 * @return the child resource ID of this feature
	 */
	public long getChildResourceId();

	/**
	 * Sets the child resource ID of this feature.
	 *
	 * @param childResourceId the child resource ID of this feature
	 */
	public void setChildResourceId(long childResourceId);

	/**
	 * Returns the version of this feature.
	 *
	 * @return the version of this feature
	 */
	public int getVersion();

	/**
	 * Sets the version of this feature.
	 *
	 * @param version the version of this feature
	 */
	public void setVersion(int version);

	/**
	 * Returns the workflow action of this feature.
	 *
	 * @return the workflow action of this feature
	 */
	@AutoEscape
	public String getWorkflowAction();

	/**
	 * Sets the workflow action of this feature.
	 *
	 * @param workflowAction the workflow action of this feature
	 */
	public void setWorkflowAction(String workflowAction);

	/**
	 * Returns <code>true</code> if this feature is approved.
	 *
	 * @return <code>true</code> if this feature is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this feature is denied.
	 *
	 * @return <code>true</code> if this feature is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this feature is a draft.
	 *
	 * @return <code>true</code> if this feature is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this feature is expired.
	 *
	 * @return <code>true</code> if this feature is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this feature is inactive.
	 *
	 * @return <code>true</code> if this feature is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this feature is incomplete.
	 *
	 * @return <code>true</code> if this feature is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this feature is pending.
	 *
	 * @return <code>true</code> if this feature is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this feature is scheduled.
	 *
	 * @return <code>true</code> if this feature is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Feature cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}