/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FeatureLovMap service. Represents a row in the &quot;FeatureLovMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.FeatureLovMapModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.FeatureLovMapImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeatureLovMap
 * @generated
 */
@ProviderType
public interface FeatureLovMapModel extends BaseModel<FeatureLovMap> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feature lov map model instance should use the {@link FeatureLovMap} interface instead.
	 */

	/**
	 * Returns the primary key of this feature lov map.
	 *
	 * @return the primary key of this feature lov map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this feature lov map.
	 *
	 * @param primaryKey the primary key of this feature lov map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this feature lov map.
	 *
	 * @return the ID of this feature lov map
	 */
	public long getId();

	/**
	 * Sets the ID of this feature lov map.
	 *
	 * @param id the ID of this feature lov map
	 */
	public void setId(long id);

	/**
	 * Returns the feature ID of this feature lov map.
	 *
	 * @return the feature ID of this feature lov map
	 */
	public long getFeatureId();

	/**
	 * Sets the feature ID of this feature lov map.
	 *
	 * @param featureId the feature ID of this feature lov map
	 */
	public void setFeatureId(long featureId);

	/**
	 * Returns the feature entity resource ID of this feature lov map.
	 *
	 * @return the feature entity resource ID of this feature lov map
	 */
	public long getFeatureEntityResourceId();

	/**
	 * Sets the feature entity resource ID of this feature lov map.
	 *
	 * @param featureEntityResourceId the feature entity resource ID of this feature lov map
	 */
	public void setFeatureEntityResourceId(long featureEntityResourceId);

	/**
	 * Returns the lov entity resource ID of this feature lov map.
	 *
	 * @return the lov entity resource ID of this feature lov map
	 */
	public long getLovEntityResourceId();

	/**
	 * Sets the lov entity resource ID of this feature lov map.
	 *
	 * @param lovEntityResourceId the lov entity resource ID of this feature lov map
	 */
	public void setLovEntityResourceId(long lovEntityResourceId);

	/**
	 * Returns the lov data code of this feature lov map.
	 *
	 * @return the lov data code of this feature lov map
	 */
	@AutoEscape
	public String getLovDataCode();

	/**
	 * Sets the lov data code of this feature lov map.
	 *
	 * @param lovDataCode the lov data code of this feature lov map
	 */
	public void setLovDataCode(String lovDataCode);

	/**
	 * Returns the lov type of this feature lov map.
	 *
	 * @return the lov type of this feature lov map
	 */
	@AutoEscape
	public String getLovType();

	/**
	 * Sets the lov type of this feature lov map.
	 *
	 * @param lovType the lov type of this feature lov map
	 */
	public void setLovType(String lovType);

	@Override
	public FeatureLovMap cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}