/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GlobalVersion service. Represents a row in the &quot;GlobalVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.GlobalVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.GlobalVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GlobalVersion
 * @generated
 */
@ProviderType
public interface GlobalVersionModel
	extends BaseModel<GlobalVersion>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a global version model instance should use the {@link GlobalVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this global version.
	 *
	 * @return the primary key of this global version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this global version.
	 *
	 * @param primaryKey the primary key of this global version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the version ID of this global version.
	 *
	 * @return the version ID of this global version
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this global version.
	 *
	 * @param versionId the version ID of this global version
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the company ID of this global version.
	 *
	 * @return the company ID of this global version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this global version.
	 *
	 * @param companyId the company ID of this global version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the channel ID of this global version.
	 *
	 * @return the channel ID of this global version
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this global version.
	 *
	 * @param channelId the channel ID of this global version
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the component name of this global version.
	 *
	 * @return the component name of this global version
	 */
	@AutoEscape
	public String getComponentName();

	/**
	 * Sets the component name of this global version.
	 *
	 * @param componentName the component name of this global version
	 */
	public void setComponentName(String componentName);

	/**
	 * Returns the version of this global version.
	 *
	 * @return the version of this global version
	 */
	public long getVersion();

	/**
	 * Sets the version of this global version.
	 *
	 * @param version the version of this global version
	 */
	public void setVersion(long version);

	/**
	 * Returns the modified date of this global version.
	 *
	 * @return the modified date of this global version
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this global version.
	 *
	 * @param modifiedDate the modified date of this global version
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public GlobalVersion cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}