/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Localization service. Represents a row in the &quot;LOCALIZATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.LocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.LocalizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Localization
 * @generated
 */
@ProviderType
public interface LocalizationModel
	extends BaseModel<Localization>, GroupedModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a localization model instance should use the {@link Localization} interface instead.
	 */

	/**
	 * Returns the primary key of this localization.
	 *
	 * @return the primary key of this localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this localization.
	 *
	 * @param primaryKey the primary key of this localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the localization ID of this localization.
	 *
	 * @return the localization ID of this localization
	 */
	public long getLocalizationId();

	/**
	 * Sets the localization ID of this localization.
	 *
	 * @param localizationId the localization ID of this localization
	 */
	public void setLocalizationId(long localizationId);

	/**
	 * Returns the local value of this localization.
	 *
	 * @return the local value of this localization
	 */
	@AutoEscape
	public String getLocalValue();

	/**
	 * Sets the local value of this localization.
	 *
	 * @param localValue the local value of this localization
	 */
	public void setLocalValue(String localValue);

	/**
	 * Returns the version of this localization.
	 *
	 * @return the version of this localization
	 */
	public long getVersion();

	/**
	 * Sets the version of this localization.
	 *
	 * @param version the version of this localization
	 */
	public void setVersion(long version);

	/**
	 * Returns the language ID of this localization.
	 *
	 * @return the language ID of this localization
	 */
	public long getLanguageId();

	/**
	 * Sets the language ID of this localization.
	 *
	 * @param languageId the language ID of this localization
	 */
	public void setLanguageId(long languageId);

	/**
	 * Returns the user name of this localization.
	 *
	 * @return the user name of this localization
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this localization.
	 *
	 * @param userName the user name of this localization
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the channel ID of this localization.
	 *
	 * @return the channel ID of this localization
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this localization.
	 *
	 * @param channelId the channel ID of this localization
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the feature ID of this localization.
	 *
	 * @return the feature ID of this localization
	 */
	public long getFeatureId();

	/**
	 * Sets the feature ID of this localization.
	 *
	 * @param featureId the feature ID of this localization
	 */
	public void setFeatureId(long featureId);

	/**
	 * Returns the group ID of this localization.
	 *
	 * @return the group ID of this localization
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this localization.
	 *
	 * @param groupId the group ID of this localization
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this localization.
	 *
	 * @return the company ID of this localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this localization.
	 *
	 * @param companyId the company ID of this localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this localization.
	 *
	 * @return the user ID of this localization
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this localization.
	 *
	 * @param userId the user ID of this localization
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this localization.
	 *
	 * @return the user uuid of this localization
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this localization.
	 *
	 * @param userUuid the user uuid of this localization
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this localization.
	 *
	 * @return the create date of this localization
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this localization.
	 *
	 * @param createDate the create date of this localization
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this localization.
	 *
	 * @return the modified date of this localization
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this localization.
	 *
	 * @param modifiedDate the modified date of this localization
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this localization.
	 *
	 * @return the status of this localization
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this localization.
	 *
	 * @param status the status of this localization
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this localization.
	 *
	 * @return the status by user ID of this localization
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this localization.
	 *
	 * @param statusByUserId the status by user ID of this localization
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this localization.
	 *
	 * @return the status by user uuid of this localization
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this localization.
	 *
	 * @param statusByUserUuid the status by user uuid of this localization
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this localization.
	 *
	 * @return the status by user name of this localization
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this localization.
	 *
	 * @param statusByUserName the status by user name of this localization
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this localization.
	 *
	 * @return the status date of this localization
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this localization.
	 *
	 * @param statusDate the status date of this localization
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this localization.
	 *
	 * @return the uuid_ of this localization
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this localization.
	 *
	 * @param uuid_ the uuid_ of this localization
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the original entity ID of this localization.
	 *
	 * @return the original entity ID of this localization
	 */
	public long getOriginalEntityId();

	/**
	 * Sets the original entity ID of this localization.
	 *
	 * @param originalEntityId the original entity ID of this localization
	 */
	public void setOriginalEntityId(long originalEntityId);

	/**
	 * Returns the entity resource ID of this localization.
	 *
	 * @return the entity resource ID of this localization
	 */
	public long getEntityResourceId();

	/**
	 * Sets the entity resource ID of this localization.
	 *
	 * @param entityResourceId the entity resource ID of this localization
	 */
	public void setEntityResourceId(long entityResourceId);

	/**
	 * Returns the workflow batch ID of this localization.
	 *
	 * @return the workflow batch ID of this localization
	 */
	@AutoEscape
	public String getWorkflowBatchId();

	/**
	 * Sets the workflow batch ID of this localization.
	 *
	 * @param workflowBatchId the workflow batch ID of this localization
	 */
	public void setWorkflowBatchId(String workflowBatchId);

	/**
	 * Returns the global version of this localization.
	 *
	 * @return the global version of this localization
	 */
	public long getGlobalVersion();

	/**
	 * Sets the global version of this localization.
	 *
	 * @param globalVersion the global version of this localization
	 */
	public void setGlobalVersion(long globalVersion);

	/**
	 * Returns the import request ID of this localization.
	 *
	 * @return the import request ID of this localization
	 */
	public long getImportRequestId();

	/**
	 * Sets the import request ID of this localization.
	 *
	 * @param importRequestId the import request ID of this localization
	 */
	public void setImportRequestId(long importRequestId);

	/**
	 * Returns <code>true</code> if this localization is approved.
	 *
	 * @return <code>true</code> if this localization is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this localization is denied.
	 *
	 * @return <code>true</code> if this localization is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this localization is a draft.
	 *
	 * @return <code>true</code> if this localization is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this localization is expired.
	 *
	 * @return <code>true</code> if this localization is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this localization is inactive.
	 *
	 * @return <code>true</code> if this localization is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this localization is incomplete.
	 *
	 * @return <code>true</code> if this localization is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this localization is pending.
	 *
	 * @return <code>true</code> if this localization is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this localization is scheduled.
	 *
	 * @return <code>true</code> if this localization is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Localization cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}