/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LovDataLocalization service. Represents a row in the &quot;LovDataLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.LovDataLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.LovDataLocalizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovDataLocalization
 * @generated
 */
@ProviderType
public interface LovDataLocalizationModel
	extends BaseModel<LovDataLocalization>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lov data localization model instance should use the {@link LovDataLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this lov data localization.
	 *
	 * @return the primary key of this lov data localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lov data localization.
	 *
	 * @param primaryKey the primary key of this lov data localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this lov data localization.
	 *
	 * @return the mvcc version of this lov data localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this lov data localization.
	 *
	 * @param mvccVersion the mvcc version of this lov data localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the lov data localization ID of this lov data localization.
	 *
	 * @return the lov data localization ID of this lov data localization
	 */
	public long getLovDataLocalizationId();

	/**
	 * Sets the lov data localization ID of this lov data localization.
	 *
	 * @param lovDataLocalizationId the lov data localization ID of this lov data localization
	 */
	public void setLovDataLocalizationId(long lovDataLocalizationId);

	/**
	 * Returns the ID of this lov data localization.
	 *
	 * @return the ID of this lov data localization
	 */
	public long getId();

	/**
	 * Sets the ID of this lov data localization.
	 *
	 * @param id the ID of this lov data localization
	 */
	public void setId(long id);

	/**
	 * Returns the language ID of this lov data localization.
	 *
	 * @return the language ID of this lov data localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this lov data localization.
	 *
	 * @param languageId the language ID of this lov data localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the record description of this lov data localization.
	 *
	 * @return the record description of this lov data localization
	 */
	@AutoEscape
	public String getRecordDescription();

	/**
	 * Sets the record description of this lov data localization.
	 *
	 * @param recordDescription the record description of this lov data localization
	 */
	public void setRecordDescription(String recordDescription);

	/**
	 * Returns the lov ID localization of this lov data localization.
	 *
	 * @return the lov ID localization of this lov data localization
	 */
	@AutoEscape
	public String getLovIdLocalization();

	/**
	 * Sets the lov ID localization of this lov data localization.
	 *
	 * @param lovIdLocalization the lov ID localization of this lov data localization
	 */
	public void setLovIdLocalization(String lovIdLocalization);

	@Override
	public LovDataLocalization cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}