/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LovsLocalization service. Represents a row in the &quot;LovsLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.LovsLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.LovsLocalizationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovsLocalization
 * @generated
 */
@ProviderType
public interface LovsLocalizationModel
	extends BaseModel<LovsLocalization>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lovs localization model instance should use the {@link LovsLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this lovs localization.
	 *
	 * @return the primary key of this lovs localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lovs localization.
	 *
	 * @param primaryKey the primary key of this lovs localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this lovs localization.
	 *
	 * @return the mvcc version of this lovs localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this lovs localization.
	 *
	 * @param mvccVersion the mvcc version of this lovs localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the lovs localization ID of this lovs localization.
	 *
	 * @return the lovs localization ID of this lovs localization
	 */
	public long getLovsLocalizationId();

	/**
	 * Sets the lovs localization ID of this lovs localization.
	 *
	 * @param lovsLocalizationId the lovs localization ID of this lovs localization
	 */
	public void setLovsLocalizationId(long lovsLocalizationId);

	/**
	 * Returns the company ID of this lovs localization.
	 *
	 * @return the company ID of this lovs localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lovs localization.
	 *
	 * @param companyId the company ID of this lovs localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the ID of this lovs localization.
	 *
	 * @return the ID of this lovs localization
	 */
	public long getId();

	/**
	 * Sets the ID of this lovs localization.
	 *
	 * @param id the ID of this lovs localization
	 */
	public void setId(long id);

	/**
	 * Returns the language ID of this lovs localization.
	 *
	 * @return the language ID of this lovs localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this lovs localization.
	 *
	 * @param languageId the language ID of this lovs localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the name of this lovs localization.
	 *
	 * @return the name of this lovs localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lovs localization.
	 *
	 * @param name the name of this lovs localization
	 */
	public void setName(String name);

	@Override
	public LovsLocalization cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}