/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Persona service. Represents a row in the &quot;PERSONA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.PersonaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.PersonaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Persona
 * @generated
 */
@ProviderType
public interface PersonaModel
	extends BaseModel<Persona>, GroupedModel, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persona model instance should use the {@link Persona} interface instead.
	 */

	/**
	 * Returns the primary key of this persona.
	 *
	 * @return the primary key of this persona
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persona.
	 *
	 * @param primaryKey the primary key of this persona
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the persona ID of this persona.
	 *
	 * @return the persona ID of this persona
	 */
	public long getPersonaId();

	/**
	 * Sets the persona ID of this persona.
	 *
	 * @param personaId the persona ID of this persona
	 */
	public void setPersonaId(long personaId);

	/**
	 * Returns the channel ID of this persona.
	 *
	 * @return the channel ID of this persona
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this persona.
	 *
	 * @param channelId the channel ID of this persona
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the dark theme ID of this persona.
	 *
	 * @return the dark theme ID of this persona
	 */
	public Long getDarkThemeId();

	/**
	 * Sets the dark theme ID of this persona.
	 *
	 * @param darkThemeId the dark theme ID of this persona
	 */
	public void setDarkThemeId(Long darkThemeId);

	/**
	 * Returns the light theme ID of this persona.
	 *
	 * @return the light theme ID of this persona
	 */
	public Long getLightThemeId();

	/**
	 * Sets the light theme ID of this persona.
	 *
	 * @param lightThemeId the light theme ID of this persona
	 */
	public void setLightThemeId(Long lightThemeId);

	/**
	 * Returns the name of this persona.
	 *
	 * @return the name of this persona
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this persona.
	 *
	 * @param name the name of this persona
	 */
	public void setName(String name);

	/**
	 * Returns the start age of this persona.
	 *
	 * @return the start age of this persona
	 */
	public int getStartAge();

	/**
	 * Sets the start age of this persona.
	 *
	 * @param startAge the start age of this persona
	 */
	public void setStartAge(int startAge);

	/**
	 * Returns the end age of this persona.
	 *
	 * @return the end age of this persona
	 */
	public int getEndAge();

	/**
	 * Sets the end age of this persona.
	 *
	 * @param endAge the end age of this persona
	 */
	public void setEndAge(int endAge);

	/**
	 * Returns the nationality of this persona.
	 *
	 * @return the nationality of this persona
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this persona.
	 *
	 * @param nationality the nationality of this persona
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the customer segment of this persona.
	 *
	 * @return the customer segment of this persona
	 */
	@AutoEscape
	public String getCustomerSegment();

	/**
	 * Sets the customer segment of this persona.
	 *
	 * @param customerSegment the customer segment of this persona
	 */
	public void setCustomerSegment(String customerSegment);

	/**
	 * Returns the persona status of this persona.
	 *
	 * @return the persona status of this persona
	 */
	@AutoEscape
	public String getPersonaStatus();

	/**
	 * Sets the persona status of this persona.
	 *
	 * @param personaStatus the persona status of this persona
	 */
	public void setPersonaStatus(String personaStatus);

	/**
	 * Returns the sector of this persona.
	 *
	 * @return the sector of this persona
	 */
	@AutoEscape
	public String getSector();

	/**
	 * Sets the sector of this persona.
	 *
	 * @param sector the sector of this persona
	 */
	public void setSector(String sector);

	/**
	 * Returns the min income of this persona.
	 *
	 * @return the min income of this persona
	 */
	public int getMinIncome();

	/**
	 * Sets the min income of this persona.
	 *
	 * @param minIncome the min income of this persona
	 */
	public void setMinIncome(int minIncome);

	/**
	 * Returns the max income of this persona.
	 *
	 * @return the max income of this persona
	 */
	public int getMaxIncome();

	/**
	 * Sets the max income of this persona.
	 *
	 * @param maxIncome the max income of this persona
	 */
	public void setMaxIncome(int maxIncome);

	/**
	 * Returns the description of this persona.
	 *
	 * @return the description of this persona
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this persona.
	 *
	 * @param description the description of this persona
	 */
	public void setDescription(String description);

	/**
	 * Returns the gender of this persona.
	 *
	 * @return the gender of this persona
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this persona.
	 *
	 * @param gender the gender of this persona
	 */
	public void setGender(String gender);

	/**
	 * Returns the priority of this persona.
	 *
	 * @return the priority of this persona
	 */
	public int getPriority();

	/**
	 * Sets the priority of this persona.
	 *
	 * @param priority the priority of this persona
	 */
	public void setPriority(int priority);

	/**
	 * Returns the date from of this persona.
	 *
	 * @return the date from of this persona
	 */
	public Date getDateFrom();

	/**
	 * Sets the date from of this persona.
	 *
	 * @param dateFrom the date from of this persona
	 */
	public void setDateFrom(Date dateFrom);

	/**
	 * Returns the date to of this persona.
	 *
	 * @return the date to of this persona
	 */
	public Date getDateTo();

	/**
	 * Sets the date to of this persona.
	 *
	 * @param dateTo the date to of this persona
	 */
	public void setDateTo(Date dateTo);

	/**
	 * Returns the default persona of this persona.
	 *
	 * @return the default persona of this persona
	 */
	public boolean getDefaultPersona();

	/**
	 * Returns <code>true</code> if this persona is default persona.
	 *
	 * @return <code>true</code> if this persona is default persona; <code>false</code> otherwise
	 */
	public boolean isDefaultPersona();

	/**
	 * Sets whether this persona is default persona.
	 *
	 * @param defaultPersona the default persona of this persona
	 */
	public void setDefaultPersona(boolean defaultPersona);

	/**
	 * Returns the group ID of this persona.
	 *
	 * @return the group ID of this persona
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this persona.
	 *
	 * @param groupId the group ID of this persona
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this persona.
	 *
	 * @return the company ID of this persona
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persona.
	 *
	 * @param companyId the company ID of this persona
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persona.
	 *
	 * @return the user ID of this persona
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persona.
	 *
	 * @param userId the user ID of this persona
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persona.
	 *
	 * @return the user uuid of this persona
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persona.
	 *
	 * @param userUuid the user uuid of this persona
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persona.
	 *
	 * @return the user name of this persona
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persona.
	 *
	 * @param userName the user name of this persona
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persona.
	 *
	 * @return the create date of this persona
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persona.
	 *
	 * @param createDate the create date of this persona
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persona.
	 *
	 * @return the modified date of this persona
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persona.
	 *
	 * @param modifiedDate the modified date of this persona
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this persona.
	 *
	 * @return the status of this persona
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this persona.
	 *
	 * @param status the status of this persona
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this persona.
	 *
	 * @return the status by user ID of this persona
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this persona.
	 *
	 * @param statusByUserId the status by user ID of this persona
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this persona.
	 *
	 * @return the status by user uuid of this persona
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this persona.
	 *
	 * @param statusByUserUuid the status by user uuid of this persona
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this persona.
	 *
	 * @return the status by user name of this persona
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this persona.
	 *
	 * @param statusByUserName the status by user name of this persona
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this persona.
	 *
	 * @return the status date of this persona
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this persona.
	 *
	 * @param statusDate the status date of this persona
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this persona.
	 *
	 * @return the uuid_ of this persona
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this persona.
	 *
	 * @param uuid_ the uuid_ of this persona
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the original entity ID of this persona.
	 *
	 * @return the original entity ID of this persona
	 */
	public long getOriginalEntityId();

	/**
	 * Sets the original entity ID of this persona.
	 *
	 * @param originalEntityId the original entity ID of this persona
	 */
	public void setOriginalEntityId(long originalEntityId);

	/**
	 * Returns the entity resource ID of this persona.
	 *
	 * @return the entity resource ID of this persona
	 */
	public long getEntityResourceId();

	/**
	 * Sets the entity resource ID of this persona.
	 *
	 * @param entityResourceId the entity resource ID of this persona
	 */
	public void setEntityResourceId(long entityResourceId);

	/**
	 * Returns the version of this persona.
	 *
	 * @return the version of this persona
	 */
	public int getVersion();

	/**
	 * Sets the version of this persona.
	 *
	 * @param version the version of this persona
	 */
	public void setVersion(int version);

	/**
	 * Returns the workflow action of this persona.
	 *
	 * @return the workflow action of this persona
	 */
	@AutoEscape
	public String getWorkflowAction();

	/**
	 * Sets the workflow action of this persona.
	 *
	 * @param workflowAction the workflow action of this persona
	 */
	public void setWorkflowAction(String workflowAction);

	/**
	 * Returns <code>true</code> if this persona is approved.
	 *
	 * @return <code>true</code> if this persona is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this persona is denied.
	 *
	 * @return <code>true</code> if this persona is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this persona is a draft.
	 *
	 * @return <code>true</code> if this persona is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this persona is expired.
	 *
	 * @return <code>true</code> if this persona is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this persona is inactive.
	 *
	 * @return <code>true</code> if this persona is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this persona is incomplete.
	 *
	 * @return <code>true</code> if this persona is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this persona is pending.
	 *
	 * @return <code>true</code> if this persona is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this persona is scheduled.
	 *
	 * @return <code>true</code> if this persona is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Persona cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}