/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Resource service. Represents a row in the &quot;Resource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.ResourceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.ResourceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Resource
 * @generated
 */
@ProviderType
public interface ResourceModel
	extends BaseModel<Resource>, GroupedModel, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a resource model instance should use the {@link Resource} interface instead.
	 */

	/**
	 * Returns the primary key of this resource.
	 *
	 * @return the primary key of this resource
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this resource.
	 *
	 * @param primaryKey the primary key of this resource
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the default language ID of this resource.
	 *
	 * @return the default language ID of this resource
	 */
	@AutoEscape
	public String getDefaultLanguageId();

	/**
	 * Sets the default language ID of this resource.
	 *
	 * @param defaultLanguageId the default language ID of this resource
	 */
	public void setDefaultLanguageId(String defaultLanguageId);

	/**
	 * Returns the resource ID of this resource.
	 *
	 * @return the resource ID of this resource
	 */
	public long getResourceId();

	/**
	 * Sets the resource ID of this resource.
	 *
	 * @param resourceId the resource ID of this resource
	 */
	public void setResourceId(long resourceId);

	/**
	 * Returns the channel ID of this resource.
	 *
	 * @return the channel ID of this resource
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this resource.
	 *
	 * @param channelId the channel ID of this resource
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the resource code of this resource.
	 *
	 * @return the resource code of this resource
	 */
	@AutoEscape
	public String getResourceCode();

	/**
	 * Sets the resource code of this resource.
	 *
	 * @param resourceCode the resource code of this resource
	 */
	public void setResourceCode(String resourceCode);

	/**
	 * Returns the resource type of this resource.
	 *
	 * @return the resource type of this resource
	 */
	@AutoEscape
	public String getResourceType();

	/**
	 * Sets the resource type of this resource.
	 *
	 * @param resourceType the resource type of this resource
	 */
	public void setResourceType(String resourceType);

	/**
	 * Returns the url type of this resource.
	 *
	 * @return the url type of this resource
	 */
	@AutoEscape
	public String getUrlType();

	/**
	 * Sets the url type of this resource.
	 *
	 * @param urlType the url type of this resource
	 */
	public void setUrlType(String urlType);

	/**
	 * Returns the group ID of this resource.
	 *
	 * @return the group ID of this resource
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this resource.
	 *
	 * @param groupId the group ID of this resource
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this resource.
	 *
	 * @return the company ID of this resource
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this resource.
	 *
	 * @param companyId the company ID of this resource
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this resource.
	 *
	 * @return the user ID of this resource
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this resource.
	 *
	 * @param userId the user ID of this resource
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this resource.
	 *
	 * @return the user uuid of this resource
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this resource.
	 *
	 * @param userUuid the user uuid of this resource
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this resource.
	 *
	 * @return the user name of this resource
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this resource.
	 *
	 * @param userName the user name of this resource
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this resource.
	 *
	 * @return the create date of this resource
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this resource.
	 *
	 * @param createDate the create date of this resource
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this resource.
	 *
	 * @return the modified date of this resource
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this resource.
	 *
	 * @param modifiedDate the modified date of this resource
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this resource.
	 *
	 * @return the status of this resource
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this resource.
	 *
	 * @param status the status of this resource
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this resource.
	 *
	 * @return the status by user ID of this resource
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this resource.
	 *
	 * @param statusByUserId the status by user ID of this resource
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this resource.
	 *
	 * @return the status by user uuid of this resource
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this resource.
	 *
	 * @param statusByUserUuid the status by user uuid of this resource
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this resource.
	 *
	 * @return the status by user name of this resource
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this resource.
	 *
	 * @param statusByUserName the status by user name of this resource
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this resource.
	 *
	 * @return the status date of this resource
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this resource.
	 *
	 * @param statusDate the status date of this resource
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this resource.
	 *
	 * @return the uuid_ of this resource
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this resource.
	 *
	 * @param uuid_ the uuid_ of this resource
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the original entity ID of this resource.
	 *
	 * @return the original entity ID of this resource
	 */
	public long getOriginalEntityId();

	/**
	 * Sets the original entity ID of this resource.
	 *
	 * @param originalEntityId the original entity ID of this resource
	 */
	public void setOriginalEntityId(long originalEntityId);

	/**
	 * Returns the entity resource ID of this resource.
	 *
	 * @return the entity resource ID of this resource
	 */
	public long getEntityResourceId();

	/**
	 * Sets the entity resource ID of this resource.
	 *
	 * @param entityResourceId the entity resource ID of this resource
	 */
	public void setEntityResourceId(long entityResourceId);

	/**
	 * Returns the version of this resource.
	 *
	 * @return the version of this resource
	 */
	public int getVersion();

	/**
	 * Sets the version of this resource.
	 *
	 * @param version the version of this resource
	 */
	public void setVersion(int version);

	/**
	 * Returns the workflow action of this resource.
	 *
	 * @return the workflow action of this resource
	 */
	@AutoEscape
	public String getWorkflowAction();

	/**
	 * Sets the workflow action of this resource.
	 *
	 * @param workflowAction the workflow action of this resource
	 */
	public void setWorkflowAction(String workflowAction);

	/**
	 * Returns the feature ID of this resource.
	 *
	 * @return the feature ID of this resource
	 */
	public long getFeatureId();

	/**
	 * Sets the feature ID of this resource.
	 *
	 * @param featureId the feature ID of this resource
	 */
	public void setFeatureId(long featureId);

	public String[] getAvailableLanguageIds();

	public String getName();

	public String getName(String languageId);

	public String getName(String languageId, boolean useDefault);

	public String getNameMapAsXML();

	public Map<String, String> getLanguageIdToNameMap();

	public String getAttachName();

	public String getAttachName(String languageId);

	public String getAttachName(String languageId, boolean useDefault);

	public String getAttachNameMapAsXML();

	public Map<String, String> getLanguageIdToAttachNameMap();

	public String getAttach();

	public String getAttach(String languageId);

	public String getAttach(String languageId, boolean useDefault);

	public String getAttachMapAsXML();

	public Map<String, String> getLanguageIdToAttachMap();

	public String getDescription();

	public String getDescription(String languageId);

	public String getDescription(String languageId, boolean useDefault);

	public String getDescriptionMapAsXML();

	public Map<String, String> getLanguageIdToDescriptionMap();

	public String getRouteId();

	public String getRouteId(String languageId);

	public String getRouteId(String languageId, boolean useDefault);

	public String getRouteIdMapAsXML();

	public Map<String, String> getLanguageIdToRouteIdMap();

	public String getUrl();

	public String getUrl(String languageId);

	public String getUrl(String languageId, boolean useDefault);

	public String getUrlMapAsXML();

	public Map<String, String> getLanguageIdToUrlMap();

	/**
	 * Returns <code>true</code> if this resource is approved.
	 *
	 * @return <code>true</code> if this resource is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this resource is denied.
	 *
	 * @return <code>true</code> if this resource is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this resource is a draft.
	 *
	 * @return <code>true</code> if this resource is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this resource is expired.
	 *
	 * @return <code>true</code> if this resource is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this resource is inactive.
	 *
	 * @return <code>true</code> if this resource is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this resource is incomplete.
	 *
	 * @return <code>true</code> if this resource is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this resource is pending.
	 *
	 * @return <code>true</code> if this resource is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this resource is scheduled.
	 *
	 * @return <code>true</code> if this resource is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Resource cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}