/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Themes service. Represents a row in the &quot;THEMES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.telemony.db.model.impl.ThemesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.telemony.db.model.impl.ThemesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Themes
 * @generated
 */
@ProviderType
public interface ThemesModel
	extends BaseModel<Themes>, GroupedModel, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a themes model instance should use the {@link Themes} interface instead.
	 */

	/**
	 * Returns the primary key of this themes.
	 *
	 * @return the primary key of this themes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this themes.
	 *
	 * @param primaryKey the primary key of this themes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the theme ID of this themes.
	 *
	 * @return the theme ID of this themes
	 */
	public long getThemeId();

	/**
	 * Sets the theme ID of this themes.
	 *
	 * @param themeId the theme ID of this themes
	 */
	public void setThemeId(long themeId);

	/**
	 * Returns the channel ID of this themes.
	 *
	 * @return the channel ID of this themes
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this themes.
	 *
	 * @param channelId the channel ID of this themes
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the theme en name of this themes.
	 *
	 * @return the theme en name of this themes
	 */
	@AutoEscape
	public String getThemeEnName();

	/**
	 * Sets the theme en name of this themes.
	 *
	 * @param themeEnName the theme en name of this themes
	 */
	public void setThemeEnName(String themeEnName);

	/**
	 * Returns the theme ar name of this themes.
	 *
	 * @return the theme ar name of this themes
	 */
	@AutoEscape
	public String getThemeArName();

	/**
	 * Sets the theme ar name of this themes.
	 *
	 * @param themeArName the theme ar name of this themes
	 */
	public void setThemeArName(String themeArName);

	/**
	 * Returns the dark theme of this themes.
	 *
	 * @return the dark theme of this themes
	 */
	public boolean getDarkTheme();

	/**
	 * Returns <code>true</code> if this themes is dark theme.
	 *
	 * @return <code>true</code> if this themes is dark theme; <code>false</code> otherwise
	 */
	public boolean isDarkTheme();

	/**
	 * Sets whether this themes is dark theme.
	 *
	 * @param darkTheme the dark theme of this themes
	 */
	public void setDarkTheme(boolean darkTheme);

	/**
	 * Returns the primary colors of this themes.
	 *
	 * @return the primary colors of this themes
	 */
	@AutoEscape
	public String getPrimaryColors();

	/**
	 * Sets the primary colors of this themes.
	 *
	 * @param primaryColors the primary colors of this themes
	 */
	public void setPrimaryColors(String primaryColors);

	/**
	 * Returns the secondary colors of this themes.
	 *
	 * @return the secondary colors of this themes
	 */
	@AutoEscape
	public String getSecondaryColors();

	/**
	 * Sets the secondary colors of this themes.
	 *
	 * @param secondaryColors the secondary colors of this themes
	 */
	public void setSecondaryColors(String secondaryColors);

	/**
	 * Returns the neutral colors of this themes.
	 *
	 * @return the neutral colors of this themes
	 */
	@AutoEscape
	public String getNeutralColors();

	/**
	 * Sets the neutral colors of this themes.
	 *
	 * @param neutralColors the neutral colors of this themes
	 */
	public void setNeutralColors(String neutralColors);

	/**
	 * Returns the success colors of this themes.
	 *
	 * @return the success colors of this themes
	 */
	@AutoEscape
	public String getSuccessColors();

	/**
	 * Sets the success colors of this themes.
	 *
	 * @param successColors the success colors of this themes
	 */
	public void setSuccessColors(String successColors);

	/**
	 * Returns the error colors of this themes.
	 *
	 * @return the error colors of this themes
	 */
	@AutoEscape
	public String getErrorColors();

	/**
	 * Sets the error colors of this themes.
	 *
	 * @param errorColors the error colors of this themes
	 */
	public void setErrorColors(String errorColors);

	/**
	 * Returns the warning colors of this themes.
	 *
	 * @return the warning colors of this themes
	 */
	@AutoEscape
	public String getWarningColors();

	/**
	 * Sets the warning colors of this themes.
	 *
	 * @param warningColors the warning colors of this themes
	 */
	public void setWarningColors(String warningColors);

	/**
	 * Returns the support colors of this themes.
	 *
	 * @return the support colors of this themes
	 */
	@AutoEscape
	public String getSupportColors();

	/**
	 * Sets the support colors of this themes.
	 *
	 * @param supportColors the support colors of this themes
	 */
	public void setSupportColors(String supportColors);

	/**
	 * Returns the gradient colors of this themes.
	 *
	 * @return the gradient colors of this themes
	 */
	@AutoEscape
	public String getGradientColors();

	/**
	 * Sets the gradient colors of this themes.
	 *
	 * @param gradientColors the gradient colors of this themes
	 */
	public void setGradientColors(String gradientColors);

	/**
	 * Returns the splash bg of this themes.
	 *
	 * @return the splash bg of this themes
	 */
	@AutoEscape
	public String getSplashBg();

	/**
	 * Sets the splash bg of this themes.
	 *
	 * @param splashBg the splash bg of this themes
	 */
	public void setSplashBg(String splashBg);

	/**
	 * Returns the splash animation of this themes.
	 *
	 * @return the splash animation of this themes
	 */
	@AutoEscape
	public String getSplashAnimation();

	/**
	 * Sets the splash animation of this themes.
	 *
	 * @param splashAnimation the splash animation of this themes
	 */
	public void setSplashAnimation(String splashAnimation);

	/**
	 * Returns the header bg of this themes.
	 *
	 * @return the header bg of this themes
	 */
	@AutoEscape
	public String getHeaderBg();

	/**
	 * Sets the header bg of this themes.
	 *
	 * @param headerBg the header bg of this themes
	 */
	public void setHeaderBg(String headerBg);

	/**
	 * Returns the balance bg of this themes.
	 *
	 * @return the balance bg of this themes
	 */
	@AutoEscape
	public String getBalanceBg();

	/**
	 * Sets the balance bg of this themes.
	 *
	 * @param balanceBg the balance bg of this themes
	 */
	public void setBalanceBg(String balanceBg);

	/**
	 * Returns the default theme of this themes.
	 *
	 * @return the default theme of this themes
	 */
	public boolean getDefaultTheme();

	/**
	 * Returns <code>true</code> if this themes is default theme.
	 *
	 * @return <code>true</code> if this themes is default theme; <code>false</code> otherwise
	 */
	public boolean isDefaultTheme();

	/**
	 * Sets whether this themes is default theme.
	 *
	 * @param defaultTheme the default theme of this themes
	 */
	public void setDefaultTheme(boolean defaultTheme);

	/**
	 * Returns the group ID of this themes.
	 *
	 * @return the group ID of this themes
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this themes.
	 *
	 * @param groupId the group ID of this themes
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this themes.
	 *
	 * @return the company ID of this themes
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this themes.
	 *
	 * @param companyId the company ID of this themes
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this themes.
	 *
	 * @return the user ID of this themes
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this themes.
	 *
	 * @param userId the user ID of this themes
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this themes.
	 *
	 * @return the user uuid of this themes
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this themes.
	 *
	 * @param userUuid the user uuid of this themes
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this themes.
	 *
	 * @return the user name of this themes
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this themes.
	 *
	 * @param userName the user name of this themes
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this themes.
	 *
	 * @return the create date of this themes
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this themes.
	 *
	 * @param createDate the create date of this themes
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this themes.
	 *
	 * @return the modified date of this themes
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this themes.
	 *
	 * @param modifiedDate the modified date of this themes
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this themes.
	 *
	 * @return the status of this themes
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this themes.
	 *
	 * @param status the status of this themes
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this themes.
	 *
	 * @return the status by user ID of this themes
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this themes.
	 *
	 * @param statusByUserId the status by user ID of this themes
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this themes.
	 *
	 * @return the status by user uuid of this themes
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this themes.
	 *
	 * @param statusByUserUuid the status by user uuid of this themes
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this themes.
	 *
	 * @return the status by user name of this themes
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this themes.
	 *
	 * @param statusByUserName the status by user name of this themes
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this themes.
	 *
	 * @return the status date of this themes
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this themes.
	 *
	 * @param statusDate the status date of this themes
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the uuid_ of this themes.
	 *
	 * @return the uuid_ of this themes
	 */
	@AutoEscape
	public String getUuid_();

	/**
	 * Sets the uuid_ of this themes.
	 *
	 * @param uuid_ the uuid_ of this themes
	 */
	public void setUuid_(String uuid_);

	/**
	 * Returns the original entity ID of this themes.
	 *
	 * @return the original entity ID of this themes
	 */
	public long getOriginalEntityId();

	/**
	 * Sets the original entity ID of this themes.
	 *
	 * @param originalEntityId the original entity ID of this themes
	 */
	public void setOriginalEntityId(long originalEntityId);

	/**
	 * Returns the entity resource ID of this themes.
	 *
	 * @return the entity resource ID of this themes
	 */
	public long getEntityResourceId();

	/**
	 * Sets the entity resource ID of this themes.
	 *
	 * @param entityResourceId the entity resource ID of this themes
	 */
	public void setEntityResourceId(long entityResourceId);

	/**
	 * Returns the version of this themes.
	 *
	 * @return the version of this themes
	 */
	public int getVersion();

	/**
	 * Sets the version of this themes.
	 *
	 * @param version the version of this themes
	 */
	public void setVersion(int version);

	/**
	 * Returns the workflow action of this themes.
	 *
	 * @return the workflow action of this themes
	 */
	@AutoEscape
	public String getWorkflowAction();

	/**
	 * Sets the workflow action of this themes.
	 *
	 * @param workflowAction the workflow action of this themes
	 */
	public void setWorkflowAction(String workflowAction);

	/**
	 * Returns the import request ID of this themes.
	 *
	 * @return the import request ID of this themes
	 */
	public long getImportRequestId();

	/**
	 * Sets the import request ID of this themes.
	 *
	 * @param importRequestId the import request ID of this themes
	 */
	public void setImportRequestId(long importRequestId);

	/**
	 * Returns <code>true</code> if this themes is approved.
	 *
	 * @return <code>true</code> if this themes is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this themes is denied.
	 *
	 * @return <code>true</code> if this themes is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this themes is a draft.
	 *
	 * @return <code>true</code> if this themes is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this themes is expired.
	 *
	 * @return <code>true</code> if this themes is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this themes is inactive.
	 *
	 * @return <code>true</code> if this themes is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this themes is incomplete.
	 *
	 * @return <code>true</code> if this themes is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this themes is pending.
	 *
	 * @return <code>true</code> if this themes is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this themes is scheduled.
	 *
	 * @return <code>true</code> if this themes is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Themes cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}