/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.AppConfigItem;
import com.ejada.telemony.db.model.AppConfigItemModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppConfigItem service. Represents a row in the &quot;AppConfigItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppConfigItemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppConfigItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppConfigItemImpl
 * @generated
 */
@JSON(strict = true)
public class AppConfigItemModelImpl
	extends BaseModelImpl<AppConfigItem> implements AppConfigItemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app config item model instance should use the <code>AppConfigItem</code> interface instead.
	 */
	public static final String TABLE_NAME = "AppConfigItem";

	public static final Object[][] TABLE_COLUMNS = {
		{"configItemId", Types.BIGINT}, {"environmentId", Types.BIGINT},
		{"keyName", Types.VARCHAR}, {"valueType", Types.VARCHAR},
		{"value", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("configItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("environmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("keyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valueType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AppConfigItem (configItemId LONG not null primary key,environmentId LONG,keyName VARCHAR(75) null,valueType VARCHAR(75) null,value VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AppConfigItem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appConfigItem.configItemId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AppConfigItem.configItemId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENVIRONMENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONFIGITEMID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.AppConfigItem"));

	public AppConfigItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _configItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConfigItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _configItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppConfigItem.class;
	}

	@Override
	public String getModelClassName() {
		return AppConfigItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppConfigItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppConfigItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppConfigItem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppConfigItem)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppConfigItem, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppConfigItem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppConfigItem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppConfigItem, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppConfigItem, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppConfigItem, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppConfigItem, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppConfigItem, Object>>();

			attributeGetterFunctions.put(
				"configItemId", AppConfigItem::getConfigItemId);
			attributeGetterFunctions.put(
				"environmentId", AppConfigItem::getEnvironmentId);
			attributeGetterFunctions.put("keyName", AppConfigItem::getKeyName);
			attributeGetterFunctions.put(
				"valueType", AppConfigItem::getValueType);
			attributeGetterFunctions.put("value", AppConfigItem::getValue);
			attributeGetterFunctions.put(
				"createDate", AppConfigItem::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppConfigItem::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppConfigItem, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppConfigItem, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AppConfigItem, ?>>();

			attributeSetterBiConsumers.put(
				"configItemId",
				(BiConsumer<AppConfigItem, Long>)
					AppConfigItem::setConfigItemId);
			attributeSetterBiConsumers.put(
				"environmentId",
				(BiConsumer<AppConfigItem, Long>)
					AppConfigItem::setEnvironmentId);
			attributeSetterBiConsumers.put(
				"keyName",
				(BiConsumer<AppConfigItem, String>)AppConfigItem::setKeyName);
			attributeSetterBiConsumers.put(
				"valueType",
				(BiConsumer<AppConfigItem, String>)AppConfigItem::setValueType);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<AppConfigItem, String>)AppConfigItem::setValue);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppConfigItem, Date>)AppConfigItem::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppConfigItem, Date>)
					AppConfigItem::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getConfigItemId() {
		return _configItemId;
	}

	@Override
	public void setConfigItemId(long configItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_configItemId = configItemId;
	}

	@JSON
	@Override
	public long getEnvironmentId() {
		return _environmentId;
	}

	@Override
	public void setEnvironmentId(long environmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_environmentId = environmentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEnvironmentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("environmentId"));
	}

	@JSON
	@Override
	public String getKeyName() {
		if (_keyName == null) {
			return "";
		}
		else {
			return _keyName;
		}
	}

	@Override
	public void setKeyName(String keyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_keyName = keyName;
	}

	@JSON
	@Override
	public String getValueType() {
		if (_valueType == null) {
			return "";
		}
		else {
			return _valueType;
		}
	}

	@Override
	public void setValueType(String valueType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valueType = valueType;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AppConfigItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppConfigItem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppConfigItem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppConfigItemImpl appConfigItemImpl = new AppConfigItemImpl();

		appConfigItemImpl.setConfigItemId(getConfigItemId());
		appConfigItemImpl.setEnvironmentId(getEnvironmentId());
		appConfigItemImpl.setKeyName(getKeyName());
		appConfigItemImpl.setValueType(getValueType());
		appConfigItemImpl.setValue(getValue());
		appConfigItemImpl.setCreateDate(getCreateDate());
		appConfigItemImpl.setModifiedDate(getModifiedDate());

		appConfigItemImpl.resetOriginalValues();

		return appConfigItemImpl;
	}

	@Override
	public AppConfigItem cloneWithOriginalValues() {
		AppConfigItemImpl appConfigItemImpl = new AppConfigItemImpl();

		appConfigItemImpl.setConfigItemId(
			this.<Long>getColumnOriginalValue("configItemId"));
		appConfigItemImpl.setEnvironmentId(
			this.<Long>getColumnOriginalValue("environmentId"));
		appConfigItemImpl.setKeyName(
			this.<String>getColumnOriginalValue("keyName"));
		appConfigItemImpl.setValueType(
			this.<String>getColumnOriginalValue("valueType"));
		appConfigItemImpl.setValue(
			this.<String>getColumnOriginalValue("value"));
		appConfigItemImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appConfigItemImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return appConfigItemImpl;
	}

	@Override
	public int compareTo(AppConfigItem appConfigItem) {
		long primaryKey = appConfigItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppConfigItem)) {
			return false;
		}

		AppConfigItem appConfigItem = (AppConfigItem)object;

		long primaryKey = appConfigItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppConfigItem> toCacheModel() {
		AppConfigItemCacheModel appConfigItemCacheModel =
			new AppConfigItemCacheModel();

		appConfigItemCacheModel.configItemId = getConfigItemId();

		appConfigItemCacheModel.environmentId = getEnvironmentId();

		appConfigItemCacheModel.keyName = getKeyName();

		String keyName = appConfigItemCacheModel.keyName;

		if ((keyName != null) && (keyName.length() == 0)) {
			appConfigItemCacheModel.keyName = null;
		}

		appConfigItemCacheModel.valueType = getValueType();

		String valueType = appConfigItemCacheModel.valueType;

		if ((valueType != null) && (valueType.length() == 0)) {
			appConfigItemCacheModel.valueType = null;
		}

		appConfigItemCacheModel.value = getValue();

		String value = appConfigItemCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			appConfigItemCacheModel.value = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appConfigItemCacheModel.createDate = createDate.getTime();
		}
		else {
			appConfigItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appConfigItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appConfigItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return appConfigItemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppConfigItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppConfigItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppConfigItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AppConfigItem)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppConfigItem>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppConfigItem.class, ModelWrapper.class);

	}

	private long _configItemId;
	private long _environmentId;
	private String _keyName;
	private String _valueType;
	private String _value;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<AppConfigItem, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppConfigItem)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("configItemId", _configItemId);
		_columnOriginalValues.put("environmentId", _environmentId);
		_columnOriginalValues.put("keyName", _keyName);
		_columnOriginalValues.put("valueType", _valueType);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("configItemId", 1L);

		columnBitmasks.put("environmentId", 2L);

		columnBitmasks.put("keyName", 4L);

		columnBitmasks.put("valueType", 8L);

		columnBitmasks.put("value", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppConfigItem _escapedModel;

}