/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.AppEnvironment;
import com.ejada.telemony.db.model.AppEnvironmentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppEnvironment service. Represents a row in the &quot;AppEnvironment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppEnvironmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppEnvironmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppEnvironmentImpl
 * @generated
 */
@JSON(strict = true)
public class AppEnvironmentModelImpl
	extends BaseModelImpl<AppEnvironment> implements AppEnvironmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app environment model instance should use the <code>AppEnvironment</code> interface instead.
	 */
	public static final String TABLE_NAME = "AppEnvironment";

	public static final Object[][] TABLE_COLUMNS = {
		{"environmentId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"environmentName", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusDate", Types.TIMESTAMP}, {"uuid_", Types.VARCHAR},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT},
		{"version", Types.INTEGER}, {"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("environmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("environmentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AppEnvironment (environmentId LONG not null primary key,channelId LONG,environmentName VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,statusByUserId LONG,statusByUserName VARCHAR(75) null,status INTEGER,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AppEnvironment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appEnvironment.environmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AppEnvironment.environmentId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENVIRONMENTID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.AppEnvironment"));

	public AppEnvironmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _environmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEnvironmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _environmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppEnvironment.class;
	}

	@Override
	public String getModelClassName() {
		return AppEnvironment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppEnvironment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppEnvironment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppEnvironment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppEnvironment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppEnvironment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppEnvironment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppEnvironment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppEnvironment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppEnvironment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppEnvironment, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppEnvironment, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppEnvironment, Object>>();

			attributeGetterFunctions.put(
				"environmentId", AppEnvironment::getEnvironmentId);
			attributeGetterFunctions.put(
				"channelId", AppEnvironment::getChannelId);
			attributeGetterFunctions.put(
				"environmentName", AppEnvironment::getEnvironmentName);
			attributeGetterFunctions.put("groupId", AppEnvironment::getGroupId);
			attributeGetterFunctions.put(
				"companyId", AppEnvironment::getCompanyId);
			attributeGetterFunctions.put("userId", AppEnvironment::getUserId);
			attributeGetterFunctions.put(
				"userName", AppEnvironment::getUserName);
			attributeGetterFunctions.put(
				"createDate", AppEnvironment::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppEnvironment::getModifiedDate);
			attributeGetterFunctions.put(
				"statusByUserId", AppEnvironment::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", AppEnvironment::getStatusByUserName);
			attributeGetterFunctions.put("status", AppEnvironment::getStatus);
			attributeGetterFunctions.put(
				"statusDate", AppEnvironment::getStatusDate);
			attributeGetterFunctions.put("uuid_", AppEnvironment::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", AppEnvironment::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", AppEnvironment::getEntityResourceId);
			attributeGetterFunctions.put("version", AppEnvironment::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", AppEnvironment::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppEnvironment, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppEnvironment, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AppEnvironment, ?>>();

			attributeSetterBiConsumers.put(
				"environmentId",
				(BiConsumer<AppEnvironment, Long>)
					AppEnvironment::setEnvironmentId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<AppEnvironment, Long>)AppEnvironment::setChannelId);
			attributeSetterBiConsumers.put(
				"environmentName",
				(BiConsumer<AppEnvironment, String>)
					AppEnvironment::setEnvironmentName);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppEnvironment, Long>)AppEnvironment::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppEnvironment, Long>)AppEnvironment::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AppEnvironment, Long>)AppEnvironment::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AppEnvironment, String>)
					AppEnvironment::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppEnvironment, Date>)
					AppEnvironment::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppEnvironment, Date>)
					AppEnvironment::setModifiedDate);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<AppEnvironment, Long>)
					AppEnvironment::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<AppEnvironment, String>)
					AppEnvironment::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppEnvironment, Integer>)AppEnvironment::setStatus);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<AppEnvironment, Date>)
					AppEnvironment::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_",
				(BiConsumer<AppEnvironment, String>)AppEnvironment::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<AppEnvironment, Long>)
					AppEnvironment::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<AppEnvironment, Long>)
					AppEnvironment::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<AppEnvironment, Integer>)
					AppEnvironment::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<AppEnvironment, String>)
					AppEnvironment::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getEnvironmentId() {
		return _environmentId;
	}

	@Override
	public void setEnvironmentId(long environmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_environmentId = environmentId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getEnvironmentName() {
		if (_environmentName == null) {
			return "";
		}
		else {
			return _environmentName;
		}
	}

	@Override
	public void setEnvironmentName(String environmentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_environmentName = environmentName;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppEnvironment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppEnvironment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppEnvironment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppEnvironmentImpl appEnvironmentImpl = new AppEnvironmentImpl();

		appEnvironmentImpl.setEnvironmentId(getEnvironmentId());
		appEnvironmentImpl.setChannelId(getChannelId());
		appEnvironmentImpl.setEnvironmentName(getEnvironmentName());
		appEnvironmentImpl.setGroupId(getGroupId());
		appEnvironmentImpl.setCompanyId(getCompanyId());
		appEnvironmentImpl.setUserId(getUserId());
		appEnvironmentImpl.setUserName(getUserName());
		appEnvironmentImpl.setCreateDate(getCreateDate());
		appEnvironmentImpl.setModifiedDate(getModifiedDate());
		appEnvironmentImpl.setStatusByUserId(getStatusByUserId());
		appEnvironmentImpl.setStatusByUserName(getStatusByUserName());
		appEnvironmentImpl.setStatus(getStatus());
		appEnvironmentImpl.setStatusDate(getStatusDate());
		appEnvironmentImpl.setUuid_(getUuid_());
		appEnvironmentImpl.setOriginalEntityId(getOriginalEntityId());
		appEnvironmentImpl.setEntityResourceId(getEntityResourceId());
		appEnvironmentImpl.setVersion(getVersion());
		appEnvironmentImpl.setWorkflowAction(getWorkflowAction());

		appEnvironmentImpl.resetOriginalValues();

		return appEnvironmentImpl;
	}

	@Override
	public AppEnvironment cloneWithOriginalValues() {
		AppEnvironmentImpl appEnvironmentImpl = new AppEnvironmentImpl();

		appEnvironmentImpl.setEnvironmentId(
			this.<Long>getColumnOriginalValue("environmentId"));
		appEnvironmentImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		appEnvironmentImpl.setEnvironmentName(
			this.<String>getColumnOriginalValue("environmentName"));
		appEnvironmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appEnvironmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appEnvironmentImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		appEnvironmentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		appEnvironmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appEnvironmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appEnvironmentImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		appEnvironmentImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		appEnvironmentImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		appEnvironmentImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		appEnvironmentImpl.setUuid_(
			this.<String>getColumnOriginalValue("uuid_"));
		appEnvironmentImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		appEnvironmentImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		appEnvironmentImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		appEnvironmentImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return appEnvironmentImpl;
	}

	@Override
	public int compareTo(AppEnvironment appEnvironment) {
		long primaryKey = appEnvironment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppEnvironment)) {
			return false;
		}

		AppEnvironment appEnvironment = (AppEnvironment)object;

		long primaryKey = appEnvironment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppEnvironment> toCacheModel() {
		AppEnvironmentCacheModel appEnvironmentCacheModel =
			new AppEnvironmentCacheModel();

		appEnvironmentCacheModel.environmentId = getEnvironmentId();

		appEnvironmentCacheModel.channelId = getChannelId();

		appEnvironmentCacheModel.environmentName = getEnvironmentName();

		String environmentName = appEnvironmentCacheModel.environmentName;

		if ((environmentName != null) && (environmentName.length() == 0)) {
			appEnvironmentCacheModel.environmentName = null;
		}

		appEnvironmentCacheModel.groupId = getGroupId();

		appEnvironmentCacheModel.companyId = getCompanyId();

		appEnvironmentCacheModel.userId = getUserId();

		appEnvironmentCacheModel.userName = getUserName();

		String userName = appEnvironmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			appEnvironmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appEnvironmentCacheModel.createDate = createDate.getTime();
		}
		else {
			appEnvironmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appEnvironmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appEnvironmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appEnvironmentCacheModel.statusByUserId = getStatusByUserId();

		appEnvironmentCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = appEnvironmentCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			appEnvironmentCacheModel.statusByUserName = null;
		}

		appEnvironmentCacheModel.status = getStatus();

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			appEnvironmentCacheModel.statusDate = statusDate.getTime();
		}
		else {
			appEnvironmentCacheModel.statusDate = Long.MIN_VALUE;
		}

		appEnvironmentCacheModel.uuid_ = getUuid_();

		String uuid_ = appEnvironmentCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			appEnvironmentCacheModel.uuid_ = null;
		}

		appEnvironmentCacheModel.originalEntityId = getOriginalEntityId();

		appEnvironmentCacheModel.entityResourceId = getEntityResourceId();

		appEnvironmentCacheModel.version = getVersion();

		appEnvironmentCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = appEnvironmentCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			appEnvironmentCacheModel.workflowAction = null;
		}

		return appEnvironmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppEnvironment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppEnvironment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppEnvironment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AppEnvironment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppEnvironment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppEnvironment.class, ModelWrapper.class);

	}

	private long _environmentId;
	private long _channelId;
	private String _environmentName;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _statusByUserId;
	private String _statusByUserName;
	private int _status;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<AppEnvironment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppEnvironment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("environmentId", _environmentId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("environmentName", _environmentName);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("environmentId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("environmentName", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("statusDate", 4096L);

		columnBitmasks.put("uuid_", 8192L);

		columnBitmasks.put("originalEntityId", 16384L);

		columnBitmasks.put("entityResourceId", 32768L);

		columnBitmasks.put("version", 65536L);

		columnBitmasks.put("workflowAction", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppEnvironment _escapedModel;

}