/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.AppVersion;
import com.ejada.telemony.db.model.AppVersionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppVersion service. Represents a row in the &quot;AppVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppVersionImpl
 * @generated
 */
@JSON(strict = true)
public class AppVersionModelImpl
	extends BaseModelImpl<AppVersion> implements AppVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app version model instance should use the <code>AppVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "AppVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"versionId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"platform", Types.VARCHAR}, {"versionNumber", Types.VARCHAR},
		{"url", Types.VARCHAR}, {"appVersionStatus", Types.BOOLEAN},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"version", Types.INTEGER},
		{"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("versionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("platform", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("versionNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appVersionStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AppVersion (versionId LONG not null primary key,channelId LONG,platform VARCHAR(75) null,versionNumber VARCHAR(75) null,url VARCHAR(75) null,appVersionStatus BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AppVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appVersion.versionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AppVersion.versionId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLATFORM_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSIONID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.AppVersion"));

	public AppVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _versionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _versionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppVersion.class;
	}

	@Override
	public String getModelClassName() {
		return AppVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AppVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppVersion, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppVersion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppVersion, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppVersion, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppVersion, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppVersion, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<AppVersion, Object>>();

			attributeGetterFunctions.put("versionId", AppVersion::getVersionId);
			attributeGetterFunctions.put("channelId", AppVersion::getChannelId);
			attributeGetterFunctions.put("platform", AppVersion::getPlatform);
			attributeGetterFunctions.put(
				"versionNumber", AppVersion::getVersionNumber);
			attributeGetterFunctions.put("url", AppVersion::getUrl);
			attributeGetterFunctions.put(
				"appVersionStatus", AppVersion::getAppVersionStatus);
			attributeGetterFunctions.put("groupId", AppVersion::getGroupId);
			attributeGetterFunctions.put("companyId", AppVersion::getCompanyId);
			attributeGetterFunctions.put("userId", AppVersion::getUserId);
			attributeGetterFunctions.put("userName", AppVersion::getUserName);
			attributeGetterFunctions.put(
				"createDate", AppVersion::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppVersion::getModifiedDate);
			attributeGetterFunctions.put("status", AppVersion::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", AppVersion::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", AppVersion::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", AppVersion::getStatusDate);
			attributeGetterFunctions.put("uuid_", AppVersion::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", AppVersion::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", AppVersion::getEntityResourceId);
			attributeGetterFunctions.put("version", AppVersion::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", AppVersion::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppVersion, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppVersion, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AppVersion, ?>>();

			attributeSetterBiConsumers.put(
				"versionId",
				(BiConsumer<AppVersion, Long>)AppVersion::setVersionId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<AppVersion, Long>)AppVersion::setChannelId);
			attributeSetterBiConsumers.put(
				"platform",
				(BiConsumer<AppVersion, String>)AppVersion::setPlatform);
			attributeSetterBiConsumers.put(
				"versionNumber",
				(BiConsumer<AppVersion, String>)AppVersion::setVersionNumber);
			attributeSetterBiConsumers.put(
				"url", (BiConsumer<AppVersion, String>)AppVersion::setUrl);
			attributeSetterBiConsumers.put(
				"appVersionStatus",
				(BiConsumer<AppVersion, Boolean>)
					AppVersion::setAppVersionStatus);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppVersion, Long>)AppVersion::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppVersion, Long>)AppVersion::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<AppVersion, Long>)AppVersion::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AppVersion, String>)AppVersion::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppVersion, Date>)AppVersion::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppVersion, Date>)AppVersion::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppVersion, Integer>)AppVersion::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<AppVersion, Long>)AppVersion::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<AppVersion, String>)
					AppVersion::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<AppVersion, Date>)AppVersion::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<AppVersion, String>)AppVersion::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<AppVersion, Long>)AppVersion::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<AppVersion, Long>)AppVersion::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<AppVersion, Integer>)AppVersion::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<AppVersion, String>)AppVersion::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getVersionId() {
		return _versionId;
	}

	@Override
	public void setVersionId(long versionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_versionId = versionId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getPlatform() {
		if (_platform == null) {
			return "";
		}
		else {
			return _platform;
		}
	}

	@Override
	public void setPlatform(String platform) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_platform = platform;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPlatform() {
		return getColumnOriginalValue("platform");
	}

	@JSON
	@Override
	public String getVersionNumber() {
		if (_versionNumber == null) {
			return "";
		}
		else {
			return _versionNumber;
		}
	}

	@Override
	public void setVersionNumber(String versionNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_versionNumber = versionNumber;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public Boolean getAppVersionStatus() {
		return _appVersionStatus;
	}

	@Override
	public void setAppVersionStatus(Boolean appVersionStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appVersionStatus = appVersionStatus;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppVersionImpl appVersionImpl = new AppVersionImpl();

		appVersionImpl.setVersionId(getVersionId());
		appVersionImpl.setChannelId(getChannelId());
		appVersionImpl.setPlatform(getPlatform());
		appVersionImpl.setVersionNumber(getVersionNumber());
		appVersionImpl.setUrl(getUrl());
		appVersionImpl.setAppVersionStatus(getAppVersionStatus());
		appVersionImpl.setGroupId(getGroupId());
		appVersionImpl.setCompanyId(getCompanyId());
		appVersionImpl.setUserId(getUserId());
		appVersionImpl.setUserName(getUserName());
		appVersionImpl.setCreateDate(getCreateDate());
		appVersionImpl.setModifiedDate(getModifiedDate());
		appVersionImpl.setStatus(getStatus());
		appVersionImpl.setStatusByUserId(getStatusByUserId());
		appVersionImpl.setStatusByUserName(getStatusByUserName());
		appVersionImpl.setStatusDate(getStatusDate());
		appVersionImpl.setUuid_(getUuid_());
		appVersionImpl.setOriginalEntityId(getOriginalEntityId());
		appVersionImpl.setEntityResourceId(getEntityResourceId());
		appVersionImpl.setVersion(getVersion());
		appVersionImpl.setWorkflowAction(getWorkflowAction());

		appVersionImpl.resetOriginalValues();

		return appVersionImpl;
	}

	@Override
	public AppVersion cloneWithOriginalValues() {
		AppVersionImpl appVersionImpl = new AppVersionImpl();

		appVersionImpl.setVersionId(
			this.<Long>getColumnOriginalValue("versionId"));
		appVersionImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		appVersionImpl.setPlatform(
			this.<String>getColumnOriginalValue("platform"));
		appVersionImpl.setVersionNumber(
			this.<String>getColumnOriginalValue("versionNumber"));
		appVersionImpl.setUrl(this.<String>getColumnOriginalValue("url"));
		appVersionImpl.setAppVersionStatus(
			this.<Boolean>getColumnOriginalValue("appVersionStatus"));
		appVersionImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		appVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appVersionImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		appVersionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		appVersionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appVersionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appVersionImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		appVersionImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		appVersionImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		appVersionImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		appVersionImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		appVersionImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		appVersionImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		appVersionImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		appVersionImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return appVersionImpl;
	}

	@Override
	public int compareTo(AppVersion appVersion) {
		long primaryKey = appVersion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppVersion)) {
			return false;
		}

		AppVersion appVersion = (AppVersion)object;

		long primaryKey = appVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppVersion> toCacheModel() {
		AppVersionCacheModel appVersionCacheModel = new AppVersionCacheModel();

		appVersionCacheModel.versionId = getVersionId();

		appVersionCacheModel.channelId = getChannelId();

		appVersionCacheModel.platform = getPlatform();

		String platform = appVersionCacheModel.platform;

		if ((platform != null) && (platform.length() == 0)) {
			appVersionCacheModel.platform = null;
		}

		appVersionCacheModel.versionNumber = getVersionNumber();

		String versionNumber = appVersionCacheModel.versionNumber;

		if ((versionNumber != null) && (versionNumber.length() == 0)) {
			appVersionCacheModel.versionNumber = null;
		}

		appVersionCacheModel.url = getUrl();

		String url = appVersionCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			appVersionCacheModel.url = null;
		}

		Boolean appVersionStatus = getAppVersionStatus();

		if (appVersionStatus != null) {
			appVersionCacheModel.appVersionStatus = appVersionStatus;
		}

		appVersionCacheModel.groupId = getGroupId();

		appVersionCacheModel.companyId = getCompanyId();

		appVersionCacheModel.userId = getUserId();

		appVersionCacheModel.userName = getUserName();

		String userName = appVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			appVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			appVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appVersionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appVersionCacheModel.status = getStatus();

		appVersionCacheModel.statusByUserId = getStatusByUserId();

		appVersionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = appVersionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			appVersionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			appVersionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			appVersionCacheModel.statusDate = Long.MIN_VALUE;
		}

		appVersionCacheModel.uuid_ = getUuid_();

		String uuid_ = appVersionCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			appVersionCacheModel.uuid_ = null;
		}

		appVersionCacheModel.originalEntityId = getOriginalEntityId();

		appVersionCacheModel.entityResourceId = getEntityResourceId();

		appVersionCacheModel.version = getVersion();

		appVersionCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = appVersionCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			appVersionCacheModel.workflowAction = null;
		}

		return appVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AppVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppVersion.class, ModelWrapper.class);

	}

	private long _versionId;
	private long _channelId;
	private String _platform;
	private String _versionNumber;
	private String _url;
	private Boolean _appVersionStatus;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<AppVersion, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("versionId", _versionId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("platform", _platform);
		_columnOriginalValues.put("versionNumber", _versionNumber);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("appVersionStatus", _appVersionStatus);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("versionId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("platform", 4L);

		columnBitmasks.put("versionNumber", 8L);

		columnBitmasks.put("url", 16L);

		columnBitmasks.put("appVersionStatus", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		columnBitmasks.put("uuid_", 65536L);

		columnBitmasks.put("originalEntityId", 131072L);

		columnBitmasks.put("entityResourceId", 262144L);

		columnBitmasks.put("version", 524288L);

		columnBitmasks.put("workflowAction", 1048576L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppVersion _escapedModel;

}