/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.BannerContent;
import com.ejada.telemony.db.model.BannerContentLocalization;
import com.ejada.telemony.db.model.BannerContentModel;
import com.ejada.telemony.db.service.BannerContentLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BannerContent service. Represents a row in the &quot;BANNER_CONTENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BannerContentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerContentImpl
 * @generated
 */
@JSON(strict = true)
public class BannerContentModelImpl
	extends BaseModelImpl<BannerContent> implements BannerContentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banner content model instance should use the <code>BannerContent</code> interface instead.
	 */
	public static final String TABLE_NAME = "BANNER_CONTENT";

	public static final Object[][] TABLE_COLUMNS = {
		{"defaultLanguageId", Types.VARCHAR}, {"contentId", Types.BIGINT},
		{"contentName", Types.VARCHAR}, {"contentOrder", Types.INTEGER},
		{"bannerId", Types.BIGINT}, {"contentStatus", Types.VARCHAR},
		{"channelId", Types.BIGINT}, {"status", Types.INTEGER},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contentOrder", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("bannerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BANNER_CONTENT (defaultLanguageId VARCHAR(75) null,contentId LONG not null primary key,contentName VARCHAR(75) null,contentOrder INTEGER,bannerId LONG,contentStatus VARCHAR(75) null,channelId LONG,status INTEGER,originalEntityId LONG,entityResourceId LONG)";

	public static final String TABLE_SQL_DROP = "drop table BANNER_CONTENT";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bannerContent.contentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BANNER_CONTENT.contentId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BANNERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTENTID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.BannerContent"));

	public BannerContentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BannerContent.class;
	}

	@Override
	public String getModelClassName() {
		return BannerContent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BannerContent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BannerContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BannerContent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BannerContent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BannerContent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BannerContent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BannerContent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BannerContent, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BannerContent, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BannerContent, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BannerContent, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BannerContent, Object>>();

			attributeGetterFunctions.put(
				"defaultLanguageId", BannerContent::getDefaultLanguageId);
			attributeGetterFunctions.put(
				"contentId", BannerContent::getContentId);
			attributeGetterFunctions.put(
				"contentName", BannerContent::getContentName);
			attributeGetterFunctions.put(
				"contentOrder", BannerContent::getContentOrder);
			attributeGetterFunctions.put(
				"bannerId", BannerContent::getBannerId);
			attributeGetterFunctions.put(
				"contentStatus", BannerContent::getContentStatus);
			attributeGetterFunctions.put(
				"channelId", BannerContent::getChannelId);
			attributeGetterFunctions.put("status", BannerContent::getStatus);
			attributeGetterFunctions.put(
				"originalEntityId", BannerContent::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", BannerContent::getEntityResourceId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BannerContent, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BannerContent, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BannerContent, ?>>();

			attributeSetterBiConsumers.put(
				"defaultLanguageId",
				(BiConsumer<BannerContent, String>)
					BannerContent::setDefaultLanguageId);
			attributeSetterBiConsumers.put(
				"contentId",
				(BiConsumer<BannerContent, Long>)BannerContent::setContentId);
			attributeSetterBiConsumers.put(
				"contentName",
				(BiConsumer<BannerContent, String>)
					BannerContent::setContentName);
			attributeSetterBiConsumers.put(
				"contentOrder",
				(BiConsumer<BannerContent, Integer>)
					BannerContent::setContentOrder);
			attributeSetterBiConsumers.put(
				"bannerId",
				(BiConsumer<BannerContent, Long>)BannerContent::setBannerId);
			attributeSetterBiConsumers.put(
				"contentStatus",
				(BiConsumer<BannerContent, String>)
					BannerContent::setContentStatus);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<BannerContent, Long>)BannerContent::setChannelId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<BannerContent, Integer>)BannerContent::setStatus);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<BannerContent, Long>)
					BannerContent::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<BannerContent, Long>)
					BannerContent::setEntityResourceId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<BannerContentLocalization> bannerContentLocalizations =
			BannerContentLocalServiceUtil.getBannerContentLocalizations(
				getPrimaryKey());

		String[] availableLanguageIds =
			new String[bannerContentLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			BannerContentLocalization bannerContentLocalization =
				bannerContentLocalizations.get(i);

			availableLanguageIds[i] = bannerContentLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getTitleValue() {
		return getTitleValue(getDefaultLanguageId(), false);
	}

	@Override
	public String getTitleValue(String languageId) {
		return getTitleValue(languageId, true);
	}

	@Override
	public String getTitleValue(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getTitleValue(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getTitleValue(languageId);
	}

	@Override
	public String getTitleValueMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToTitleValueMap(), getDefaultLanguageId(),
			"TitleValue");
	}

	@Override
	public Map<String, String> getLanguageIdToTitleValueMap() {
		Map<String, String> languageIdToTitleValueMap =
			new HashMap<String, String>();

		List<BannerContentLocalization> bannerContentLocalizations =
			BannerContentLocalServiceUtil.getBannerContentLocalizations(
				getPrimaryKey());

		for (BannerContentLocalization bannerContentLocalization :
				bannerContentLocalizations) {

			languageIdToTitleValueMap.put(
				bannerContentLocalization.getLanguageId(),
				bannerContentLocalization.getTitleValue());
		}

		return languageIdToTitleValueMap;
	}

	private String _getTitleValue(String languageId) {
		BannerContentLocalization bannerContentLocalization =
			BannerContentLocalServiceUtil.fetchBannerContentLocalization(
				getPrimaryKey(), languageId);

		if (bannerContentLocalization == null) {
			return "";
		}

		return bannerContentLocalization.getTitleValue();
	}

	@Override
	public String getDescriptionValue() {
		return getDescriptionValue(getDefaultLanguageId(), false);
	}

	@Override
	public String getDescriptionValue(String languageId) {
		return getDescriptionValue(languageId, true);
	}

	@Override
	public String getDescriptionValue(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getDescriptionValue(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getDescriptionValue(languageId);
	}

	@Override
	public String getDescriptionValueMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToDescriptionValueMap(), getDefaultLanguageId(),
			"DescriptionValue");
	}

	@Override
	public Map<String, String> getLanguageIdToDescriptionValueMap() {
		Map<String, String> languageIdToDescriptionValueMap =
			new HashMap<String, String>();

		List<BannerContentLocalization> bannerContentLocalizations =
			BannerContentLocalServiceUtil.getBannerContentLocalizations(
				getPrimaryKey());

		for (BannerContentLocalization bannerContentLocalization :
				bannerContentLocalizations) {

			languageIdToDescriptionValueMap.put(
				bannerContentLocalization.getLanguageId(),
				bannerContentLocalization.getDescriptionValue());
		}

		return languageIdToDescriptionValueMap;
	}

	private String _getDescriptionValue(String languageId) {
		BannerContentLocalization bannerContentLocalization =
			BannerContentLocalServiceUtil.fetchBannerContentLocalization(
				getPrimaryKey(), languageId);

		if (bannerContentLocalization == null) {
			return "";
		}

		return bannerContentLocalization.getDescriptionValue();
	}

	@JSON
	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultLanguageId = defaultLanguageId;
	}

	@JSON
	@Override
	public long getContentId() {
		return _contentId;
	}

	@Override
	public void setContentId(long contentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentId = contentId;
	}

	@JSON
	@Override
	public String getContentName() {
		if (_contentName == null) {
			return "";
		}
		else {
			return _contentName;
		}
	}

	@Override
	public void setContentName(String contentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentName = contentName;
	}

	@JSON
	@Override
	public int getContentOrder() {
		return _contentOrder;
	}

	@Override
	public void setContentOrder(int contentOrder) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentOrder = contentOrder;
	}

	@JSON
	@Override
	public long getBannerId() {
		return _bannerId;
	}

	@Override
	public void setBannerId(long bannerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerId = bannerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBannerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("bannerId"));
	}

	@JSON
	@Override
	public String getContentStatus() {
		if (_contentStatus == null) {
			return "";
		}
		else {
			return _contentStatus;
		}
	}

	@Override
	public void setContentStatus(String contentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentStatus = contentStatus;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BannerContent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BannerContent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BannerContent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BannerContentImpl bannerContentImpl = new BannerContentImpl();

		bannerContentImpl.setDefaultLanguageId(getDefaultLanguageId());
		bannerContentImpl.setContentId(getContentId());
		bannerContentImpl.setContentName(getContentName());
		bannerContentImpl.setContentOrder(getContentOrder());
		bannerContentImpl.setBannerId(getBannerId());
		bannerContentImpl.setContentStatus(getContentStatus());
		bannerContentImpl.setChannelId(getChannelId());
		bannerContentImpl.setStatus(getStatus());
		bannerContentImpl.setOriginalEntityId(getOriginalEntityId());
		bannerContentImpl.setEntityResourceId(getEntityResourceId());

		bannerContentImpl.resetOriginalValues();

		return bannerContentImpl;
	}

	@Override
	public BannerContent cloneWithOriginalValues() {
		BannerContentImpl bannerContentImpl = new BannerContentImpl();

		bannerContentImpl.setDefaultLanguageId(
			this.<String>getColumnOriginalValue("defaultLanguageId"));
		bannerContentImpl.setContentId(
			this.<Long>getColumnOriginalValue("contentId"));
		bannerContentImpl.setContentName(
			this.<String>getColumnOriginalValue("contentName"));
		bannerContentImpl.setContentOrder(
			this.<Integer>getColumnOriginalValue("contentOrder"));
		bannerContentImpl.setBannerId(
			this.<Long>getColumnOriginalValue("bannerId"));
		bannerContentImpl.setContentStatus(
			this.<String>getColumnOriginalValue("contentStatus"));
		bannerContentImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		bannerContentImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		bannerContentImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		bannerContentImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));

		return bannerContentImpl;
	}

	@Override
	public int compareTo(BannerContent bannerContent) {
		long primaryKey = bannerContent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BannerContent)) {
			return false;
		}

		BannerContent bannerContent = (BannerContent)object;

		long primaryKey = bannerContent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BannerContent> toCacheModel() {
		BannerContentCacheModel bannerContentCacheModel =
			new BannerContentCacheModel();

		bannerContentCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = bannerContentCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			bannerContentCacheModel.defaultLanguageId = null;
		}

		bannerContentCacheModel.contentId = getContentId();

		bannerContentCacheModel.contentName = getContentName();

		String contentName = bannerContentCacheModel.contentName;

		if ((contentName != null) && (contentName.length() == 0)) {
			bannerContentCacheModel.contentName = null;
		}

		bannerContentCacheModel.contentOrder = getContentOrder();

		bannerContentCacheModel.bannerId = getBannerId();

		bannerContentCacheModel.contentStatus = getContentStatus();

		String contentStatus = bannerContentCacheModel.contentStatus;

		if ((contentStatus != null) && (contentStatus.length() == 0)) {
			bannerContentCacheModel.contentStatus = null;
		}

		bannerContentCacheModel.channelId = getChannelId();

		bannerContentCacheModel.status = getStatus();

		bannerContentCacheModel.originalEntityId = getOriginalEntityId();

		bannerContentCacheModel.entityResourceId = getEntityResourceId();

		return bannerContentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BannerContent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BannerContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BannerContent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BannerContent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BannerContent>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BannerContent.class, ModelWrapper.class);

	}

	private String _defaultLanguageId;
	private long _contentId;
	private String _contentName;
	private int _contentOrder;
	private long _bannerId;
	private String _contentStatus;
	private long _channelId;
	private int _status;
	private long _originalEntityId;
	private long _entityResourceId;

	public <T> T getColumnValue(String columnName) {
		Function<BannerContent, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BannerContent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("defaultLanguageId", _defaultLanguageId);
		_columnOriginalValues.put("contentId", _contentId);
		_columnOriginalValues.put("contentName", _contentName);
		_columnOriginalValues.put("contentOrder", _contentOrder);
		_columnOriginalValues.put("bannerId", _bannerId);
		_columnOriginalValues.put("contentStatus", _contentStatus);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("defaultLanguageId", 1L);

		columnBitmasks.put("contentId", 2L);

		columnBitmasks.put("contentName", 4L);

		columnBitmasks.put("contentOrder", 8L);

		columnBitmasks.put("bannerId", 16L);

		columnBitmasks.put("contentStatus", 32L);

		columnBitmasks.put("channelId", 64L);

		columnBitmasks.put("status", 128L);

		columnBitmasks.put("originalEntityId", 256L);

		columnBitmasks.put("entityResourceId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BannerContent _escapedModel;

}