/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.BannerContentLocalization;
import com.ejada.telemony.db.model.BannerContentLocalizationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BannerContentLocalization service. Represents a row in the &quot;BannerContentLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BannerContentLocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerContentLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerContentLocalizationImpl
 * @generated
 */
public class BannerContentLocalizationModelImpl
	extends BaseModelImpl<BannerContentLocalization>
	implements BannerContentLocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banner content localization model instance should use the <code>BannerContentLocalization</code> interface instead.
	 */
	public static final String TABLE_NAME = "BannerContentLocalization";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"bannerContentLocalizationId", Types.BIGINT},
		{"contentId", Types.BIGINT}, {"languageId", Types.VARCHAR},
		{"bannerImage", Types.VARCHAR}, {"imageOverlay", Types.VARCHAR},
		{"linkType", Types.VARCHAR}, {"url", Types.VARCHAR},
		{"titleValue", Types.VARCHAR}, {"descriptionValue", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bannerContentLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bannerImage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageOverlay", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("titleValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descriptionValue", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BannerContentLocalization (mvccVersion LONG default 0 not null,bannerContentLocalizationId LONG not null primary key,contentId LONG,languageId VARCHAR(75) null,bannerImage VARCHAR(75) null,imageOverlay VARCHAR(75) null,linkType VARCHAR(75) null,url VARCHAR(75) null,titleValue VARCHAR(75) null,descriptionValue VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BannerContentLocalization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bannerContentLocalization.bannerContentLocalizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BannerContentLocalization.bannerContentLocalizationId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BANNERCONTENTLOCALIZATIONID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.BannerContentLocalization"));

	public BannerContentLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bannerContentLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBannerContentLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bannerContentLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BannerContentLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return BannerContentLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BannerContentLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BannerContentLocalization, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BannerContentLocalization, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BannerContentLocalization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BannerContentLocalization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BannerContentLocalization, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BannerContentLocalization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BannerContentLocalization, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BannerContentLocalization, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<BannerContentLocalization, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<BannerContentLocalization, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BannerContentLocalization, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", BannerContentLocalization::getMvccVersion);
			attributeGetterFunctions.put(
				"bannerContentLocalizationId",
				BannerContentLocalization::getBannerContentLocalizationId);
			attributeGetterFunctions.put(
				"contentId", BannerContentLocalization::getContentId);
			attributeGetterFunctions.put(
				"languageId", BannerContentLocalization::getLanguageId);
			attributeGetterFunctions.put(
				"bannerImage", BannerContentLocalization::getBannerImage);
			attributeGetterFunctions.put(
				"imageOverlay", BannerContentLocalization::getImageOverlay);
			attributeGetterFunctions.put(
				"linkType", BannerContentLocalization::getLinkType);
			attributeGetterFunctions.put(
				"url", BannerContentLocalization::getUrl);
			attributeGetterFunctions.put(
				"titleValue", BannerContentLocalization::getTitleValue);
			attributeGetterFunctions.put(
				"descriptionValue",
				BannerContentLocalization::getDescriptionValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<BannerContentLocalization, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BannerContentLocalization, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BannerContentLocalization, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<BannerContentLocalization, Long>)
					BannerContentLocalization::setMvccVersion);
			attributeSetterBiConsumers.put(
				"bannerContentLocalizationId",
				(BiConsumer<BannerContentLocalization, Long>)
					BannerContentLocalization::setBannerContentLocalizationId);
			attributeSetterBiConsumers.put(
				"contentId",
				(BiConsumer<BannerContentLocalization, Long>)
					BannerContentLocalization::setContentId);
			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setLanguageId);
			attributeSetterBiConsumers.put(
				"bannerImage",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setBannerImage);
			attributeSetterBiConsumers.put(
				"imageOverlay",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setImageOverlay);
			attributeSetterBiConsumers.put(
				"linkType",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setLinkType);
			attributeSetterBiConsumers.put(
				"url",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setUrl);
			attributeSetterBiConsumers.put(
				"titleValue",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setTitleValue);
			attributeSetterBiConsumers.put(
				"descriptionValue",
				(BiConsumer<BannerContentLocalization, String>)
					BannerContentLocalization::setDescriptionValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getBannerContentLocalizationId() {
		return _bannerContentLocalizationId;
	}

	@Override
	public void setBannerContentLocalizationId(
		long bannerContentLocalizationId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerContentLocalizationId = bannerContentLocalizationId;
	}

	@Override
	public long getContentId() {
		return _contentId;
	}

	@Override
	public void setContentId(long contentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentId = contentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalContentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("contentId"));
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@Override
	public String getBannerImage() {
		if (_bannerImage == null) {
			return "";
		}
		else {
			return _bannerImage;
		}
	}

	@Override
	public void setBannerImage(String bannerImage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerImage = bannerImage;
	}

	@Override
	public String getImageOverlay() {
		if (_imageOverlay == null) {
			return "";
		}
		else {
			return _imageOverlay;
		}
	}

	@Override
	public void setImageOverlay(String imageOverlay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageOverlay = imageOverlay;
	}

	@Override
	public String getLinkType() {
		if (_linkType == null) {
			return "";
		}
		else {
			return _linkType;
		}
	}

	@Override
	public void setLinkType(String linkType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkType = linkType;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@Override
	public String getTitleValue() {
		if (_titleValue == null) {
			return "";
		}
		else {
			return _titleValue;
		}
	}

	@Override
	public void setTitleValue(String titleValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_titleValue = titleValue;
	}

	@Override
	public String getDescriptionValue() {
		if (_descriptionValue == null) {
			return "";
		}
		else {
			return _descriptionValue;
		}
	}

	@Override
	public void setDescriptionValue(String descriptionValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descriptionValue = descriptionValue;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BannerContentLocalization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BannerContentLocalization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BannerContentLocalization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BannerContentLocalizationImpl bannerContentLocalizationImpl =
			new BannerContentLocalizationImpl();

		bannerContentLocalizationImpl.setMvccVersion(getMvccVersion());
		bannerContentLocalizationImpl.setBannerContentLocalizationId(
			getBannerContentLocalizationId());
		bannerContentLocalizationImpl.setContentId(getContentId());
		bannerContentLocalizationImpl.setLanguageId(getLanguageId());
		bannerContentLocalizationImpl.setBannerImage(getBannerImage());
		bannerContentLocalizationImpl.setImageOverlay(getImageOverlay());
		bannerContentLocalizationImpl.setLinkType(getLinkType());
		bannerContentLocalizationImpl.setUrl(getUrl());
		bannerContentLocalizationImpl.setTitleValue(getTitleValue());
		bannerContentLocalizationImpl.setDescriptionValue(
			getDescriptionValue());

		bannerContentLocalizationImpl.resetOriginalValues();

		return bannerContentLocalizationImpl;
	}

	@Override
	public BannerContentLocalization cloneWithOriginalValues() {
		BannerContentLocalizationImpl bannerContentLocalizationImpl =
			new BannerContentLocalizationImpl();

		bannerContentLocalizationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		bannerContentLocalizationImpl.setBannerContentLocalizationId(
			this.<Long>getColumnOriginalValue("bannerContentLocalizationId"));
		bannerContentLocalizationImpl.setContentId(
			this.<Long>getColumnOriginalValue("contentId"));
		bannerContentLocalizationImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		bannerContentLocalizationImpl.setBannerImage(
			this.<String>getColumnOriginalValue("bannerImage"));
		bannerContentLocalizationImpl.setImageOverlay(
			this.<String>getColumnOriginalValue("imageOverlay"));
		bannerContentLocalizationImpl.setLinkType(
			this.<String>getColumnOriginalValue("linkType"));
		bannerContentLocalizationImpl.setUrl(
			this.<String>getColumnOriginalValue("url"));
		bannerContentLocalizationImpl.setTitleValue(
			this.<String>getColumnOriginalValue("titleValue"));
		bannerContentLocalizationImpl.setDescriptionValue(
			this.<String>getColumnOriginalValue("descriptionValue"));

		return bannerContentLocalizationImpl;
	}

	@Override
	public int compareTo(BannerContentLocalization bannerContentLocalization) {
		long primaryKey = bannerContentLocalization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BannerContentLocalization)) {
			return false;
		}

		BannerContentLocalization bannerContentLocalization =
			(BannerContentLocalization)object;

		long primaryKey = bannerContentLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BannerContentLocalization> toCacheModel() {
		BannerContentLocalizationCacheModel
			bannerContentLocalizationCacheModel =
				new BannerContentLocalizationCacheModel();

		bannerContentLocalizationCacheModel.mvccVersion = getMvccVersion();

		bannerContentLocalizationCacheModel.bannerContentLocalizationId =
			getBannerContentLocalizationId();

		bannerContentLocalizationCacheModel.contentId = getContentId();

		bannerContentLocalizationCacheModel.languageId = getLanguageId();

		String languageId = bannerContentLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			bannerContentLocalizationCacheModel.languageId = null;
		}

		bannerContentLocalizationCacheModel.bannerImage = getBannerImage();

		String bannerImage = bannerContentLocalizationCacheModel.bannerImage;

		if ((bannerImage != null) && (bannerImage.length() == 0)) {
			bannerContentLocalizationCacheModel.bannerImage = null;
		}

		bannerContentLocalizationCacheModel.imageOverlay = getImageOverlay();

		String imageOverlay = bannerContentLocalizationCacheModel.imageOverlay;

		if ((imageOverlay != null) && (imageOverlay.length() == 0)) {
			bannerContentLocalizationCacheModel.imageOverlay = null;
		}

		bannerContentLocalizationCacheModel.linkType = getLinkType();

		String linkType = bannerContentLocalizationCacheModel.linkType;

		if ((linkType != null) && (linkType.length() == 0)) {
			bannerContentLocalizationCacheModel.linkType = null;
		}

		bannerContentLocalizationCacheModel.url = getUrl();

		String url = bannerContentLocalizationCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			bannerContentLocalizationCacheModel.url = null;
		}

		bannerContentLocalizationCacheModel.titleValue = getTitleValue();

		String titleValue = bannerContentLocalizationCacheModel.titleValue;

		if ((titleValue != null) && (titleValue.length() == 0)) {
			bannerContentLocalizationCacheModel.titleValue = null;
		}

		bannerContentLocalizationCacheModel.descriptionValue =
			getDescriptionValue();

		String descriptionValue =
			bannerContentLocalizationCacheModel.descriptionValue;

		if ((descriptionValue != null) && (descriptionValue.length() == 0)) {
			bannerContentLocalizationCacheModel.descriptionValue = null;
		}

		return bannerContentLocalizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BannerContentLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BannerContentLocalization, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BannerContentLocalization, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BannerContentLocalization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, BannerContentLocalization>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						BannerContentLocalization.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _bannerContentLocalizationId;
	private long _contentId;
	private String _languageId;
	private String _bannerImage;
	private String _imageOverlay;
	private String _linkType;
	private String _url;
	private String _titleValue;
	private String _descriptionValue;

	public <T> T getColumnValue(String columnName) {
		Function<BannerContentLocalization, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BannerContentLocalization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"bannerContentLocalizationId", _bannerContentLocalizationId);
		_columnOriginalValues.put("contentId", _contentId);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("bannerImage", _bannerImage);
		_columnOriginalValues.put("imageOverlay", _imageOverlay);
		_columnOriginalValues.put("linkType", _linkType);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("titleValue", _titleValue);
		_columnOriginalValues.put("descriptionValue", _descriptionValue);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("bannerContentLocalizationId", 2L);

		columnBitmasks.put("contentId", 4L);

		columnBitmasks.put("languageId", 8L);

		columnBitmasks.put("bannerImage", 16L);

		columnBitmasks.put("imageOverlay", 32L);

		columnBitmasks.put("linkType", 64L);

		columnBitmasks.put("url", 128L);

		columnBitmasks.put("titleValue", 256L);

		columnBitmasks.put("descriptionValue", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BannerContentLocalization _escapedModel;

}