/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.BannerContentLocalization;

/**
 * The extended model base implementation for the BannerContentLocalization service. Represents a row in the &quot;BannerContentLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerContentLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerContentLocalizationImpl
 * @see BannerContentLocalization
 * @generated
 */
public abstract class BannerContentLocalizationBaseImpl
	extends BannerContentLocalizationModelImpl
	implements BannerContentLocalization {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banner content localization model instance should use the <code>BannerContentLocalization</code> interface instead.
	 */

}