/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Banner;
import com.ejada.telemony.db.model.BannerModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Banner service. Represents a row in the &quot;BANNER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BannerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerImpl
 * @generated
 */
@JSON(strict = true)
public class BannerModelImpl
	extends BaseModelImpl<Banner> implements BannerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banner model instance should use the <code>Banner</code> interface instead.
	 */
	public static final String TABLE_NAME = "BANNER";

	public static final Object[][] TABLE_COLUMNS = {
		{"bannerId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"bannerName", Types.VARCHAR}, {"bannerType", Types.VARCHAR},
		{"container", Types.VARCHAR}, {"dateFrom", Types.TIMESTAMP},
		{"dateTo", Types.TIMESTAMP}, {"blockId", Types.BIGINT},
		{"persona", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"uuid_", Types.VARCHAR},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT},
		{"version", Types.INTEGER}, {"workflowAction", Types.VARCHAR},
		{"importRequestId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("bannerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bannerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bannerType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("container", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateTo", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("blockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("persona", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importRequestId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BANNER (bannerId LONG not null primary key,channelId LONG,bannerName VARCHAR(75) null,bannerType VARCHAR(75) null,container VARCHAR(75) null,dateFrom DATE null,dateTo DATE null,blockId LONG,persona VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null,importRequestId LONG)";

	public static final String TABLE_SQL_DROP = "drop table BANNER";

	public static final String ORDER_BY_JPQL = " ORDER BY banner.bannerId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY BANNER.bannerId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BANNERID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Banner"));

	public BannerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bannerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBannerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bannerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Banner.class;
	}

	@Override
	public String getModelClassName() {
		return Banner.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Banner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Banner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Banner, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Banner)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Banner, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Banner, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Banner)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Banner, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Banner, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Banner, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Banner, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Banner, Object>>();

			attributeGetterFunctions.put("bannerId", Banner::getBannerId);
			attributeGetterFunctions.put("channelId", Banner::getChannelId);
			attributeGetterFunctions.put("bannerName", Banner::getBannerName);
			attributeGetterFunctions.put("bannerType", Banner::getBannerType);
			attributeGetterFunctions.put("container", Banner::getContainer);
			attributeGetterFunctions.put("dateFrom", Banner::getDateFrom);
			attributeGetterFunctions.put("dateTo", Banner::getDateTo);
			attributeGetterFunctions.put("blockId", Banner::getBlockId);
			attributeGetterFunctions.put("persona", Banner::getPersona);
			attributeGetterFunctions.put("groupId", Banner::getGroupId);
			attributeGetterFunctions.put("companyId", Banner::getCompanyId);
			attributeGetterFunctions.put("userId", Banner::getUserId);
			attributeGetterFunctions.put("userName", Banner::getUserName);
			attributeGetterFunctions.put("createDate", Banner::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Banner::getModifiedDate);
			attributeGetterFunctions.put("status", Banner::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Banner::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Banner::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Banner::getStatusDate);
			attributeGetterFunctions.put("uuid_", Banner::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Banner::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Banner::getEntityResourceId);
			attributeGetterFunctions.put("version", Banner::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Banner::getWorkflowAction);
			attributeGetterFunctions.put(
				"importRequestId", Banner::getImportRequestId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Banner, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Banner, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Banner, ?>>();

			attributeSetterBiConsumers.put(
				"bannerId", (BiConsumer<Banner, Long>)Banner::setBannerId);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Banner, Long>)Banner::setChannelId);
			attributeSetterBiConsumers.put(
				"bannerName",
				(BiConsumer<Banner, String>)Banner::setBannerName);
			attributeSetterBiConsumers.put(
				"bannerType",
				(BiConsumer<Banner, String>)Banner::setBannerType);
			attributeSetterBiConsumers.put(
				"container", (BiConsumer<Banner, String>)Banner::setContainer);
			attributeSetterBiConsumers.put(
				"dateFrom", (BiConsumer<Banner, Date>)Banner::setDateFrom);
			attributeSetterBiConsumers.put(
				"dateTo", (BiConsumer<Banner, Date>)Banner::setDateTo);
			attributeSetterBiConsumers.put(
				"blockId", (BiConsumer<Banner, Long>)Banner::setBlockId);
			attributeSetterBiConsumers.put(
				"persona", (BiConsumer<Banner, String>)Banner::setPersona);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Banner, Long>)Banner::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Banner, Long>)Banner::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Banner, Long>)Banner::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Banner, String>)Banner::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Banner, Date>)Banner::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Banner, Date>)Banner::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Banner, Integer>)Banner::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Banner, Long>)Banner::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Banner, String>)Banner::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate", (BiConsumer<Banner, Date>)Banner::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Banner, String>)Banner::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Banner, Long>)Banner::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Banner, Long>)Banner::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Banner, Integer>)Banner::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Banner, String>)Banner::setWorkflowAction);
			attributeSetterBiConsumers.put(
				"importRequestId",
				(BiConsumer<Banner, Long>)Banner::setImportRequestId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getBannerId() {
		return _bannerId;
	}

	@Override
	public void setBannerId(long bannerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerId = bannerId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getBannerName() {
		if (_bannerName == null) {
			return "";
		}
		else {
			return _bannerName;
		}
	}

	@Override
	public void setBannerName(String bannerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerName = bannerName;
	}

	@JSON
	@Override
	public String getBannerType() {
		if (_bannerType == null) {
			return "";
		}
		else {
			return _bannerType;
		}
	}

	@Override
	public void setBannerType(String bannerType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bannerType = bannerType;
	}

	@JSON
	@Override
	public String getContainer() {
		if (_container == null) {
			return "";
		}
		else {
			return _container;
		}
	}

	@Override
	public void setContainer(String container) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_container = container;
	}

	@JSON
	@Override
	public Date getDateFrom() {
		return _dateFrom;
	}

	@Override
	public void setDateFrom(Date dateFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateFrom = dateFrom;
	}

	@JSON
	@Override
	public Date getDateTo() {
		return _dateTo;
	}

	@Override
	public void setDateTo(Date dateTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateTo = dateTo;
	}

	@JSON
	@Override
	public long getBlockId() {
		return _blockId;
	}

	@Override
	public void setBlockId(long blockId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blockId = blockId;
	}

	@JSON
	@Override
	public String getPersona() {
		if (_persona == null) {
			return "";
		}
		else {
			return _persona;
		}
	}

	@Override
	public void setPersona(String persona) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_persona = persona;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@JSON
	@Override
	public long getImportRequestId() {
		return _importRequestId;
	}

	@Override
	public void setImportRequestId(long importRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importRequestId = importRequestId;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Banner.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Banner toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Banner>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BannerImpl bannerImpl = new BannerImpl();

		bannerImpl.setBannerId(getBannerId());
		bannerImpl.setChannelId(getChannelId());
		bannerImpl.setBannerName(getBannerName());
		bannerImpl.setBannerType(getBannerType());
		bannerImpl.setContainer(getContainer());
		bannerImpl.setDateFrom(getDateFrom());
		bannerImpl.setDateTo(getDateTo());
		bannerImpl.setBlockId(getBlockId());
		bannerImpl.setPersona(getPersona());
		bannerImpl.setGroupId(getGroupId());
		bannerImpl.setCompanyId(getCompanyId());
		bannerImpl.setUserId(getUserId());
		bannerImpl.setUserName(getUserName());
		bannerImpl.setCreateDate(getCreateDate());
		bannerImpl.setModifiedDate(getModifiedDate());
		bannerImpl.setStatus(getStatus());
		bannerImpl.setStatusByUserId(getStatusByUserId());
		bannerImpl.setStatusByUserName(getStatusByUserName());
		bannerImpl.setStatusDate(getStatusDate());
		bannerImpl.setUuid_(getUuid_());
		bannerImpl.setOriginalEntityId(getOriginalEntityId());
		bannerImpl.setEntityResourceId(getEntityResourceId());
		bannerImpl.setVersion(getVersion());
		bannerImpl.setWorkflowAction(getWorkflowAction());
		bannerImpl.setImportRequestId(getImportRequestId());

		bannerImpl.resetOriginalValues();

		return bannerImpl;
	}

	@Override
	public Banner cloneWithOriginalValues() {
		BannerImpl bannerImpl = new BannerImpl();

		bannerImpl.setBannerId(this.<Long>getColumnOriginalValue("bannerId"));
		bannerImpl.setChannelId(this.<Long>getColumnOriginalValue("channelId"));
		bannerImpl.setBannerName(
			this.<String>getColumnOriginalValue("bannerName"));
		bannerImpl.setBannerType(
			this.<String>getColumnOriginalValue("bannerType"));
		bannerImpl.setContainer(
			this.<String>getColumnOriginalValue("container"));
		bannerImpl.setDateFrom(this.<Date>getColumnOriginalValue("dateFrom"));
		bannerImpl.setDateTo(this.<Date>getColumnOriginalValue("dateTo"));
		bannerImpl.setBlockId(this.<Long>getColumnOriginalValue("blockId"));
		bannerImpl.setPersona(this.<String>getColumnOriginalValue("persona"));
		bannerImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		bannerImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		bannerImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		bannerImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		bannerImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		bannerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		bannerImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		bannerImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		bannerImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		bannerImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		bannerImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		bannerImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		bannerImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		bannerImpl.setVersion(this.<Integer>getColumnOriginalValue("version"));
		bannerImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));
		bannerImpl.setImportRequestId(
			this.<Long>getColumnOriginalValue("importRequestId"));

		return bannerImpl;
	}

	@Override
	public int compareTo(Banner banner) {
		long primaryKey = banner.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Banner)) {
			return false;
		}

		Banner banner = (Banner)object;

		long primaryKey = banner.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Banner> toCacheModel() {
		BannerCacheModel bannerCacheModel = new BannerCacheModel();

		bannerCacheModel.bannerId = getBannerId();

		bannerCacheModel.channelId = getChannelId();

		bannerCacheModel.bannerName = getBannerName();

		String bannerName = bannerCacheModel.bannerName;

		if ((bannerName != null) && (bannerName.length() == 0)) {
			bannerCacheModel.bannerName = null;
		}

		bannerCacheModel.bannerType = getBannerType();

		String bannerType = bannerCacheModel.bannerType;

		if ((bannerType != null) && (bannerType.length() == 0)) {
			bannerCacheModel.bannerType = null;
		}

		bannerCacheModel.container = getContainer();

		String container = bannerCacheModel.container;

		if ((container != null) && (container.length() == 0)) {
			bannerCacheModel.container = null;
		}

		Date dateFrom = getDateFrom();

		if (dateFrom != null) {
			bannerCacheModel.dateFrom = dateFrom.getTime();
		}
		else {
			bannerCacheModel.dateFrom = Long.MIN_VALUE;
		}

		Date dateTo = getDateTo();

		if (dateTo != null) {
			bannerCacheModel.dateTo = dateTo.getTime();
		}
		else {
			bannerCacheModel.dateTo = Long.MIN_VALUE;
		}

		bannerCacheModel.blockId = getBlockId();

		bannerCacheModel.persona = getPersona();

		String persona = bannerCacheModel.persona;

		if ((persona != null) && (persona.length() == 0)) {
			bannerCacheModel.persona = null;
		}

		bannerCacheModel.groupId = getGroupId();

		bannerCacheModel.companyId = getCompanyId();

		bannerCacheModel.userId = getUserId();

		bannerCacheModel.userName = getUserName();

		String userName = bannerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bannerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bannerCacheModel.createDate = createDate.getTime();
		}
		else {
			bannerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bannerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bannerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bannerCacheModel.status = getStatus();

		bannerCacheModel.statusByUserId = getStatusByUserId();

		bannerCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = bannerCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			bannerCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			bannerCacheModel.statusDate = statusDate.getTime();
		}
		else {
			bannerCacheModel.statusDate = Long.MIN_VALUE;
		}

		bannerCacheModel.uuid_ = getUuid_();

		String uuid_ = bannerCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			bannerCacheModel.uuid_ = null;
		}

		bannerCacheModel.originalEntityId = getOriginalEntityId();

		bannerCacheModel.entityResourceId = getEntityResourceId();

		bannerCacheModel.version = getVersion();

		bannerCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = bannerCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			bannerCacheModel.workflowAction = null;
		}

		bannerCacheModel.importRequestId = getImportRequestId();

		return bannerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Banner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Banner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Banner, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Banner)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Banner>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Banner.class, ModelWrapper.class);

	}

	private long _bannerId;
	private long _channelId;
	private String _bannerName;
	private String _bannerType;
	private String _container;
	private Date _dateFrom;
	private Date _dateTo;
	private long _blockId;
	private String _persona;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;
	private long _importRequestId;

	public <T> T getColumnValue(String columnName) {
		Function<Banner, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Banner)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("bannerId", _bannerId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("bannerName", _bannerName);
		_columnOriginalValues.put("bannerType", _bannerType);
		_columnOriginalValues.put("container", _container);
		_columnOriginalValues.put("dateFrom", _dateFrom);
		_columnOriginalValues.put("dateTo", _dateTo);
		_columnOriginalValues.put("blockId", _blockId);
		_columnOriginalValues.put("persona", _persona);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
		_columnOriginalValues.put("importRequestId", _importRequestId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("bannerId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("bannerName", 4L);

		columnBitmasks.put("bannerType", 8L);

		columnBitmasks.put("container", 16L);

		columnBitmasks.put("dateFrom", 32L);

		columnBitmasks.put("dateTo", 64L);

		columnBitmasks.put("blockId", 128L);

		columnBitmasks.put("persona", 256L);

		columnBitmasks.put("groupId", 512L);

		columnBitmasks.put("companyId", 1024L);

		columnBitmasks.put("userId", 2048L);

		columnBitmasks.put("userName", 4096L);

		columnBitmasks.put("createDate", 8192L);

		columnBitmasks.put("modifiedDate", 16384L);

		columnBitmasks.put("status", 32768L);

		columnBitmasks.put("statusByUserId", 65536L);

		columnBitmasks.put("statusByUserName", 131072L);

		columnBitmasks.put("statusDate", 262144L);

		columnBitmasks.put("uuid_", 524288L);

		columnBitmasks.put("originalEntityId", 1048576L);

		columnBitmasks.put("entityResourceId", 2097152L);

		columnBitmasks.put("version", 4194304L);

		columnBitmasks.put("workflowAction", 8388608L);

		columnBitmasks.put("importRequestId", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Banner _escapedModel;

}