/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Blocks;
import com.ejada.telemony.db.model.BlocksModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Blocks service. Represents a row in the &quot;BLOCKS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BlocksModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlocksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlocksImpl
 * @generated
 */
public class BlocksModelImpl
	extends BaseModelImpl<Blocks> implements BlocksModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blocks model instance should use the <code>Blocks</code> interface instead.
	 */
	public static final String TABLE_NAME = "BLOCKS";

	public static final Object[][] TABLE_COLUMNS = {
		{"blockId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"type", Types.VARCHAR}, {"androidBlock", Types.BOOLEAN},
		{"androidBlockVersion", Types.VARCHAR},
		{"androidBlockFrom", Types.TIMESTAMP},
		{"androidBlockTo", Types.TIMESTAMP}, {"iosBlock", Types.BOOLEAN},
		{"iosBlockVersion", Types.VARCHAR}, {"iosBlockFrom", Types.TIMESTAMP},
		{"iosBlockTo", Types.TIMESTAMP}, {"webBlock", Types.BOOLEAN},
		{"webBlockVersion", Types.VARCHAR}, {"webBlockFrom", Types.TIMESTAMP},
		{"webBlockTo", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("blockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("androidBlock", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("androidBlockVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("androidBlockFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("androidBlockTo", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("iosBlock", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("iosBlockVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("iosBlockFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("iosBlockTo", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("webBlock", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("webBlockVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("webBlockFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("webBlockTo", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BLOCKS (blockId LONG not null primary key,channelId LONG,type VARCHAR(75) null,androidBlock BOOLEAN,androidBlockVersion VARCHAR(75) null,androidBlockFrom DATE null,androidBlockTo DATE null,iosBlock BOOLEAN,iosBlockVersion VARCHAR(75) null,iosBlockFrom DATE null,iosBlockTo DATE null,webBlock BOOLEAN,webBlockVersion VARCHAR(75) null,webBlockFrom DATE null,webBlockTo DATE null)";

	public static final String TABLE_SQL_DROP = "drop table BLOCKS";

	public static final String ORDER_BY_JPQL = " ORDER BY blocks.blockId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY BLOCKS.blockId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BLOCKID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Blocks"));

	public BlocksModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _blockId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBlockId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _blockId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Blocks.class;
	}

	@Override
	public String getModelClassName() {
		return Blocks.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Blocks, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Blocks, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Blocks, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Blocks)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Blocks, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Blocks, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Blocks)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Blocks, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Blocks, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Blocks, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Blocks, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Blocks, Object>>();

			attributeGetterFunctions.put("blockId", Blocks::getBlockId);
			attributeGetterFunctions.put("channelId", Blocks::getChannelId);
			attributeGetterFunctions.put("type", Blocks::getType);
			attributeGetterFunctions.put(
				"androidBlock", Blocks::getAndroidBlock);
			attributeGetterFunctions.put(
				"androidBlockVersion", Blocks::getAndroidBlockVersion);
			attributeGetterFunctions.put(
				"androidBlockFrom", Blocks::getAndroidBlockFrom);
			attributeGetterFunctions.put(
				"androidBlockTo", Blocks::getAndroidBlockTo);
			attributeGetterFunctions.put("iosBlock", Blocks::getIosBlock);
			attributeGetterFunctions.put(
				"iosBlockVersion", Blocks::getIosBlockVersion);
			attributeGetterFunctions.put(
				"iosBlockFrom", Blocks::getIosBlockFrom);
			attributeGetterFunctions.put("iosBlockTo", Blocks::getIosBlockTo);
			attributeGetterFunctions.put("webBlock", Blocks::getWebBlock);
			attributeGetterFunctions.put(
				"webBlockVersion", Blocks::getWebBlockVersion);
			attributeGetterFunctions.put(
				"webBlockFrom", Blocks::getWebBlockFrom);
			attributeGetterFunctions.put("webBlockTo", Blocks::getWebBlockTo);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Blocks, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Blocks, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Blocks, ?>>();

			attributeSetterBiConsumers.put(
				"blockId", (BiConsumer<Blocks, Long>)Blocks::setBlockId);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Blocks, Long>)Blocks::setChannelId);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<Blocks, String>)Blocks::setType);
			attributeSetterBiConsumers.put(
				"androidBlock",
				(BiConsumer<Blocks, Boolean>)Blocks::setAndroidBlock);
			attributeSetterBiConsumers.put(
				"androidBlockVersion",
				(BiConsumer<Blocks, String>)Blocks::setAndroidBlockVersion);
			attributeSetterBiConsumers.put(
				"androidBlockFrom",
				(BiConsumer<Blocks, Date>)Blocks::setAndroidBlockFrom);
			attributeSetterBiConsumers.put(
				"androidBlockTo",
				(BiConsumer<Blocks, Date>)Blocks::setAndroidBlockTo);
			attributeSetterBiConsumers.put(
				"iosBlock", (BiConsumer<Blocks, Boolean>)Blocks::setIosBlock);
			attributeSetterBiConsumers.put(
				"iosBlockVersion",
				(BiConsumer<Blocks, String>)Blocks::setIosBlockVersion);
			attributeSetterBiConsumers.put(
				"iosBlockFrom",
				(BiConsumer<Blocks, Date>)Blocks::setIosBlockFrom);
			attributeSetterBiConsumers.put(
				"iosBlockTo", (BiConsumer<Blocks, Date>)Blocks::setIosBlockTo);
			attributeSetterBiConsumers.put(
				"webBlock", (BiConsumer<Blocks, Boolean>)Blocks::setWebBlock);
			attributeSetterBiConsumers.put(
				"webBlockVersion",
				(BiConsumer<Blocks, String>)Blocks::setWebBlockVersion);
			attributeSetterBiConsumers.put(
				"webBlockFrom",
				(BiConsumer<Blocks, Date>)Blocks::setWebBlockFrom);
			attributeSetterBiConsumers.put(
				"webBlockTo", (BiConsumer<Blocks, Date>)Blocks::setWebBlockTo);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getBlockId() {
		return _blockId;
	}

	@Override
	public void setBlockId(long blockId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blockId = blockId;
	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public boolean getAndroidBlock() {
		return _androidBlock;
	}

	@Override
	public boolean isAndroidBlock() {
		return _androidBlock;
	}

	@Override
	public void setAndroidBlock(boolean androidBlock) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_androidBlock = androidBlock;
	}

	@Override
	public String getAndroidBlockVersion() {
		if (_androidBlockVersion == null) {
			return "";
		}
		else {
			return _androidBlockVersion;
		}
	}

	@Override
	public void setAndroidBlockVersion(String androidBlockVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_androidBlockVersion = androidBlockVersion;
	}

	@Override
	public Date getAndroidBlockFrom() {
		return _androidBlockFrom;
	}

	@Override
	public void setAndroidBlockFrom(Date androidBlockFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_androidBlockFrom = androidBlockFrom;
	}

	@Override
	public Date getAndroidBlockTo() {
		return _androidBlockTo;
	}

	@Override
	public void setAndroidBlockTo(Date androidBlockTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_androidBlockTo = androidBlockTo;
	}

	@Override
	public boolean getIosBlock() {
		return _iosBlock;
	}

	@Override
	public boolean isIosBlock() {
		return _iosBlock;
	}

	@Override
	public void setIosBlock(boolean iosBlock) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iosBlock = iosBlock;
	}

	@Override
	public String getIosBlockVersion() {
		if (_iosBlockVersion == null) {
			return "";
		}
		else {
			return _iosBlockVersion;
		}
	}

	@Override
	public void setIosBlockVersion(String iosBlockVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iosBlockVersion = iosBlockVersion;
	}

	@Override
	public Date getIosBlockFrom() {
		return _iosBlockFrom;
	}

	@Override
	public void setIosBlockFrom(Date iosBlockFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iosBlockFrom = iosBlockFrom;
	}

	@Override
	public Date getIosBlockTo() {
		return _iosBlockTo;
	}

	@Override
	public void setIosBlockTo(Date iosBlockTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iosBlockTo = iosBlockTo;
	}

	@Override
	public boolean getWebBlock() {
		return _webBlock;
	}

	@Override
	public boolean isWebBlock() {
		return _webBlock;
	}

	@Override
	public void setWebBlock(boolean webBlock) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webBlock = webBlock;
	}

	@Override
	public String getWebBlockVersion() {
		if (_webBlockVersion == null) {
			return "";
		}
		else {
			return _webBlockVersion;
		}
	}

	@Override
	public void setWebBlockVersion(String webBlockVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webBlockVersion = webBlockVersion;
	}

	@Override
	public Date getWebBlockFrom() {
		return _webBlockFrom;
	}

	@Override
	public void setWebBlockFrom(Date webBlockFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webBlockFrom = webBlockFrom;
	}

	@Override
	public Date getWebBlockTo() {
		return _webBlockTo;
	}

	@Override
	public void setWebBlockTo(Date webBlockTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webBlockTo = webBlockTo;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Blocks.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Blocks toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Blocks>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BlocksImpl blocksImpl = new BlocksImpl();

		blocksImpl.setBlockId(getBlockId());
		blocksImpl.setChannelId(getChannelId());
		blocksImpl.setType(getType());
		blocksImpl.setAndroidBlock(isAndroidBlock());
		blocksImpl.setAndroidBlockVersion(getAndroidBlockVersion());
		blocksImpl.setAndroidBlockFrom(getAndroidBlockFrom());
		blocksImpl.setAndroidBlockTo(getAndroidBlockTo());
		blocksImpl.setIosBlock(isIosBlock());
		blocksImpl.setIosBlockVersion(getIosBlockVersion());
		blocksImpl.setIosBlockFrom(getIosBlockFrom());
		blocksImpl.setIosBlockTo(getIosBlockTo());
		blocksImpl.setWebBlock(isWebBlock());
		blocksImpl.setWebBlockVersion(getWebBlockVersion());
		blocksImpl.setWebBlockFrom(getWebBlockFrom());
		blocksImpl.setWebBlockTo(getWebBlockTo());

		blocksImpl.resetOriginalValues();

		return blocksImpl;
	}

	@Override
	public Blocks cloneWithOriginalValues() {
		BlocksImpl blocksImpl = new BlocksImpl();

		blocksImpl.setBlockId(this.<Long>getColumnOriginalValue("blockId"));
		blocksImpl.setChannelId(this.<Long>getColumnOriginalValue("channelId"));
		blocksImpl.setType(this.<String>getColumnOriginalValue("type"));
		blocksImpl.setAndroidBlock(
			this.<Boolean>getColumnOriginalValue("androidBlock"));
		blocksImpl.setAndroidBlockVersion(
			this.<String>getColumnOriginalValue("androidBlockVersion"));
		blocksImpl.setAndroidBlockFrom(
			this.<Date>getColumnOriginalValue("androidBlockFrom"));
		blocksImpl.setAndroidBlockTo(
			this.<Date>getColumnOriginalValue("androidBlockTo"));
		blocksImpl.setIosBlock(
			this.<Boolean>getColumnOriginalValue("iosBlock"));
		blocksImpl.setIosBlockVersion(
			this.<String>getColumnOriginalValue("iosBlockVersion"));
		blocksImpl.setIosBlockFrom(
			this.<Date>getColumnOriginalValue("iosBlockFrom"));
		blocksImpl.setIosBlockTo(
			this.<Date>getColumnOriginalValue("iosBlockTo"));
		blocksImpl.setWebBlock(
			this.<Boolean>getColumnOriginalValue("webBlock"));
		blocksImpl.setWebBlockVersion(
			this.<String>getColumnOriginalValue("webBlockVersion"));
		blocksImpl.setWebBlockFrom(
			this.<Date>getColumnOriginalValue("webBlockFrom"));
		blocksImpl.setWebBlockTo(
			this.<Date>getColumnOriginalValue("webBlockTo"));

		return blocksImpl;
	}

	@Override
	public int compareTo(Blocks blocks) {
		long primaryKey = blocks.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Blocks)) {
			return false;
		}

		Blocks blocks = (Blocks)object;

		long primaryKey = blocks.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Blocks> toCacheModel() {
		BlocksCacheModel blocksCacheModel = new BlocksCacheModel();

		blocksCacheModel.blockId = getBlockId();

		blocksCacheModel.channelId = getChannelId();

		blocksCacheModel.type = getType();

		String type = blocksCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			blocksCacheModel.type = null;
		}

		blocksCacheModel.androidBlock = isAndroidBlock();

		blocksCacheModel.androidBlockVersion = getAndroidBlockVersion();

		String androidBlockVersion = blocksCacheModel.androidBlockVersion;

		if ((androidBlockVersion != null) &&
			(androidBlockVersion.length() == 0)) {

			blocksCacheModel.androidBlockVersion = null;
		}

		Date androidBlockFrom = getAndroidBlockFrom();

		if (androidBlockFrom != null) {
			blocksCacheModel.androidBlockFrom = androidBlockFrom.getTime();
		}
		else {
			blocksCacheModel.androidBlockFrom = Long.MIN_VALUE;
		}

		Date androidBlockTo = getAndroidBlockTo();

		if (androidBlockTo != null) {
			blocksCacheModel.androidBlockTo = androidBlockTo.getTime();
		}
		else {
			blocksCacheModel.androidBlockTo = Long.MIN_VALUE;
		}

		blocksCacheModel.iosBlock = isIosBlock();

		blocksCacheModel.iosBlockVersion = getIosBlockVersion();

		String iosBlockVersion = blocksCacheModel.iosBlockVersion;

		if ((iosBlockVersion != null) && (iosBlockVersion.length() == 0)) {
			blocksCacheModel.iosBlockVersion = null;
		}

		Date iosBlockFrom = getIosBlockFrom();

		if (iosBlockFrom != null) {
			blocksCacheModel.iosBlockFrom = iosBlockFrom.getTime();
		}
		else {
			blocksCacheModel.iosBlockFrom = Long.MIN_VALUE;
		}

		Date iosBlockTo = getIosBlockTo();

		if (iosBlockTo != null) {
			blocksCacheModel.iosBlockTo = iosBlockTo.getTime();
		}
		else {
			blocksCacheModel.iosBlockTo = Long.MIN_VALUE;
		}

		blocksCacheModel.webBlock = isWebBlock();

		blocksCacheModel.webBlockVersion = getWebBlockVersion();

		String webBlockVersion = blocksCacheModel.webBlockVersion;

		if ((webBlockVersion != null) && (webBlockVersion.length() == 0)) {
			blocksCacheModel.webBlockVersion = null;
		}

		Date webBlockFrom = getWebBlockFrom();

		if (webBlockFrom != null) {
			blocksCacheModel.webBlockFrom = webBlockFrom.getTime();
		}
		else {
			blocksCacheModel.webBlockFrom = Long.MIN_VALUE;
		}

		Date webBlockTo = getWebBlockTo();

		if (webBlockTo != null) {
			blocksCacheModel.webBlockTo = webBlockTo.getTime();
		}
		else {
			blocksCacheModel.webBlockTo = Long.MIN_VALUE;
		}

		return blocksCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Blocks, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Blocks, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Blocks, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Blocks)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Blocks>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Blocks.class, ModelWrapper.class);

	}

	private long _blockId;
	private long _channelId;
	private String _type;
	private boolean _androidBlock;
	private String _androidBlockVersion;
	private Date _androidBlockFrom;
	private Date _androidBlockTo;
	private boolean _iosBlock;
	private String _iosBlockVersion;
	private Date _iosBlockFrom;
	private Date _iosBlockTo;
	private boolean _webBlock;
	private String _webBlockVersion;
	private Date _webBlockFrom;
	private Date _webBlockTo;

	public <T> T getColumnValue(String columnName) {
		Function<Blocks, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Blocks)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("blockId", _blockId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("type", _type);
		_columnOriginalValues.put("androidBlock", _androidBlock);
		_columnOriginalValues.put("androidBlockVersion", _androidBlockVersion);
		_columnOriginalValues.put("androidBlockFrom", _androidBlockFrom);
		_columnOriginalValues.put("androidBlockTo", _androidBlockTo);
		_columnOriginalValues.put("iosBlock", _iosBlock);
		_columnOriginalValues.put("iosBlockVersion", _iosBlockVersion);
		_columnOriginalValues.put("iosBlockFrom", _iosBlockFrom);
		_columnOriginalValues.put("iosBlockTo", _iosBlockTo);
		_columnOriginalValues.put("webBlock", _webBlock);
		_columnOriginalValues.put("webBlockVersion", _webBlockVersion);
		_columnOriginalValues.put("webBlockFrom", _webBlockFrom);
		_columnOriginalValues.put("webBlockTo", _webBlockTo);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("blockId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("type", 4L);

		columnBitmasks.put("androidBlock", 8L);

		columnBitmasks.put("androidBlockVersion", 16L);

		columnBitmasks.put("androidBlockFrom", 32L);

		columnBitmasks.put("androidBlockTo", 64L);

		columnBitmasks.put("iosBlock", 128L);

		columnBitmasks.put("iosBlockVersion", 256L);

		columnBitmasks.put("iosBlockFrom", 512L);

		columnBitmasks.put("iosBlockTo", 1024L);

		columnBitmasks.put("webBlock", 2048L);

		columnBitmasks.put("webBlockVersion", 4096L);

		columnBitmasks.put("webBlockFrom", 8192L);

		columnBitmasks.put("webBlockTo", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Blocks _escapedModel;

}