/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Channels;
import com.ejada.telemony.db.model.ChannelsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Channels service. Represents a row in the &quot;CHANNELS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChannelsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChannelsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChannelsImpl
 * @generated
 */
public class ChannelsModelImpl
	extends BaseModelImpl<Channels> implements ChannelsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a channels model instance should use the <code>Channels</code> interface instead.
	 */
	public static final String TABLE_NAME = "CHANNELS";

	public static final Object[][] TABLE_COLUMNS = {
		{"channelId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"type", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CHANNELS (channelId LONG not null primary key,name VARCHAR(75) null,type VARCHAR(75) null,description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table CHANNELS";

	public static final String ORDER_BY_JPQL =
		" ORDER BY channels.channelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CHANNELS.channelId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Channels"));

	public ChannelsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _channelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChannelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _channelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Channels.class;
	}

	@Override
	public String getModelClassName() {
		return Channels.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Channels, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Channels, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Channels, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Channels)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Channels, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Channels, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Channels)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Channels, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Channels, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Channels, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Channels, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Channels, Object>>();

			attributeGetterFunctions.put("channelId", Channels::getChannelId);
			attributeGetterFunctions.put("name", Channels::getName);
			attributeGetterFunctions.put("type", Channels::getType);
			attributeGetterFunctions.put(
				"description", Channels::getDescription);
			attributeGetterFunctions.put("groupId", Channels::getGroupId);
			attributeGetterFunctions.put("companyId", Channels::getCompanyId);
			attributeGetterFunctions.put("userId", Channels::getUserId);
			attributeGetterFunctions.put("userName", Channels::getUserName);
			attributeGetterFunctions.put("createDate", Channels::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Channels::getModifiedDate);
			attributeGetterFunctions.put("status", Channels::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Channels::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Channels::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Channels::getStatusDate);
			attributeGetterFunctions.put("uuid_", Channels::getUuid_);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Channels, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Channels, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Channels, ?>>();

			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<Channels, Long>)Channels::setChannelId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Channels, String>)Channels::setName);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<Channels, String>)Channels::setType);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<Channels, String>)Channels::setDescription);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Channels, Long>)Channels::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Channels, Long>)Channels::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Channels, Long>)Channels::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Channels, String>)Channels::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Channels, Date>)Channels::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Channels, Date>)Channels::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Channels, Integer>)Channels::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Channels, Long>)Channels::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Channels, String>)Channels::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Channels, Date>)Channels::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Channels, String>)Channels::setUuid_);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Channels.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Channels toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Channels>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChannelsImpl channelsImpl = new ChannelsImpl();

		channelsImpl.setChannelId(getChannelId());
		channelsImpl.setName(getName());
		channelsImpl.setType(getType());
		channelsImpl.setDescription(getDescription());
		channelsImpl.setGroupId(getGroupId());
		channelsImpl.setCompanyId(getCompanyId());
		channelsImpl.setUserId(getUserId());
		channelsImpl.setUserName(getUserName());
		channelsImpl.setCreateDate(getCreateDate());
		channelsImpl.setModifiedDate(getModifiedDate());
		channelsImpl.setStatus(getStatus());
		channelsImpl.setStatusByUserId(getStatusByUserId());
		channelsImpl.setStatusByUserName(getStatusByUserName());
		channelsImpl.setStatusDate(getStatusDate());
		channelsImpl.setUuid_(getUuid_());

		channelsImpl.resetOriginalValues();

		return channelsImpl;
	}

	@Override
	public Channels cloneWithOriginalValues() {
		ChannelsImpl channelsImpl = new ChannelsImpl();

		channelsImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		channelsImpl.setName(this.<String>getColumnOriginalValue("name"));
		channelsImpl.setType(this.<String>getColumnOriginalValue("type"));
		channelsImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		channelsImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		channelsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		channelsImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		channelsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		channelsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		channelsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		channelsImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		channelsImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		channelsImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		channelsImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		channelsImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));

		return channelsImpl;
	}

	@Override
	public int compareTo(Channels channels) {
		long primaryKey = channels.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Channels)) {
			return false;
		}

		Channels channels = (Channels)object;

		long primaryKey = channels.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Channels> toCacheModel() {
		ChannelsCacheModel channelsCacheModel = new ChannelsCacheModel();

		channelsCacheModel.channelId = getChannelId();

		channelsCacheModel.name = getName();

		String name = channelsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			channelsCacheModel.name = null;
		}

		channelsCacheModel.type = getType();

		String type = channelsCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			channelsCacheModel.type = null;
		}

		channelsCacheModel.description = getDescription();

		String description = channelsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			channelsCacheModel.description = null;
		}

		channelsCacheModel.groupId = getGroupId();

		channelsCacheModel.companyId = getCompanyId();

		channelsCacheModel.userId = getUserId();

		channelsCacheModel.userName = getUserName();

		String userName = channelsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			channelsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			channelsCacheModel.createDate = createDate.getTime();
		}
		else {
			channelsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			channelsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			channelsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		channelsCacheModel.status = getStatus();

		channelsCacheModel.statusByUserId = getStatusByUserId();

		channelsCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = channelsCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			channelsCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			channelsCacheModel.statusDate = statusDate.getTime();
		}
		else {
			channelsCacheModel.statusDate = Long.MIN_VALUE;
		}

		channelsCacheModel.uuid_ = getUuid_();

		String uuid_ = channelsCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			channelsCacheModel.uuid_ = null;
		}

		return channelsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Channels, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Channels, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Channels, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Channels)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Channels>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Channels.class, ModelWrapper.class);

	}

	private long _channelId;
	private String _name;
	private String _type;
	private String _description;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;

	public <T> T getColumnValue(String columnName) {
		Function<Channels, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Channels)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("type", _type);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("channelId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("type", 4L);

		columnBitmasks.put("description", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("status", 1024L);

		columnBitmasks.put("statusByUserId", 2048L);

		columnBitmasks.put("statusByUserName", 4096L);

		columnBitmasks.put("statusDate", 8192L);

		columnBitmasks.put("uuid_", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Channels _escapedModel;

}