/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Channels;
import com.ejada.telemony.db.service.ChannelsLocalServiceUtil;

/**
 * The extended model base implementation for the Channels service. Represents a row in the &quot;CHANNELS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChannelsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChannelsImpl
 * @see Channels
 * @generated
 */
public abstract class ChannelsBaseImpl
	extends ChannelsModelImpl implements Channels {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a channels model instance should use the <code>Channels</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ChannelsLocalServiceUtil.addChannels(this);
		}
		else {
			ChannelsLocalServiceUtil.updateChannels(this);
		}
	}

}