/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.ConfigurationEntity;
import com.ejada.telemony.db.service.ConfigurationEntityLocalServiceUtil;

/**
 * The extended model base implementation for the ConfigurationEntity service. Represents a row in the &quot;ConfigurationEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfigurationEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConfigurationEntityImpl
 * @see ConfigurationEntity
 * @generated
 */
public abstract class ConfigurationEntityBaseImpl
	extends ConfigurationEntityModelImpl implements ConfigurationEntity {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a configuration entity model instance should use the <code>ConfigurationEntity</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ConfigurationEntityLocalServiceUtil.addConfigurationEntity(this);
		}
		else {
			ConfigurationEntityLocalServiceUtil.updateConfigurationEntity(this);
		}
	}

}