/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.ConfigurationEntity;
import com.ejada.telemony.db.model.ConfigurationEntityModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ConfigurationEntity service. Represents a row in the &quot;ConfigurationEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConfigurationEntityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfigurationEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConfigurationEntityImpl
 * @generated
 */
@JSON(strict = true)
public class ConfigurationEntityModelImpl
	extends BaseModelImpl<ConfigurationEntity>
	implements ConfigurationEntityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a configuration entity model instance should use the <code>ConfigurationEntity</code> interface instead.
	 */
	public static final String TABLE_NAME = "ConfigurationEntity";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"url", Types.VARCHAR},
		{"oldData", Types.VARCHAR}, {"newData", Types.VARCHAR},
		{"entityType", Types.VARCHAR}, {"entityId", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oldData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("newData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ConfigurationEntity (id LONG not null primary key,url VARCHAR(75) null,oldData VARCHAR(75) null,newData VARCHAR(75) null,entityType VARCHAR(75) null,entityId VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ConfigurationEntity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY configurationEntity.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ConfigurationEntity.id ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYTYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.ConfigurationEntity"));

	public ConfigurationEntityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConfigurationEntity.class;
	}

	@Override
	public String getModelClassName() {
		return ConfigurationEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConfigurationEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConfigurationEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConfigurationEntity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConfigurationEntity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConfigurationEntity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConfigurationEntity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConfigurationEntity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConfigurationEntity, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConfigurationEntity, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ConfigurationEntity, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ConfigurationEntity, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ConfigurationEntity, Object>>();

			attributeGetterFunctions.put("id", ConfigurationEntity::getId);
			attributeGetterFunctions.put("url", ConfigurationEntity::getUrl);
			attributeGetterFunctions.put(
				"oldData", ConfigurationEntity::getOldData);
			attributeGetterFunctions.put(
				"newData", ConfigurationEntity::getNewData);
			attributeGetterFunctions.put(
				"entityType", ConfigurationEntity::getEntityType);
			attributeGetterFunctions.put(
				"entityId", ConfigurationEntity::getEntityId);
			attributeGetterFunctions.put(
				"groupId", ConfigurationEntity::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ConfigurationEntity::getCompanyId);
			attributeGetterFunctions.put(
				"userId", ConfigurationEntity::getUserId);
			attributeGetterFunctions.put(
				"userName", ConfigurationEntity::getUserName);
			attributeGetterFunctions.put(
				"createDate", ConfigurationEntity::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ConfigurationEntity::getModifiedDate);
			attributeGetterFunctions.put(
				"status", ConfigurationEntity::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", ConfigurationEntity::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", ConfigurationEntity::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", ConfigurationEntity::getStatusDate);
			attributeGetterFunctions.put(
				"uuid_", ConfigurationEntity::getUuid_);
			attributeGetterFunctions.put(
				"workflowAction", ConfigurationEntity::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ConfigurationEntity, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ConfigurationEntity, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ConfigurationEntity, ?>>();

			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<ConfigurationEntity, Long>)
					ConfigurationEntity::setId);
			attributeSetterBiConsumers.put(
				"url",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setUrl);
			attributeSetterBiConsumers.put(
				"oldData",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setOldData);
			attributeSetterBiConsumers.put(
				"newData",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setNewData);
			attributeSetterBiConsumers.put(
				"entityType",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setEntityType);
			attributeSetterBiConsumers.put(
				"entityId",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setEntityId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ConfigurationEntity, Long>)
					ConfigurationEntity::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ConfigurationEntity, Long>)
					ConfigurationEntity::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ConfigurationEntity, Long>)
					ConfigurationEntity::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ConfigurationEntity, Date>)
					ConfigurationEntity::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ConfigurationEntity, Date>)
					ConfigurationEntity::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<ConfigurationEntity, Integer>)
					ConfigurationEntity::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<ConfigurationEntity, Long>)
					ConfigurationEntity::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<ConfigurationEntity, Date>)
					ConfigurationEntity::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setUuid_);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<ConfigurationEntity, String>)
					ConfigurationEntity::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public String getOldData() {
		if (_oldData == null) {
			return "";
		}
		else {
			return _oldData;
		}
	}

	@Override
	public void setOldData(String oldData) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oldData = oldData;
	}

	@JSON
	@Override
	public String getNewData() {
		if (_newData == null) {
			return "";
		}
		else {
			return _newData;
		}
	}

	@Override
	public void setNewData(String newData) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newData = newData;
	}

	@JSON
	@Override
	public String getEntityType() {
		if (_entityType == null) {
			return "";
		}
		else {
			return _entityType;
		}
	}

	@Override
	public void setEntityType(String entityType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityType = entityType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEntityType() {
		return getColumnOriginalValue("entityType");
	}

	@JSON
	@Override
	public String getEntityId() {
		if (_entityId == null) {
			return "";
		}
		else {
			return _entityId;
		}
	}

	@Override
	public void setEntityId(String entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEntityId() {
		return getColumnOriginalValue("entityId");
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ConfigurationEntity.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConfigurationEntity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ConfigurationEntity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConfigurationEntityImpl configurationEntityImpl =
			new ConfigurationEntityImpl();

		configurationEntityImpl.setId(getId());
		configurationEntityImpl.setUrl(getUrl());
		configurationEntityImpl.setOldData(getOldData());
		configurationEntityImpl.setNewData(getNewData());
		configurationEntityImpl.setEntityType(getEntityType());
		configurationEntityImpl.setEntityId(getEntityId());
		configurationEntityImpl.setGroupId(getGroupId());
		configurationEntityImpl.setCompanyId(getCompanyId());
		configurationEntityImpl.setUserId(getUserId());
		configurationEntityImpl.setUserName(getUserName());
		configurationEntityImpl.setCreateDate(getCreateDate());
		configurationEntityImpl.setModifiedDate(getModifiedDate());
		configurationEntityImpl.setStatus(getStatus());
		configurationEntityImpl.setStatusByUserId(getStatusByUserId());
		configurationEntityImpl.setStatusByUserName(getStatusByUserName());
		configurationEntityImpl.setStatusDate(getStatusDate());
		configurationEntityImpl.setUuid_(getUuid_());
		configurationEntityImpl.setWorkflowAction(getWorkflowAction());

		configurationEntityImpl.resetOriginalValues();

		return configurationEntityImpl;
	}

	@Override
	public ConfigurationEntity cloneWithOriginalValues() {
		ConfigurationEntityImpl configurationEntityImpl =
			new ConfigurationEntityImpl();

		configurationEntityImpl.setId(this.<Long>getColumnOriginalValue("id"));
		configurationEntityImpl.setUrl(
			this.<String>getColumnOriginalValue("url"));
		configurationEntityImpl.setOldData(
			this.<String>getColumnOriginalValue("oldData"));
		configurationEntityImpl.setNewData(
			this.<String>getColumnOriginalValue("newData"));
		configurationEntityImpl.setEntityType(
			this.<String>getColumnOriginalValue("entityType"));
		configurationEntityImpl.setEntityId(
			this.<String>getColumnOriginalValue("entityId"));
		configurationEntityImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		configurationEntityImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		configurationEntityImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		configurationEntityImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		configurationEntityImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		configurationEntityImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		configurationEntityImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		configurationEntityImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		configurationEntityImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		configurationEntityImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		configurationEntityImpl.setUuid_(
			this.<String>getColumnOriginalValue("uuid_"));
		configurationEntityImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return configurationEntityImpl;
	}

	@Override
	public int compareTo(ConfigurationEntity configurationEntity) {
		long primaryKey = configurationEntity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ConfigurationEntity)) {
			return false;
		}

		ConfigurationEntity configurationEntity = (ConfigurationEntity)object;

		long primaryKey = configurationEntity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ConfigurationEntity> toCacheModel() {
		ConfigurationEntityCacheModel configurationEntityCacheModel =
			new ConfigurationEntityCacheModel();

		configurationEntityCacheModel.id = getId();

		configurationEntityCacheModel.url = getUrl();

		String url = configurationEntityCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			configurationEntityCacheModel.url = null;
		}

		configurationEntityCacheModel.oldData = getOldData();

		String oldData = configurationEntityCacheModel.oldData;

		if ((oldData != null) && (oldData.length() == 0)) {
			configurationEntityCacheModel.oldData = null;
		}

		configurationEntityCacheModel.newData = getNewData();

		String newData = configurationEntityCacheModel.newData;

		if ((newData != null) && (newData.length() == 0)) {
			configurationEntityCacheModel.newData = null;
		}

		configurationEntityCacheModel.entityType = getEntityType();

		String entityType = configurationEntityCacheModel.entityType;

		if ((entityType != null) && (entityType.length() == 0)) {
			configurationEntityCacheModel.entityType = null;
		}

		configurationEntityCacheModel.entityId = getEntityId();

		String entityId = configurationEntityCacheModel.entityId;

		if ((entityId != null) && (entityId.length() == 0)) {
			configurationEntityCacheModel.entityId = null;
		}

		configurationEntityCacheModel.groupId = getGroupId();

		configurationEntityCacheModel.companyId = getCompanyId();

		configurationEntityCacheModel.userId = getUserId();

		configurationEntityCacheModel.userName = getUserName();

		String userName = configurationEntityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			configurationEntityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			configurationEntityCacheModel.createDate = createDate.getTime();
		}
		else {
			configurationEntityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			configurationEntityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			configurationEntityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		configurationEntityCacheModel.status = getStatus();

		configurationEntityCacheModel.statusByUserId = getStatusByUserId();

		configurationEntityCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName =
			configurationEntityCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			configurationEntityCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			configurationEntityCacheModel.statusDate = statusDate.getTime();
		}
		else {
			configurationEntityCacheModel.statusDate = Long.MIN_VALUE;
		}

		configurationEntityCacheModel.uuid_ = getUuid_();

		String uuid_ = configurationEntityCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			configurationEntityCacheModel.uuid_ = null;
		}

		configurationEntityCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = configurationEntityCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			configurationEntityCacheModel.workflowAction = null;
		}

		return configurationEntityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConfigurationEntity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConfigurationEntity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConfigurationEntity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ConfigurationEntity)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ConfigurationEntity>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ConfigurationEntity.class, ModelWrapper.class);

	}

	private long _id;
	private String _url;
	private String _oldData;
	private String _newData;
	private String _entityType;
	private String _entityId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<ConfigurationEntity, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ConfigurationEntity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("oldData", _oldData);
		_columnOriginalValues.put("newData", _newData);
		_columnOriginalValues.put("entityType", _entityType);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("url", 2L);

		columnBitmasks.put("oldData", 4L);

		columnBitmasks.put("newData", 8L);

		columnBitmasks.put("entityType", 16L);

		columnBitmasks.put("entityId", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		columnBitmasks.put("uuid_", 65536L);

		columnBitmasks.put("workflowAction", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ConfigurationEntity _escapedModel;

}