/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.FeatureLovMap;
import com.ejada.telemony.db.service.FeatureLovMapLocalServiceUtil;

/**
 * The extended model base implementation for the FeatureLovMap service. Represents a row in the &quot;FeatureLovMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeatureLovMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeatureLovMapImpl
 * @see FeatureLovMap
 * @generated
 */
public abstract class FeatureLovMapBaseImpl
	extends FeatureLovMapModelImpl implements FeatureLovMap {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feature lov map model instance should use the <code>FeatureLovMap</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FeatureLovMapLocalServiceUtil.addFeatureLovMap(this);
		}
		else {
			FeatureLovMapLocalServiceUtil.updateFeatureLovMap(this);
		}
	}

}