/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.FeatureLovMap;
import com.ejada.telemony.db.model.FeatureLovMapModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FeatureLovMap service. Represents a row in the &quot;FeatureLovMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FeatureLovMapModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeatureLovMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeatureLovMapImpl
 * @generated
 */
@JSON(strict = true)
public class FeatureLovMapModelImpl
	extends BaseModelImpl<FeatureLovMap> implements FeatureLovMapModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feature lov map model instance should use the <code>FeatureLovMap</code> interface instead.
	 */
	public static final String TABLE_NAME = "FeatureLovMap";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"featureId", Types.BIGINT},
		{"featureEntityResourceId", Types.BIGINT},
		{"lovEntityResourceId", Types.BIGINT}, {"lovDataCode", Types.VARCHAR},
		{"lovType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("featureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("featureEntityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lovEntityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lovDataCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lovType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FeatureLovMap (id LONG not null primary key,featureId LONG,featureEntityResourceId LONG,lovEntityResourceId LONG,lovDataCode VARCHAR(75) null,lovType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FeatureLovMap";

	public static final String ORDER_BY_JPQL = " ORDER BY featureLovMap.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY FeatureLovMap.id ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FEATUREENTITYRESOURCEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FEATUREID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVDATACODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVENTITYRESOURCEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVTYPE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.FeatureLovMap"));

	public FeatureLovMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FeatureLovMap.class;
	}

	@Override
	public String getModelClassName() {
		return FeatureLovMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FeatureLovMap, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FeatureLovMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FeatureLovMap, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FeatureLovMap)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FeatureLovMap, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FeatureLovMap, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FeatureLovMap)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FeatureLovMap, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FeatureLovMap, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FeatureLovMap, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FeatureLovMap, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FeatureLovMap, Object>>();

			attributeGetterFunctions.put("id", FeatureLovMap::getId);
			attributeGetterFunctions.put(
				"featureId", FeatureLovMap::getFeatureId);
			attributeGetterFunctions.put(
				"featureEntityResourceId",
				FeatureLovMap::getFeatureEntityResourceId);
			attributeGetterFunctions.put(
				"lovEntityResourceId", FeatureLovMap::getLovEntityResourceId);
			attributeGetterFunctions.put(
				"lovDataCode", FeatureLovMap::getLovDataCode);
			attributeGetterFunctions.put("lovType", FeatureLovMap::getLovType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FeatureLovMap, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FeatureLovMap, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<FeatureLovMap, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<FeatureLovMap, Long>)FeatureLovMap::setId);
			attributeSetterBiConsumers.put(
				"featureId",
				(BiConsumer<FeatureLovMap, Long>)FeatureLovMap::setFeatureId);
			attributeSetterBiConsumers.put(
				"featureEntityResourceId",
				(BiConsumer<FeatureLovMap, Long>)
					FeatureLovMap::setFeatureEntityResourceId);
			attributeSetterBiConsumers.put(
				"lovEntityResourceId",
				(BiConsumer<FeatureLovMap, Long>)
					FeatureLovMap::setLovEntityResourceId);
			attributeSetterBiConsumers.put(
				"lovDataCode",
				(BiConsumer<FeatureLovMap, String>)
					FeatureLovMap::setLovDataCode);
			attributeSetterBiConsumers.put(
				"lovType",
				(BiConsumer<FeatureLovMap, String>)FeatureLovMap::setLovType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getFeatureId() {
		return _featureId;
	}

	@Override
	public void setFeatureId(long featureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureId = featureId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFeatureId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("featureId"));
	}

	@JSON
	@Override
	public long getFeatureEntityResourceId() {
		return _featureEntityResourceId;
	}

	@Override
	public void setFeatureEntityResourceId(long featureEntityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureEntityResourceId = featureEntityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFeatureEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("featureEntityResourceId"));
	}

	@JSON
	@Override
	public long getLovEntityResourceId() {
		return _lovEntityResourceId;
	}

	@Override
	public void setLovEntityResourceId(long lovEntityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovEntityResourceId = lovEntityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLovEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("lovEntityResourceId"));
	}

	@JSON
	@Override
	public String getLovDataCode() {
		if (_lovDataCode == null) {
			return "";
		}
		else {
			return _lovDataCode;
		}
	}

	@Override
	public void setLovDataCode(String lovDataCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovDataCode = lovDataCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLovDataCode() {
		return getColumnOriginalValue("lovDataCode");
	}

	@JSON
	@Override
	public String getLovType() {
		if (_lovType == null) {
			return "";
		}
		else {
			return _lovType;
		}
	}

	@Override
	public void setLovType(String lovType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovType = lovType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLovType() {
		return getColumnOriginalValue("lovType");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FeatureLovMap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FeatureLovMap toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FeatureLovMap>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FeatureLovMapImpl featureLovMapImpl = new FeatureLovMapImpl();

		featureLovMapImpl.setId(getId());
		featureLovMapImpl.setFeatureId(getFeatureId());
		featureLovMapImpl.setFeatureEntityResourceId(
			getFeatureEntityResourceId());
		featureLovMapImpl.setLovEntityResourceId(getLovEntityResourceId());
		featureLovMapImpl.setLovDataCode(getLovDataCode());
		featureLovMapImpl.setLovType(getLovType());

		featureLovMapImpl.resetOriginalValues();

		return featureLovMapImpl;
	}

	@Override
	public FeatureLovMap cloneWithOriginalValues() {
		FeatureLovMapImpl featureLovMapImpl = new FeatureLovMapImpl();

		featureLovMapImpl.setId(this.<Long>getColumnOriginalValue("id"));
		featureLovMapImpl.setFeatureId(
			this.<Long>getColumnOriginalValue("featureId"));
		featureLovMapImpl.setFeatureEntityResourceId(
			this.<Long>getColumnOriginalValue("featureEntityResourceId"));
		featureLovMapImpl.setLovEntityResourceId(
			this.<Long>getColumnOriginalValue("lovEntityResourceId"));
		featureLovMapImpl.setLovDataCode(
			this.<String>getColumnOriginalValue("lovDataCode"));
		featureLovMapImpl.setLovType(
			this.<String>getColumnOriginalValue("lovType"));

		return featureLovMapImpl;
	}

	@Override
	public int compareTo(FeatureLovMap featureLovMap) {
		long primaryKey = featureLovMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FeatureLovMap)) {
			return false;
		}

		FeatureLovMap featureLovMap = (FeatureLovMap)object;

		long primaryKey = featureLovMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FeatureLovMap> toCacheModel() {
		FeatureLovMapCacheModel featureLovMapCacheModel =
			new FeatureLovMapCacheModel();

		featureLovMapCacheModel.id = getId();

		featureLovMapCacheModel.featureId = getFeatureId();

		featureLovMapCacheModel.featureEntityResourceId =
			getFeatureEntityResourceId();

		featureLovMapCacheModel.lovEntityResourceId = getLovEntityResourceId();

		featureLovMapCacheModel.lovDataCode = getLovDataCode();

		String lovDataCode = featureLovMapCacheModel.lovDataCode;

		if ((lovDataCode != null) && (lovDataCode.length() == 0)) {
			featureLovMapCacheModel.lovDataCode = null;
		}

		featureLovMapCacheModel.lovType = getLovType();

		String lovType = featureLovMapCacheModel.lovType;

		if ((lovType != null) && (lovType.length() == 0)) {
			featureLovMapCacheModel.lovType = null;
		}

		return featureLovMapCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FeatureLovMap, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FeatureLovMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FeatureLovMap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FeatureLovMap)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FeatureLovMap>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FeatureLovMap.class, ModelWrapper.class);

	}

	private long _id;
	private long _featureId;
	private long _featureEntityResourceId;
	private long _lovEntityResourceId;
	private String _lovDataCode;
	private String _lovType;

	public <T> T getColumnValue(String columnName) {
		Function<FeatureLovMap, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FeatureLovMap)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("featureId", _featureId);
		_columnOriginalValues.put(
			"featureEntityResourceId", _featureEntityResourceId);
		_columnOriginalValues.put("lovEntityResourceId", _lovEntityResourceId);
		_columnOriginalValues.put("lovDataCode", _lovDataCode);
		_columnOriginalValues.put("lovType", _lovType);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("featureId", 2L);

		columnBitmasks.put("featureEntityResourceId", 4L);

		columnBitmasks.put("lovEntityResourceId", 8L);

		columnBitmasks.put("lovDataCode", 16L);

		columnBitmasks.put("lovType", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FeatureLovMap _escapedModel;

}