/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Feature;
import com.ejada.telemony.db.model.FeatureModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Feature service. Represents a row in the &quot;FEATURE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FeatureModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeatureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeatureImpl
 * @generated
 */
@JSON(strict = true)
public class FeatureModelImpl
	extends BaseModelImpl<Feature> implements FeatureModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feature model instance should use the <code>Feature</code> interface instead.
	 */
	public static final String TABLE_NAME = "FEATURE";

	public static final Object[][] TABLE_COLUMNS = {
		{"featureId", Types.BIGINT}, {"featureName", Types.VARCHAR},
		{"pageType", Types.VARCHAR}, {"parentPage", Types.BIGINT},
		{"routeId", Types.VARCHAR}, {"featureStatus", Types.BOOLEAN},
		{"blockId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"childResourceId", Types.BIGINT},
		{"version", Types.INTEGER}, {"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("featureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("featureName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pageType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parentPage", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("routeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("featureStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("blockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FEATURE (featureId LONG not null primary key,featureName VARCHAR(75) null,pageType VARCHAR(75) null,parentPage LONG,routeId VARCHAR(75) null,featureStatus BOOLEAN,blockId LONG,channelId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,childResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FEATURE";

	public static final String ORDER_BY_JPQL =
		" ORDER BY feature.featureId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY FEATURE.featureId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHILDRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTPAGE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FEATUREID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Feature"));

	public FeatureModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _featureId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFeatureId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _featureId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Feature.class;
	}

	@Override
	public String getModelClassName() {
		return Feature.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Feature, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Feature, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Feature, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Feature)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Feature, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Feature, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Feature)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Feature, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Feature, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Feature, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Feature, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Feature, Object>>();

			attributeGetterFunctions.put("featureId", Feature::getFeatureId);
			attributeGetterFunctions.put(
				"featureName", Feature::getFeatureName);
			attributeGetterFunctions.put("pageType", Feature::getPageType);
			attributeGetterFunctions.put("parentPage", Feature::getParentPage);
			attributeGetterFunctions.put("routeId", Feature::getRouteId);
			attributeGetterFunctions.put(
				"featureStatus", Feature::getFeatureStatus);
			attributeGetterFunctions.put("blockId", Feature::getBlockId);
			attributeGetterFunctions.put("channelId", Feature::getChannelId);
			attributeGetterFunctions.put("groupId", Feature::getGroupId);
			attributeGetterFunctions.put("companyId", Feature::getCompanyId);
			attributeGetterFunctions.put("userId", Feature::getUserId);
			attributeGetterFunctions.put("userName", Feature::getUserName);
			attributeGetterFunctions.put("createDate", Feature::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Feature::getModifiedDate);
			attributeGetterFunctions.put("status", Feature::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Feature::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Feature::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Feature::getStatusDate);
			attributeGetterFunctions.put("uuid_", Feature::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Feature::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Feature::getEntityResourceId);
			attributeGetterFunctions.put(
				"childResourceId", Feature::getChildResourceId);
			attributeGetterFunctions.put("version", Feature::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Feature::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Feature, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Feature, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Feature, ?>>();

			attributeSetterBiConsumers.put(
				"featureId", (BiConsumer<Feature, Long>)Feature::setFeatureId);
			attributeSetterBiConsumers.put(
				"featureName",
				(BiConsumer<Feature, String>)Feature::setFeatureName);
			attributeSetterBiConsumers.put(
				"pageType", (BiConsumer<Feature, String>)Feature::setPageType);
			attributeSetterBiConsumers.put(
				"parentPage",
				(BiConsumer<Feature, Long>)Feature::setParentPage);
			attributeSetterBiConsumers.put(
				"routeId", (BiConsumer<Feature, String>)Feature::setRouteId);
			attributeSetterBiConsumers.put(
				"featureStatus",
				(BiConsumer<Feature, Boolean>)Feature::setFeatureStatus);
			attributeSetterBiConsumers.put(
				"blockId", (BiConsumer<Feature, Long>)Feature::setBlockId);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Feature, Long>)Feature::setChannelId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Feature, Long>)Feature::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Feature, Long>)Feature::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Feature, Long>)Feature::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Feature, String>)Feature::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Feature, Date>)Feature::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Feature, Date>)Feature::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Feature, Integer>)Feature::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Feature, Long>)Feature::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Feature, String>)Feature::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Feature, Date>)Feature::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Feature, String>)Feature::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Feature, Long>)Feature::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Feature, Long>)Feature::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"childResourceId",
				(BiConsumer<Feature, Long>)Feature::setChildResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Feature, Integer>)Feature::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Feature, String>)Feature::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getFeatureId() {
		return _featureId;
	}

	@Override
	public void setFeatureId(long featureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureId = featureId;
	}

	@JSON
	@Override
	public String getFeatureName() {
		if (_featureName == null) {
			return "";
		}
		else {
			return _featureName;
		}
	}

	@Override
	public void setFeatureName(String featureName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureName = featureName;
	}

	@JSON
	@Override
	public String getPageType() {
		if (_pageType == null) {
			return "";
		}
		else {
			return _pageType;
		}
	}

	@Override
	public void setPageType(String pageType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pageType = pageType;
	}

	@JSON
	@Override
	public long getParentPage() {
		return _parentPage;
	}

	@Override
	public void setParentPage(long parentPage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentPage = parentPage;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentPage() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentPage"));
	}

	@JSON
	@Override
	public String getRouteId() {
		if (_routeId == null) {
			return "";
		}
		else {
			return _routeId;
		}
	}

	@Override
	public void setRouteId(String routeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_routeId = routeId;
	}

	@JSON
	@Override
	public Boolean getFeatureStatus() {
		return _featureStatus;
	}

	@Override
	public void setFeatureStatus(Boolean featureStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureStatus = featureStatus;
	}

	@JSON
	@Override
	public long getBlockId() {
		return _blockId;
	}

	@Override
	public void setBlockId(long blockId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blockId = blockId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public long getChildResourceId() {
		return _childResourceId;
	}

	@Override
	public void setChildResourceId(long childResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_childResourceId = childResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChildResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("childResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Feature.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Feature toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Feature>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FeatureImpl featureImpl = new FeatureImpl();

		featureImpl.setFeatureId(getFeatureId());
		featureImpl.setFeatureName(getFeatureName());
		featureImpl.setPageType(getPageType());
		featureImpl.setParentPage(getParentPage());
		featureImpl.setRouteId(getRouteId());
		featureImpl.setFeatureStatus(getFeatureStatus());
		featureImpl.setBlockId(getBlockId());
		featureImpl.setChannelId(getChannelId());
		featureImpl.setGroupId(getGroupId());
		featureImpl.setCompanyId(getCompanyId());
		featureImpl.setUserId(getUserId());
		featureImpl.setUserName(getUserName());
		featureImpl.setCreateDate(getCreateDate());
		featureImpl.setModifiedDate(getModifiedDate());
		featureImpl.setStatus(getStatus());
		featureImpl.setStatusByUserId(getStatusByUserId());
		featureImpl.setStatusByUserName(getStatusByUserName());
		featureImpl.setStatusDate(getStatusDate());
		featureImpl.setUuid_(getUuid_());
		featureImpl.setOriginalEntityId(getOriginalEntityId());
		featureImpl.setEntityResourceId(getEntityResourceId());
		featureImpl.setChildResourceId(getChildResourceId());
		featureImpl.setVersion(getVersion());
		featureImpl.setWorkflowAction(getWorkflowAction());

		featureImpl.resetOriginalValues();

		return featureImpl;
	}

	@Override
	public Feature cloneWithOriginalValues() {
		FeatureImpl featureImpl = new FeatureImpl();

		featureImpl.setFeatureId(
			this.<Long>getColumnOriginalValue("featureId"));
		featureImpl.setFeatureName(
			this.<String>getColumnOriginalValue("featureName"));
		featureImpl.setPageType(
			this.<String>getColumnOriginalValue("pageType"));
		featureImpl.setParentPage(
			this.<Long>getColumnOriginalValue("parentPage"));
		featureImpl.setRouteId(this.<String>getColumnOriginalValue("routeId"));
		featureImpl.setFeatureStatus(
			this.<Boolean>getColumnOriginalValue("featureStatus"));
		featureImpl.setBlockId(this.<Long>getColumnOriginalValue("blockId"));
		featureImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		featureImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		featureImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		featureImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		featureImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		featureImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		featureImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		featureImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		featureImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		featureImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		featureImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		featureImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		featureImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		featureImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		featureImpl.setChildResourceId(
			this.<Long>getColumnOriginalValue("childResourceId"));
		featureImpl.setVersion(this.<Integer>getColumnOriginalValue("version"));
		featureImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return featureImpl;
	}

	@Override
	public int compareTo(Feature feature) {
		long primaryKey = feature.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Feature)) {
			return false;
		}

		Feature feature = (Feature)object;

		long primaryKey = feature.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Feature> toCacheModel() {
		FeatureCacheModel featureCacheModel = new FeatureCacheModel();

		featureCacheModel.featureId = getFeatureId();

		featureCacheModel.featureName = getFeatureName();

		String featureName = featureCacheModel.featureName;

		if ((featureName != null) && (featureName.length() == 0)) {
			featureCacheModel.featureName = null;
		}

		featureCacheModel.pageType = getPageType();

		String pageType = featureCacheModel.pageType;

		if ((pageType != null) && (pageType.length() == 0)) {
			featureCacheModel.pageType = null;
		}

		featureCacheModel.parentPage = getParentPage();

		featureCacheModel.routeId = getRouteId();

		String routeId = featureCacheModel.routeId;

		if ((routeId != null) && (routeId.length() == 0)) {
			featureCacheModel.routeId = null;
		}

		Boolean featureStatus = getFeatureStatus();

		if (featureStatus != null) {
			featureCacheModel.featureStatus = featureStatus;
		}

		featureCacheModel.blockId = getBlockId();

		featureCacheModel.channelId = getChannelId();

		featureCacheModel.groupId = getGroupId();

		featureCacheModel.companyId = getCompanyId();

		featureCacheModel.userId = getUserId();

		featureCacheModel.userName = getUserName();

		String userName = featureCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			featureCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			featureCacheModel.createDate = createDate.getTime();
		}
		else {
			featureCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			featureCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			featureCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		featureCacheModel.status = getStatus();

		featureCacheModel.statusByUserId = getStatusByUserId();

		featureCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = featureCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			featureCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			featureCacheModel.statusDate = statusDate.getTime();
		}
		else {
			featureCacheModel.statusDate = Long.MIN_VALUE;
		}

		featureCacheModel.uuid_ = getUuid_();

		String uuid_ = featureCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			featureCacheModel.uuid_ = null;
		}

		featureCacheModel.originalEntityId = getOriginalEntityId();

		featureCacheModel.entityResourceId = getEntityResourceId();

		featureCacheModel.childResourceId = getChildResourceId();

		featureCacheModel.version = getVersion();

		featureCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = featureCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			featureCacheModel.workflowAction = null;
		}

		return featureCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Feature, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Feature, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Feature, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Feature)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Feature>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Feature.class, ModelWrapper.class);

	}

	private long _featureId;
	private String _featureName;
	private String _pageType;
	private long _parentPage;
	private String _routeId;
	private Boolean _featureStatus;
	private long _blockId;
	private long _channelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private long _childResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<Feature, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Feature)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("featureId", _featureId);
		_columnOriginalValues.put("featureName", _featureName);
		_columnOriginalValues.put("pageType", _pageType);
		_columnOriginalValues.put("parentPage", _parentPage);
		_columnOriginalValues.put("routeId", _routeId);
		_columnOriginalValues.put("featureStatus", _featureStatus);
		_columnOriginalValues.put("blockId", _blockId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("childResourceId", _childResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("featureId", 1L);

		columnBitmasks.put("featureName", 2L);

		columnBitmasks.put("pageType", 4L);

		columnBitmasks.put("parentPage", 8L);

		columnBitmasks.put("routeId", 16L);

		columnBitmasks.put("featureStatus", 32L);

		columnBitmasks.put("blockId", 64L);

		columnBitmasks.put("channelId", 128L);

		columnBitmasks.put("groupId", 256L);

		columnBitmasks.put("companyId", 512L);

		columnBitmasks.put("userId", 1024L);

		columnBitmasks.put("userName", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		columnBitmasks.put("status", 16384L);

		columnBitmasks.put("statusByUserId", 32768L);

		columnBitmasks.put("statusByUserName", 65536L);

		columnBitmasks.put("statusDate", 131072L);

		columnBitmasks.put("uuid_", 262144L);

		columnBitmasks.put("originalEntityId", 524288L);

		columnBitmasks.put("entityResourceId", 1048576L);

		columnBitmasks.put("childResourceId", 2097152L);

		columnBitmasks.put("version", 4194304L);

		columnBitmasks.put("workflowAction", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Feature _escapedModel;

}