/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Feature;
import com.ejada.telemony.db.service.FeatureLocalServiceUtil;

/**
 * The extended model base implementation for the Feature service. Represents a row in the &quot;FEATURE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeatureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeatureImpl
 * @see Feature
 * @generated
 */
public abstract class FeatureBaseImpl
	extends FeatureModelImpl implements Feature {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feature model instance should use the <code>Feature</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FeatureLocalServiceUtil.addFeature(this);
		}
		else {
			FeatureLocalServiceUtil.updateFeature(this);
		}
	}

}