/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.GlobalVersion;
import com.ejada.telemony.db.service.GlobalVersionLocalServiceUtil;

/**
 * The extended model base implementation for the GlobalVersion service. Represents a row in the &quot;GlobalVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GlobalVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GlobalVersionImpl
 * @see GlobalVersion
 * @generated
 */
public abstract class GlobalVersionBaseImpl
	extends GlobalVersionModelImpl implements GlobalVersion {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a global version model instance should use the <code>GlobalVersion</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GlobalVersionLocalServiceUtil.addGlobalVersion(this);
		}
		else {
			GlobalVersionLocalServiceUtil.updateGlobalVersion(this);
		}
	}

}