/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.GlobalVersion;
import com.ejada.telemony.db.model.GlobalVersionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GlobalVersion service. Represents a row in the &quot;GlobalVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GlobalVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GlobalVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GlobalVersionImpl
 * @generated
 */
public class GlobalVersionModelImpl
	extends BaseModelImpl<GlobalVersion> implements GlobalVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a global version model instance should use the <code>GlobalVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "GlobalVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"versionId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"channelId", Types.BIGINT}, {"componentName", Types.VARCHAR},
		{"version", Types.BIGINT}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("versionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("componentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GlobalVersion (versionId LONG not null primary key,companyId LONG,channelId LONG,componentName VARCHAR(75) null,version LONG,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table GlobalVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY globalVersion.versionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GlobalVersion.versionId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPONENTNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.GlobalVersion"));

	public GlobalVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _versionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _versionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GlobalVersion.class;
	}

	@Override
	public String getModelClassName() {
		return GlobalVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GlobalVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GlobalVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GlobalVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GlobalVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GlobalVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GlobalVersion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GlobalVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GlobalVersion, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GlobalVersion, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<GlobalVersion, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<GlobalVersion, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<GlobalVersion, Object>>();

			attributeGetterFunctions.put(
				"versionId", GlobalVersion::getVersionId);
			attributeGetterFunctions.put(
				"companyId", GlobalVersion::getCompanyId);
			attributeGetterFunctions.put(
				"channelId", GlobalVersion::getChannelId);
			attributeGetterFunctions.put(
				"componentName", GlobalVersion::getComponentName);
			attributeGetterFunctions.put("version", GlobalVersion::getVersion);
			attributeGetterFunctions.put(
				"modifiedDate", GlobalVersion::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<GlobalVersion, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<GlobalVersion, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<GlobalVersion, ?>>();

			attributeSetterBiConsumers.put(
				"versionId",
				(BiConsumer<GlobalVersion, Long>)GlobalVersion::setVersionId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<GlobalVersion, Long>)GlobalVersion::setCompanyId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<GlobalVersion, Long>)GlobalVersion::setChannelId);
			attributeSetterBiConsumers.put(
				"componentName",
				(BiConsumer<GlobalVersion, String>)
					GlobalVersion::setComponentName);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<GlobalVersion, Long>)GlobalVersion::setVersion);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<GlobalVersion, Date>)
					GlobalVersion::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getVersionId() {
		return _versionId;
	}

	@Override
	public void setVersionId(long versionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_versionId = versionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@Override
	public String getComponentName() {
		if (_componentName == null) {
			return "";
		}
		else {
			return _componentName;
		}
	}

	@Override
	public void setComponentName(String componentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_componentName = componentName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalComponentName() {
		return getColumnOriginalValue("componentName");
	}

	@Override
	public long getVersion() {
		return _version;
	}

	@Override
	public void setVersion(long version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GlobalVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GlobalVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GlobalVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GlobalVersionImpl globalVersionImpl = new GlobalVersionImpl();

		globalVersionImpl.setVersionId(getVersionId());
		globalVersionImpl.setCompanyId(getCompanyId());
		globalVersionImpl.setChannelId(getChannelId());
		globalVersionImpl.setComponentName(getComponentName());
		globalVersionImpl.setVersion(getVersion());
		globalVersionImpl.setModifiedDate(getModifiedDate());

		globalVersionImpl.resetOriginalValues();

		return globalVersionImpl;
	}

	@Override
	public GlobalVersion cloneWithOriginalValues() {
		GlobalVersionImpl globalVersionImpl = new GlobalVersionImpl();

		globalVersionImpl.setVersionId(
			this.<Long>getColumnOriginalValue("versionId"));
		globalVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		globalVersionImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		globalVersionImpl.setComponentName(
			this.<String>getColumnOriginalValue("componentName"));
		globalVersionImpl.setVersion(
			this.<Long>getColumnOriginalValue("version"));
		globalVersionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return globalVersionImpl;
	}

	@Override
	public int compareTo(GlobalVersion globalVersion) {
		long primaryKey = globalVersion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GlobalVersion)) {
			return false;
		}

		GlobalVersion globalVersion = (GlobalVersion)object;

		long primaryKey = globalVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GlobalVersion> toCacheModel() {
		GlobalVersionCacheModel globalVersionCacheModel =
			new GlobalVersionCacheModel();

		globalVersionCacheModel.versionId = getVersionId();

		globalVersionCacheModel.companyId = getCompanyId();

		globalVersionCacheModel.channelId = getChannelId();

		globalVersionCacheModel.componentName = getComponentName();

		String componentName = globalVersionCacheModel.componentName;

		if ((componentName != null) && (componentName.length() == 0)) {
			globalVersionCacheModel.componentName = null;
		}

		globalVersionCacheModel.version = getVersion();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			globalVersionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			globalVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return globalVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GlobalVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GlobalVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GlobalVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((GlobalVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GlobalVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					GlobalVersion.class, ModelWrapper.class);

	}

	private long _versionId;
	private long _companyId;
	private long _channelId;
	private String _componentName;
	private long _version;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<GlobalVersion, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GlobalVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("versionId", _versionId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("componentName", _componentName);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("versionId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("channelId", 4L);

		columnBitmasks.put("componentName", 8L);

		columnBitmasks.put("version", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GlobalVersion _escapedModel;

}