/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.ImportRequest;
import com.ejada.telemony.db.model.ImportRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ImportRequest service. Represents a row in the &quot;ImportRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ImportRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImportRequestImpl
 * @generated
 */
@JSON(strict = true)
public class ImportRequestModelImpl
	extends BaseModelImpl<ImportRequest> implements ImportRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import request model instance should use the <code>ImportRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "ImportRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"type", Types.VARCHAR},
		{"fileName", Types.VARCHAR}, {"filePath", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ImportRequest (id LONG not null primary key,type VARCHAR(75) null,fileName VARCHAR(75) null,filePath VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ImportRequest";

	public static final String ORDER_BY_JPQL = " ORDER BY importRequest.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY ImportRequest.id ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.ImportRequest"));

	public ImportRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ImportRequest.class;
	}

	@Override
	public String getModelClassName() {
		return ImportRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ImportRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ImportRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ImportRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ImportRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ImportRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ImportRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ImportRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ImportRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ImportRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ImportRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ImportRequest, Object>>();

			attributeGetterFunctions.put("id", ImportRequest::getId);
			attributeGetterFunctions.put("type", ImportRequest::getType);
			attributeGetterFunctions.put(
				"fileName", ImportRequest::getFileName);
			attributeGetterFunctions.put(
				"filePath", ImportRequest::getFilePath);
			attributeGetterFunctions.put("groupId", ImportRequest::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ImportRequest::getCompanyId);
			attributeGetterFunctions.put("userId", ImportRequest::getUserId);
			attributeGetterFunctions.put(
				"userName", ImportRequest::getUserName);
			attributeGetterFunctions.put(
				"createDate", ImportRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ImportRequest::getModifiedDate);
			attributeGetterFunctions.put("status", ImportRequest::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", ImportRequest::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", ImportRequest::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", ImportRequest::getStatusDate);
			attributeGetterFunctions.put("uuid_", ImportRequest::getUuid_);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ImportRequest, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ImportRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ImportRequest, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<ImportRequest, Long>)ImportRequest::setId);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<ImportRequest, String>)ImportRequest::setType);
			attributeSetterBiConsumers.put(
				"fileName",
				(BiConsumer<ImportRequest, String>)ImportRequest::setFileName);
			attributeSetterBiConsumers.put(
				"filePath",
				(BiConsumer<ImportRequest, String>)ImportRequest::setFilePath);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ImportRequest, Long>)ImportRequest::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ImportRequest, Long>)ImportRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ImportRequest, Long>)ImportRequest::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ImportRequest, String>)ImportRequest::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ImportRequest, Date>)ImportRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ImportRequest, Date>)
					ImportRequest::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<ImportRequest, Integer>)ImportRequest::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<ImportRequest, Long>)
					ImportRequest::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<ImportRequest, String>)
					ImportRequest::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<ImportRequest, Date>)ImportRequest::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_",
				(BiConsumer<ImportRequest, String>)ImportRequest::setUuid_);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type");
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@JSON
	@Override
	public String getFilePath() {
		if (_filePath == null) {
			return "";
		}
		else {
			return _filePath;
		}
	}

	@Override
	public void setFilePath(String filePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filePath = filePath;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ImportRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ImportRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ImportRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ImportRequestImpl importRequestImpl = new ImportRequestImpl();

		importRequestImpl.setId(getId());
		importRequestImpl.setType(getType());
		importRequestImpl.setFileName(getFileName());
		importRequestImpl.setFilePath(getFilePath());
		importRequestImpl.setGroupId(getGroupId());
		importRequestImpl.setCompanyId(getCompanyId());
		importRequestImpl.setUserId(getUserId());
		importRequestImpl.setUserName(getUserName());
		importRequestImpl.setCreateDate(getCreateDate());
		importRequestImpl.setModifiedDate(getModifiedDate());
		importRequestImpl.setStatus(getStatus());
		importRequestImpl.setStatusByUserId(getStatusByUserId());
		importRequestImpl.setStatusByUserName(getStatusByUserName());
		importRequestImpl.setStatusDate(getStatusDate());
		importRequestImpl.setUuid_(getUuid_());

		importRequestImpl.resetOriginalValues();

		return importRequestImpl;
	}

	@Override
	public ImportRequest cloneWithOriginalValues() {
		ImportRequestImpl importRequestImpl = new ImportRequestImpl();

		importRequestImpl.setId(this.<Long>getColumnOriginalValue("id"));
		importRequestImpl.setType(this.<String>getColumnOriginalValue("type"));
		importRequestImpl.setFileName(
			this.<String>getColumnOriginalValue("fileName"));
		importRequestImpl.setFilePath(
			this.<String>getColumnOriginalValue("filePath"));
		importRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		importRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		importRequestImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		importRequestImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		importRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		importRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		importRequestImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		importRequestImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		importRequestImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		importRequestImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		importRequestImpl.setUuid_(
			this.<String>getColumnOriginalValue("uuid_"));

		return importRequestImpl;
	}

	@Override
	public int compareTo(ImportRequest importRequest) {
		long primaryKey = importRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ImportRequest)) {
			return false;
		}

		ImportRequest importRequest = (ImportRequest)object;

		long primaryKey = importRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ImportRequest> toCacheModel() {
		ImportRequestCacheModel importRequestCacheModel =
			new ImportRequestCacheModel();

		importRequestCacheModel.id = getId();

		importRequestCacheModel.type = getType();

		String type = importRequestCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			importRequestCacheModel.type = null;
		}

		importRequestCacheModel.fileName = getFileName();

		String fileName = importRequestCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			importRequestCacheModel.fileName = null;
		}

		importRequestCacheModel.filePath = getFilePath();

		String filePath = importRequestCacheModel.filePath;

		if ((filePath != null) && (filePath.length() == 0)) {
			importRequestCacheModel.filePath = null;
		}

		importRequestCacheModel.groupId = getGroupId();

		importRequestCacheModel.companyId = getCompanyId();

		importRequestCacheModel.userId = getUserId();

		importRequestCacheModel.userName = getUserName();

		String userName = importRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			importRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			importRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			importRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			importRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			importRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		importRequestCacheModel.status = getStatus();

		importRequestCacheModel.statusByUserId = getStatusByUserId();

		importRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = importRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			importRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			importRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			importRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		importRequestCacheModel.uuid_ = getUuid_();

		String uuid_ = importRequestCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			importRequestCacheModel.uuid_ = null;
		}

		return importRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ImportRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ImportRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ImportRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ImportRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ImportRequest.class, ModelWrapper.class);

	}

	private long _id;
	private String _type;
	private String _fileName;
	private String _filePath;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;

	public <T> T getColumnValue(String columnName) {
		Function<ImportRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ImportRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("type", _type);
		_columnOriginalValues.put("fileName", _fileName);
		_columnOriginalValues.put("filePath", _filePath);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("type", 2L);

		columnBitmasks.put("fileName", 4L);

		columnBitmasks.put("filePath", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("status", 1024L);

		columnBitmasks.put("statusByUserId", 2048L);

		columnBitmasks.put("statusByUserName", 4096L);

		columnBitmasks.put("statusDate", 8192L);

		columnBitmasks.put("uuid_", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ImportRequest _escapedModel;

}