/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Languages;
import com.ejada.telemony.db.model.LanguagesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Languages service. Represents a row in the &quot;LANGUAGES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LanguagesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LanguagesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LanguagesImpl
 * @generated
 */
@JSON(strict = true)
public class LanguagesModelImpl
	extends BaseModelImpl<Languages> implements LanguagesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a languages model instance should use the <code>Languages</code> interface instead.
	 */
	public static final String TABLE_NAME = "LANGUAGES";

	public static final Object[][] TABLE_COLUMNS = {
		{"languageId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"langName", Types.VARCHAR}, {"local", Types.VARCHAR},
		{"primaryLanguage", Types.BOOLEAN}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"uuid_", Types.VARCHAR},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT},
		{"version", Types.INTEGER}, {"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("languageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("langName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("local", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryLanguage", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LANGUAGES (languageId LONG not null primary key,channelId LONG,langName VARCHAR(75) null,local VARCHAR(75) null,primaryLanguage BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LANGUAGES";

	public static final String ORDER_BY_JPQL =
		" ORDER BY languages.languageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LANGUAGES.languageId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCAL_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Languages"));

	public LanguagesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _languageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLanguageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _languageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Languages.class;
	}

	@Override
	public String getModelClassName() {
		return Languages.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Languages, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Languages, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Languages, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Languages)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Languages, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Languages, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Languages)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Languages, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Languages, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Languages, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Languages, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Languages, Object>>();

			attributeGetterFunctions.put(
				"languageId", Languages::getLanguageId);
			attributeGetterFunctions.put("channelId", Languages::getChannelId);
			attributeGetterFunctions.put("langName", Languages::getLangName);
			attributeGetterFunctions.put("local", Languages::getLocal);
			attributeGetterFunctions.put(
				"primaryLanguage", Languages::getPrimaryLanguage);
			attributeGetterFunctions.put("groupId", Languages::getGroupId);
			attributeGetterFunctions.put("companyId", Languages::getCompanyId);
			attributeGetterFunctions.put("userId", Languages::getUserId);
			attributeGetterFunctions.put("userName", Languages::getUserName);
			attributeGetterFunctions.put(
				"createDate", Languages::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Languages::getModifiedDate);
			attributeGetterFunctions.put("status", Languages::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Languages::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Languages::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", Languages::getStatusDate);
			attributeGetterFunctions.put("uuid_", Languages::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Languages::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Languages::getEntityResourceId);
			attributeGetterFunctions.put("version", Languages::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Languages::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Languages, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Languages, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Languages, ?>>();

			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<Languages, Long>)Languages::setLanguageId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<Languages, Long>)Languages::setChannelId);
			attributeSetterBiConsumers.put(
				"langName",
				(BiConsumer<Languages, String>)Languages::setLangName);
			attributeSetterBiConsumers.put(
				"local", (BiConsumer<Languages, String>)Languages::setLocal);
			attributeSetterBiConsumers.put(
				"primaryLanguage",
				(BiConsumer<Languages, Boolean>)Languages::setPrimaryLanguage);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Languages, Long>)Languages::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Languages, Long>)Languages::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Languages, Long>)Languages::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Languages, String>)Languages::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Languages, Date>)Languages::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Languages, Date>)Languages::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Languages, Integer>)Languages::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Languages, Long>)Languages::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Languages, String>)Languages::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Languages, Date>)Languages::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Languages, String>)Languages::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Languages, Long>)Languages::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Languages, Long>)Languages::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<Languages, Integer>)Languages::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Languages, String>)Languages::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLanguageId() {
		return _languageId;
	}

	@Override
	public void setLanguageId(long languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getLangName() {
		if (_langName == null) {
			return "";
		}
		else {
			return _langName;
		}
	}

	@Override
	public void setLangName(String langName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_langName = langName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLangName() {
		return getColumnOriginalValue("langName");
	}

	@JSON
	@Override
	public String getLocal() {
		if (_local == null) {
			return "";
		}
		else {
			return _local;
		}
	}

	@Override
	public void setLocal(String local) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_local = local;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLocal() {
		return getColumnOriginalValue("local");
	}

	@JSON
	@Override
	public boolean getPrimaryLanguage() {
		return _primaryLanguage;
	}

	@JSON
	@Override
	public boolean isPrimaryLanguage() {
		return _primaryLanguage;
	}

	@Override
	public void setPrimaryLanguage(boolean primaryLanguage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_primaryLanguage = primaryLanguage;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Languages.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Languages toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Languages>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LanguagesImpl languagesImpl = new LanguagesImpl();

		languagesImpl.setLanguageId(getLanguageId());
		languagesImpl.setChannelId(getChannelId());
		languagesImpl.setLangName(getLangName());
		languagesImpl.setLocal(getLocal());
		languagesImpl.setPrimaryLanguage(isPrimaryLanguage());
		languagesImpl.setGroupId(getGroupId());
		languagesImpl.setCompanyId(getCompanyId());
		languagesImpl.setUserId(getUserId());
		languagesImpl.setUserName(getUserName());
		languagesImpl.setCreateDate(getCreateDate());
		languagesImpl.setModifiedDate(getModifiedDate());
		languagesImpl.setStatus(getStatus());
		languagesImpl.setStatusByUserId(getStatusByUserId());
		languagesImpl.setStatusByUserName(getStatusByUserName());
		languagesImpl.setStatusDate(getStatusDate());
		languagesImpl.setUuid_(getUuid_());
		languagesImpl.setOriginalEntityId(getOriginalEntityId());
		languagesImpl.setEntityResourceId(getEntityResourceId());
		languagesImpl.setVersion(getVersion());
		languagesImpl.setWorkflowAction(getWorkflowAction());

		languagesImpl.resetOriginalValues();

		return languagesImpl;
	}

	@Override
	public Languages cloneWithOriginalValues() {
		LanguagesImpl languagesImpl = new LanguagesImpl();

		languagesImpl.setLanguageId(
			this.<Long>getColumnOriginalValue("languageId"));
		languagesImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		languagesImpl.setLangName(
			this.<String>getColumnOriginalValue("langName"));
		languagesImpl.setLocal(this.<String>getColumnOriginalValue("local"));
		languagesImpl.setPrimaryLanguage(
			this.<Boolean>getColumnOriginalValue("primaryLanguage"));
		languagesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		languagesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		languagesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		languagesImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		languagesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		languagesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		languagesImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		languagesImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		languagesImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		languagesImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		languagesImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		languagesImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		languagesImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		languagesImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		languagesImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return languagesImpl;
	}

	@Override
	public int compareTo(Languages languages) {
		long primaryKey = languages.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Languages)) {
			return false;
		}

		Languages languages = (Languages)object;

		long primaryKey = languages.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Languages> toCacheModel() {
		LanguagesCacheModel languagesCacheModel = new LanguagesCacheModel();

		languagesCacheModel.languageId = getLanguageId();

		languagesCacheModel.channelId = getChannelId();

		languagesCacheModel.langName = getLangName();

		String langName = languagesCacheModel.langName;

		if ((langName != null) && (langName.length() == 0)) {
			languagesCacheModel.langName = null;
		}

		languagesCacheModel.local = getLocal();

		String local = languagesCacheModel.local;

		if ((local != null) && (local.length() == 0)) {
			languagesCacheModel.local = null;
		}

		languagesCacheModel.primaryLanguage = isPrimaryLanguage();

		languagesCacheModel.groupId = getGroupId();

		languagesCacheModel.companyId = getCompanyId();

		languagesCacheModel.userId = getUserId();

		languagesCacheModel.userName = getUserName();

		String userName = languagesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			languagesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			languagesCacheModel.createDate = createDate.getTime();
		}
		else {
			languagesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			languagesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			languagesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		languagesCacheModel.status = getStatus();

		languagesCacheModel.statusByUserId = getStatusByUserId();

		languagesCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = languagesCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			languagesCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			languagesCacheModel.statusDate = statusDate.getTime();
		}
		else {
			languagesCacheModel.statusDate = Long.MIN_VALUE;
		}

		languagesCacheModel.uuid_ = getUuid_();

		String uuid_ = languagesCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			languagesCacheModel.uuid_ = null;
		}

		languagesCacheModel.originalEntityId = getOriginalEntityId();

		languagesCacheModel.entityResourceId = getEntityResourceId();

		languagesCacheModel.version = getVersion();

		languagesCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = languagesCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			languagesCacheModel.workflowAction = null;
		}

		return languagesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Languages, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Languages, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Languages, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Languages)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Languages>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Languages.class, ModelWrapper.class);

	}

	private long _languageId;
	private long _channelId;
	private String _langName;
	private String _local;
	private boolean _primaryLanguage;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<Languages, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Languages)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("langName", _langName);
		_columnOriginalValues.put("local", _local);
		_columnOriginalValues.put("primaryLanguage", _primaryLanguage);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("languageId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("langName", 4L);

		columnBitmasks.put("local", 8L);

		columnBitmasks.put("primaryLanguage", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("statusByUserId", 4096L);

		columnBitmasks.put("statusByUserName", 8192L);

		columnBitmasks.put("statusDate", 16384L);

		columnBitmasks.put("uuid_", 32768L);

		columnBitmasks.put("originalEntityId", 65536L);

		columnBitmasks.put("entityResourceId", 131072L);

		columnBitmasks.put("version", 262144L);

		columnBitmasks.put("workflowAction", 524288L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Languages _escapedModel;

}