/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Localization;
import com.ejada.telemony.db.service.LocalizationLocalServiceUtil;

/**
 * The extended model base implementation for the Localization service. Represents a row in the &quot;LOCALIZATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LocalizationImpl
 * @see Localization
 * @generated
 */
public abstract class LocalizationBaseImpl
	extends LocalizationModelImpl implements Localization {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a localization model instance should use the <code>Localization</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LocalizationLocalServiceUtil.addLocalization(this);
		}
		else {
			LocalizationLocalServiceUtil.updateLocalization(this);
		}
	}

}