/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Localization;
import com.ejada.telemony.db.model.LocalizationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Localization service. Represents a row in the &quot;LOCALIZATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LocalizationImpl
 * @generated
 */
@JSON(strict = true)
public class LocalizationModelImpl
	extends BaseModelImpl<Localization> implements LocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a localization model instance should use the <code>Localization</code> interface instead.
	 */
	public static final String TABLE_NAME = "LOCALIZATION";

	public static final Object[][] TABLE_COLUMNS = {
		{"localizationId", Types.BIGINT}, {"localValue", Types.VARCHAR},
		{"version", Types.BIGINT}, {"languageId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"channelId", Types.BIGINT},
		{"featureId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"workflowBatchId", Types.VARCHAR},
		{"globalVersion", Types.BIGINT}, {"importRequestId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("localizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("localValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("featureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowBatchId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("globalVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("importRequestId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LOCALIZATION (localizationId LONG not null primary key,localValue VARCHAR(75) null,version LONG,languageId LONG,userName VARCHAR(75) null,channelId LONG,featureId LONG,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,workflowBatchId VARCHAR(75) null,globalVersion LONG,importRequestId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LOCALIZATION";

	public static final String ORDER_BY_JPQL =
		" ORDER BY localization.localizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LOCALIZATION.localizationId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FEATUREID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GLOBALVERSION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWBATCHID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCALIZATIONID_COLUMN_BITMASK = 64L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Localization"));

	public LocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _localizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _localizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Localization.class;
	}

	@Override
	public String getModelClassName() {
		return Localization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Localization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Localization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Localization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Localization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Localization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Localization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Localization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Localization, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Localization, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Localization, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Localization, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Localization, Object>>();

			attributeGetterFunctions.put(
				"localizationId", Localization::getLocalizationId);
			attributeGetterFunctions.put(
				"localValue", Localization::getLocalValue);
			attributeGetterFunctions.put("version", Localization::getVersion);
			attributeGetterFunctions.put(
				"languageId", Localization::getLanguageId);
			attributeGetterFunctions.put("userName", Localization::getUserName);
			attributeGetterFunctions.put(
				"channelId", Localization::getChannelId);
			attributeGetterFunctions.put(
				"featureId", Localization::getFeatureId);
			attributeGetterFunctions.put("groupId", Localization::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Localization::getCompanyId);
			attributeGetterFunctions.put("userId", Localization::getUserId);
			attributeGetterFunctions.put(
				"createDate", Localization::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Localization::getModifiedDate);
			attributeGetterFunctions.put("status", Localization::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Localization::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Localization::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", Localization::getStatusDate);
			attributeGetterFunctions.put("uuid_", Localization::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Localization::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Localization::getEntityResourceId);
			attributeGetterFunctions.put(
				"workflowBatchId", Localization::getWorkflowBatchId);
			attributeGetterFunctions.put(
				"globalVersion", Localization::getGlobalVersion);
			attributeGetterFunctions.put(
				"importRequestId", Localization::getImportRequestId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Localization, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Localization, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Localization, ?>>();

			attributeSetterBiConsumers.put(
				"localizationId",
				(BiConsumer<Localization, Long>)
					Localization::setLocalizationId);
			attributeSetterBiConsumers.put(
				"localValue",
				(BiConsumer<Localization, String>)Localization::setLocalValue);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<Localization, Long>)Localization::setVersion);
			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<Localization, Long>)Localization::setLanguageId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Localization, String>)Localization::setUserName);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<Localization, Long>)Localization::setChannelId);
			attributeSetterBiConsumers.put(
				"featureId",
				(BiConsumer<Localization, Long>)Localization::setFeatureId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Localization, Long>)Localization::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Localization, Long>)Localization::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Localization, Long>)Localization::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Localization, Date>)Localization::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Localization, Date>)Localization::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<Localization, Integer>)Localization::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Localization, Long>)
					Localization::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Localization, String>)
					Localization::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Localization, Date>)Localization::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_",
				(BiConsumer<Localization, String>)Localization::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Localization, Long>)
					Localization::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Localization, Long>)
					Localization::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"workflowBatchId",
				(BiConsumer<Localization, String>)
					Localization::setWorkflowBatchId);
			attributeSetterBiConsumers.put(
				"globalVersion",
				(BiConsumer<Localization, Long>)Localization::setGlobalVersion);
			attributeSetterBiConsumers.put(
				"importRequestId",
				(BiConsumer<Localization, Long>)
					Localization::setImportRequestId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLocalizationId() {
		return _localizationId;
	}

	@Override
	public void setLocalizationId(long localizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_localizationId = localizationId;
	}

	@JSON
	@Override
	public String getLocalValue() {
		if (_localValue == null) {
			return "";
		}
		else {
			return _localValue;
		}
	}

	@Override
	public void setLocalValue(String localValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_localValue = localValue;
	}

	@JSON
	@Override
	public long getVersion() {
		return _version;
	}

	@Override
	public void setVersion(long version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public long getLanguageId() {
		return _languageId;
	}

	@Override
	public void setLanguageId(long languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLanguageId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("languageId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public long getFeatureId() {
		return _featureId;
	}

	@Override
	public void setFeatureId(long featureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureId = featureId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFeatureId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("featureId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public String getWorkflowBatchId() {
		if (_workflowBatchId == null) {
			return "";
		}
		else {
			return _workflowBatchId;
		}
	}

	@Override
	public void setWorkflowBatchId(String workflowBatchId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowBatchId = workflowBatchId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalWorkflowBatchId() {
		return getColumnOriginalValue("workflowBatchId");
	}

	@JSON
	@Override
	public long getGlobalVersion() {
		return _globalVersion;
	}

	@Override
	public void setGlobalVersion(long globalVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_globalVersion = globalVersion;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGlobalVersion() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("globalVersion"));
	}

	@JSON
	@Override
	public long getImportRequestId() {
		return _importRequestId;
	}

	@Override
	public void setImportRequestId(long importRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importRequestId = importRequestId;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Localization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Localization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Localization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LocalizationImpl localizationImpl = new LocalizationImpl();

		localizationImpl.setLocalizationId(getLocalizationId());
		localizationImpl.setLocalValue(getLocalValue());
		localizationImpl.setVersion(getVersion());
		localizationImpl.setLanguageId(getLanguageId());
		localizationImpl.setUserName(getUserName());
		localizationImpl.setChannelId(getChannelId());
		localizationImpl.setFeatureId(getFeatureId());
		localizationImpl.setGroupId(getGroupId());
		localizationImpl.setCompanyId(getCompanyId());
		localizationImpl.setUserId(getUserId());
		localizationImpl.setCreateDate(getCreateDate());
		localizationImpl.setModifiedDate(getModifiedDate());
		localizationImpl.setStatus(getStatus());
		localizationImpl.setStatusByUserId(getStatusByUserId());
		localizationImpl.setStatusByUserName(getStatusByUserName());
		localizationImpl.setStatusDate(getStatusDate());
		localizationImpl.setUuid_(getUuid_());
		localizationImpl.setOriginalEntityId(getOriginalEntityId());
		localizationImpl.setEntityResourceId(getEntityResourceId());
		localizationImpl.setWorkflowBatchId(getWorkflowBatchId());
		localizationImpl.setGlobalVersion(getGlobalVersion());
		localizationImpl.setImportRequestId(getImportRequestId());

		localizationImpl.resetOriginalValues();

		return localizationImpl;
	}

	@Override
	public Localization cloneWithOriginalValues() {
		LocalizationImpl localizationImpl = new LocalizationImpl();

		localizationImpl.setLocalizationId(
			this.<Long>getColumnOriginalValue("localizationId"));
		localizationImpl.setLocalValue(
			this.<String>getColumnOriginalValue("localValue"));
		localizationImpl.setVersion(
			this.<Long>getColumnOriginalValue("version"));
		localizationImpl.setLanguageId(
			this.<Long>getColumnOriginalValue("languageId"));
		localizationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		localizationImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		localizationImpl.setFeatureId(
			this.<Long>getColumnOriginalValue("featureId"));
		localizationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		localizationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		localizationImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		localizationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		localizationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		localizationImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		localizationImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		localizationImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		localizationImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		localizationImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		localizationImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		localizationImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		localizationImpl.setWorkflowBatchId(
			this.<String>getColumnOriginalValue("workflowBatchId"));
		localizationImpl.setGlobalVersion(
			this.<Long>getColumnOriginalValue("globalVersion"));
		localizationImpl.setImportRequestId(
			this.<Long>getColumnOriginalValue("importRequestId"));

		return localizationImpl;
	}

	@Override
	public int compareTo(Localization localization) {
		long primaryKey = localization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Localization)) {
			return false;
		}

		Localization localization = (Localization)object;

		long primaryKey = localization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Localization> toCacheModel() {
		LocalizationCacheModel localizationCacheModel =
			new LocalizationCacheModel();

		localizationCacheModel.localizationId = getLocalizationId();

		localizationCacheModel.localValue = getLocalValue();

		String localValue = localizationCacheModel.localValue;

		if ((localValue != null) && (localValue.length() == 0)) {
			localizationCacheModel.localValue = null;
		}

		localizationCacheModel.version = getVersion();

		localizationCacheModel.languageId = getLanguageId();

		localizationCacheModel.userName = getUserName();

		String userName = localizationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			localizationCacheModel.userName = null;
		}

		localizationCacheModel.channelId = getChannelId();

		localizationCacheModel.featureId = getFeatureId();

		localizationCacheModel.groupId = getGroupId();

		localizationCacheModel.companyId = getCompanyId();

		localizationCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			localizationCacheModel.createDate = createDate.getTime();
		}
		else {
			localizationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			localizationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			localizationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		localizationCacheModel.status = getStatus();

		localizationCacheModel.statusByUserId = getStatusByUserId();

		localizationCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = localizationCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			localizationCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			localizationCacheModel.statusDate = statusDate.getTime();
		}
		else {
			localizationCacheModel.statusDate = Long.MIN_VALUE;
		}

		localizationCacheModel.uuid_ = getUuid_();

		String uuid_ = localizationCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			localizationCacheModel.uuid_ = null;
		}

		localizationCacheModel.originalEntityId = getOriginalEntityId();

		localizationCacheModel.entityResourceId = getEntityResourceId();

		localizationCacheModel.workflowBatchId = getWorkflowBatchId();

		String workflowBatchId = localizationCacheModel.workflowBatchId;

		if ((workflowBatchId != null) && (workflowBatchId.length() == 0)) {
			localizationCacheModel.workflowBatchId = null;
		}

		localizationCacheModel.globalVersion = getGlobalVersion();

		localizationCacheModel.importRequestId = getImportRequestId();

		return localizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Localization, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Localization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Localization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Localization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Localization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Localization.class, ModelWrapper.class);

	}

	private long _localizationId;
	private String _localValue;
	private long _version;
	private long _languageId;
	private String _userName;
	private long _channelId;
	private long _featureId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private String _workflowBatchId;
	private long _globalVersion;
	private long _importRequestId;

	public <T> T getColumnValue(String columnName) {
		Function<Localization, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Localization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("localizationId", _localizationId);
		_columnOriginalValues.put("localValue", _localValue);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("featureId", _featureId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("workflowBatchId", _workflowBatchId);
		_columnOriginalValues.put("globalVersion", _globalVersion);
		_columnOriginalValues.put("importRequestId", _importRequestId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("localizationId", 1L);

		columnBitmasks.put("localValue", 2L);

		columnBitmasks.put("version", 4L);

		columnBitmasks.put("languageId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("channelId", 32L);

		columnBitmasks.put("featureId", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		columnBitmasks.put("uuid_", 65536L);

		columnBitmasks.put("originalEntityId", 131072L);

		columnBitmasks.put("entityResourceId", 262144L);

		columnBitmasks.put("workflowBatchId", 524288L);

		columnBitmasks.put("globalVersion", 1048576L);

		columnBitmasks.put("importRequestId", 2097152L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Localization _escapedModel;

}