/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.LovDataLocalization;
import com.ejada.telemony.db.model.LovDataLocalizationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LovDataLocalization service. Represents a row in the &quot;LovDataLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LovDataLocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LovDataLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovDataLocalizationImpl
 * @generated
 */
public class LovDataLocalizationModelImpl
	extends BaseModelImpl<LovDataLocalization>
	implements LovDataLocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lov data localization model instance should use the <code>LovDataLocalization</code> interface instead.
	 */
	public static final String TABLE_NAME = "LovDataLocalization";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"lovDataLocalizationId", Types.BIGINT},
		{"id_", Types.BIGINT}, {"languageId", Types.VARCHAR},
		{"recordDescription", Types.VARCHAR}, {"lov_id", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lovDataLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("recordDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lov_id", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LovDataLocalization (mvccVersion LONG default 0 not null,lovDataLocalizationId LONG not null primary key,id_ LONG,languageId VARCHAR(75) null,recordDescription VARCHAR(75) null,lov_id VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table LovDataLocalization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY lovDataLocalization.lovDataLocalizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LovDataLocalization.lovDataLocalizationId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVIDLOCALIZATION_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECORDDESCRIPTION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVDATALOCALIZATIONID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.LovDataLocalization"));

	public LovDataLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lovDataLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLovDataLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lovDataLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LovDataLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return LovDataLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LovDataLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LovDataLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovDataLocalization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LovDataLocalization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LovDataLocalization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LovDataLocalization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LovDataLocalization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LovDataLocalization, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LovDataLocalization, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LovDataLocalization, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LovDataLocalization, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LovDataLocalization, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", LovDataLocalization::getMvccVersion);
			attributeGetterFunctions.put(
				"lovDataLocalizationId",
				LovDataLocalization::getLovDataLocalizationId);
			attributeGetterFunctions.put("id", LovDataLocalization::getId);
			attributeGetterFunctions.put(
				"languageId", LovDataLocalization::getLanguageId);
			attributeGetterFunctions.put(
				"recordDescription", LovDataLocalization::getRecordDescription);
			attributeGetterFunctions.put(
				"lovIdLocalization", LovDataLocalization::getLovIdLocalization);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<LovDataLocalization, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LovDataLocalization, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LovDataLocalization, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<LovDataLocalization, Long>)
					LovDataLocalization::setMvccVersion);
			attributeSetterBiConsumers.put(
				"lovDataLocalizationId",
				(BiConsumer<LovDataLocalization, Long>)
					LovDataLocalization::setLovDataLocalizationId);
			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<LovDataLocalization, Long>)
					LovDataLocalization::setId);
			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<LovDataLocalization, String>)
					LovDataLocalization::setLanguageId);
			attributeSetterBiConsumers.put(
				"recordDescription",
				(BiConsumer<LovDataLocalization, String>)
					LovDataLocalization::setRecordDescription);
			attributeSetterBiConsumers.put(
				"lovIdLocalization",
				(BiConsumer<LovDataLocalization, String>)
					LovDataLocalization::setLovIdLocalization);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getLovDataLocalizationId() {
		return _lovDataLocalizationId;
	}

	@Override
	public void setLovDataLocalizationId(long lovDataLocalizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovDataLocalizationId = lovDataLocalizationId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("id_"));
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@Override
	public String getRecordDescription() {
		if (_recordDescription == null) {
			return "";
		}
		else {
			return _recordDescription;
		}
	}

	@Override
	public void setRecordDescription(String recordDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recordDescription = recordDescription;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRecordDescription() {
		return getColumnOriginalValue("recordDescription");
	}

	@Override
	public String getLovIdLocalization() {
		if (_lovIdLocalization == null) {
			return "";
		}
		else {
			return _lovIdLocalization;
		}
	}

	@Override
	public void setLovIdLocalization(String lovIdLocalization) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovIdLocalization = lovIdLocalization;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLovIdLocalization() {
		return getColumnOriginalValue("lov_id");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LovDataLocalization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LovDataLocalization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LovDataLocalization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LovDataLocalizationImpl lovDataLocalizationImpl =
			new LovDataLocalizationImpl();

		lovDataLocalizationImpl.setMvccVersion(getMvccVersion());
		lovDataLocalizationImpl.setLovDataLocalizationId(
			getLovDataLocalizationId());
		lovDataLocalizationImpl.setId(getId());
		lovDataLocalizationImpl.setLanguageId(getLanguageId());
		lovDataLocalizationImpl.setRecordDescription(getRecordDescription());
		lovDataLocalizationImpl.setLovIdLocalization(getLovIdLocalization());

		lovDataLocalizationImpl.resetOriginalValues();

		return lovDataLocalizationImpl;
	}

	@Override
	public LovDataLocalization cloneWithOriginalValues() {
		LovDataLocalizationImpl lovDataLocalizationImpl =
			new LovDataLocalizationImpl();

		lovDataLocalizationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		lovDataLocalizationImpl.setLovDataLocalizationId(
			this.<Long>getColumnOriginalValue("lovDataLocalizationId"));
		lovDataLocalizationImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		lovDataLocalizationImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		lovDataLocalizationImpl.setRecordDescription(
			this.<String>getColumnOriginalValue("recordDescription"));
		lovDataLocalizationImpl.setLovIdLocalization(
			this.<String>getColumnOriginalValue("lov_id"));

		return lovDataLocalizationImpl;
	}

	@Override
	public int compareTo(LovDataLocalization lovDataLocalization) {
		long primaryKey = lovDataLocalization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LovDataLocalization)) {
			return false;
		}

		LovDataLocalization lovDataLocalization = (LovDataLocalization)object;

		long primaryKey = lovDataLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LovDataLocalization> toCacheModel() {
		LovDataLocalizationCacheModel lovDataLocalizationCacheModel =
			new LovDataLocalizationCacheModel();

		lovDataLocalizationCacheModel.mvccVersion = getMvccVersion();

		lovDataLocalizationCacheModel.lovDataLocalizationId =
			getLovDataLocalizationId();

		lovDataLocalizationCacheModel.id = getId();

		lovDataLocalizationCacheModel.languageId = getLanguageId();

		String languageId = lovDataLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			lovDataLocalizationCacheModel.languageId = null;
		}

		lovDataLocalizationCacheModel.recordDescription =
			getRecordDescription();

		String recordDescription =
			lovDataLocalizationCacheModel.recordDescription;

		if ((recordDescription != null) && (recordDescription.length() == 0)) {
			lovDataLocalizationCacheModel.recordDescription = null;
		}

		lovDataLocalizationCacheModel.lovIdLocalization =
			getLovIdLocalization();

		String lovIdLocalization =
			lovDataLocalizationCacheModel.lovIdLocalization;

		if ((lovIdLocalization != null) && (lovIdLocalization.length() == 0)) {
			lovDataLocalizationCacheModel.lovIdLocalization = null;
		}

		return lovDataLocalizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LovDataLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LovDataLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovDataLocalization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LovDataLocalization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LovDataLocalization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LovDataLocalization.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _lovDataLocalizationId;
	private long _id;
	private String _languageId;
	private String _recordDescription;
	private String _lovIdLocalization;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LovDataLocalization, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LovDataLocalization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"lovDataLocalizationId", _lovDataLocalizationId);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("recordDescription", _recordDescription);
		_columnOriginalValues.put("lov_id", _lovIdLocalization);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");
		attributeNames.put("lov_id", "lovIdLocalization");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("lovDataLocalizationId", 2L);

		columnBitmasks.put("id_", 4L);

		columnBitmasks.put("languageId", 8L);

		columnBitmasks.put("recordDescription", 16L);

		columnBitmasks.put("lov_id", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LovDataLocalization _escapedModel;

}