/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.LovData;
import com.ejada.telemony.db.model.LovDataLocalization;
import com.ejada.telemony.db.model.LovDataModel;
import com.ejada.telemony.db.service.LovDataLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LovData service. Represents a row in the &quot;LOVDATA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LovDataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LovDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovDataImpl
 * @generated
 */
public class LovDataModelImpl
	extends BaseModelImpl<LovData> implements LovDataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lov data model instance should use the <code>LovData</code> interface instead.
	 */
	public static final String TABLE_NAME = "LOVDATA";

	public static final Object[][] TABLE_COLUMNS = {
		{"defaultLanguageId", Types.VARCHAR}, {"id", Types.BIGINT},
		{"lov_id", Types.BIGINT}, {"lov_type", Types.VARCHAR},
		{"record_type_Code", Types.VARCHAR},
		{"record_short_description", Types.VARCHAR}, {"status", Types.INTEGER},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lov_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lov_type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("record_type_Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("record_short_description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LOVDATA (defaultLanguageId VARCHAR(75) null,id LONG not null primary key,lov_id LONG,lov_type VARCHAR(75) null,record_type_Code VARCHAR(75) null,record_short_description VARCHAR(75) null,status INTEGER,originalEntityId LONG,entityResourceId LONG)";

	public static final String TABLE_SQL_DROP = "drop table LOVDATA";

	public static final String ORDER_BY_JPQL = " ORDER BY lovData.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY LOVDATA.id ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVTYPE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECORDSHORTDESCRIPTION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECORDTYPECODE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 64L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.LovData"));

	public LovDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LovData.class;
	}

	@Override
	public String getModelClassName() {
		return LovData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LovData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LovData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovData, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LovData)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LovData, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LovData, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LovData)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LovData, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LovData, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LovData, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LovData, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<LovData, Object>>();

			attributeGetterFunctions.put(
				"defaultLanguageId", LovData::getDefaultLanguageId);
			attributeGetterFunctions.put("id", LovData::getId);
			attributeGetterFunctions.put("lovId", LovData::getLovId);
			attributeGetterFunctions.put("lovType", LovData::getLovType);
			attributeGetterFunctions.put(
				"recordTypeCode", LovData::getRecordTypeCode);
			attributeGetterFunctions.put(
				"recordShortDescription", LovData::getRecordShortDescription);
			attributeGetterFunctions.put("status", LovData::getStatus);
			attributeGetterFunctions.put(
				"originalEntityId", LovData::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", LovData::getEntityResourceId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LovData, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LovData, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<LovData, ?>>();

			attributeSetterBiConsumers.put(
				"defaultLanguageId",
				(BiConsumer<LovData, String>)LovData::setDefaultLanguageId);
			attributeSetterBiConsumers.put(
				"id", (BiConsumer<LovData, Long>)LovData::setId);
			attributeSetterBiConsumers.put(
				"lovId", (BiConsumer<LovData, Long>)LovData::setLovId);
			attributeSetterBiConsumers.put(
				"lovType", (BiConsumer<LovData, String>)LovData::setLovType);
			attributeSetterBiConsumers.put(
				"recordTypeCode",
				(BiConsumer<LovData, String>)LovData::setRecordTypeCode);
			attributeSetterBiConsumers.put(
				"recordShortDescription",
				(BiConsumer<LovData, String>)
					LovData::setRecordShortDescription);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<LovData, Integer>)LovData::setStatus);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<LovData, Long>)LovData::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<LovData, Long>)LovData::setEntityResourceId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<LovDataLocalization> lovDataLocalizations =
			LovDataLocalServiceUtil.getLovDataLocalizations(getPrimaryKey());

		String[] availableLanguageIds = new String[lovDataLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			LovDataLocalization lovDataLocalization = lovDataLocalizations.get(
				i);

			availableLanguageIds[i] = lovDataLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getRecordDescription() {
		return getRecordDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getRecordDescription(String languageId) {
		return getRecordDescription(languageId, true);
	}

	@Override
	public String getRecordDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getRecordDescription(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getRecordDescription(languageId);
	}

	@Override
	public String getRecordDescriptionMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToRecordDescriptionMap(), getDefaultLanguageId(),
			"RecordDescription");
	}

	@Override
	public Map<String, String> getLanguageIdToRecordDescriptionMap() {
		Map<String, String> languageIdToRecordDescriptionMap =
			new HashMap<String, String>();

		List<LovDataLocalization> lovDataLocalizations =
			LovDataLocalServiceUtil.getLovDataLocalizations(getPrimaryKey());

		for (LovDataLocalization lovDataLocalization : lovDataLocalizations) {
			languageIdToRecordDescriptionMap.put(
				lovDataLocalization.getLanguageId(),
				lovDataLocalization.getRecordDescription());
		}

		return languageIdToRecordDescriptionMap;
	}

	private String _getRecordDescription(String languageId) {
		LovDataLocalization lovDataLocalization =
			LovDataLocalServiceUtil.fetchLovDataLocalization(
				getPrimaryKey(), languageId);

		if (lovDataLocalization == null) {
			return "";
		}

		return lovDataLocalization.getRecordDescription();
	}

	@Override
	public String getLovIdLocalization() {
		return getLovIdLocalization(getDefaultLanguageId(), false);
	}

	@Override
	public String getLovIdLocalization(String languageId) {
		return getLovIdLocalization(languageId, true);
	}

	@Override
	public String getLovIdLocalization(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getLovIdLocalization(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getLovIdLocalization(languageId);
	}

	@Override
	public String getLovIdLocalizationMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToLovIdLocalizationMap(), getDefaultLanguageId(),
			"LovIdLocalization");
	}

	@Override
	public Map<String, String> getLanguageIdToLovIdLocalizationMap() {
		Map<String, String> languageIdToLovIdLocalizationMap =
			new HashMap<String, String>();

		List<LovDataLocalization> lovDataLocalizations =
			LovDataLocalServiceUtil.getLovDataLocalizations(getPrimaryKey());

		for (LovDataLocalization lovDataLocalization : lovDataLocalizations) {
			languageIdToLovIdLocalizationMap.put(
				lovDataLocalization.getLanguageId(),
				lovDataLocalization.getLovIdLocalization());
		}

		return languageIdToLovIdLocalizationMap;
	}

	private String _getLovIdLocalization(String languageId) {
		LovDataLocalization lovDataLocalization =
			LovDataLocalServiceUtil.fetchLovDataLocalization(
				getPrimaryKey(), languageId);

		if (lovDataLocalization == null) {
			return "";
		}

		return lovDataLocalization.getLovIdLocalization();
	}

	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultLanguageId = defaultLanguageId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getLovId() {
		return _lovId;
	}

	@Override
	public void setLovId(long lovId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovId = lovId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLovId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("lov_id"));
	}

	@Override
	public String getLovType() {
		if (_lovType == null) {
			return "";
		}
		else {
			return _lovType;
		}
	}

	@Override
	public void setLovType(String lovType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovType = lovType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLovType() {
		return getColumnOriginalValue("lov_type");
	}

	@Override
	public String getRecordTypeCode() {
		if (_recordTypeCode == null) {
			return "";
		}
		else {
			return _recordTypeCode;
		}
	}

	@Override
	public void setRecordTypeCode(String recordTypeCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recordTypeCode = recordTypeCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRecordTypeCode() {
		return getColumnOriginalValue("record_type_Code");
	}

	@Override
	public String getRecordShortDescription() {
		if (_recordShortDescription == null) {
			return "";
		}
		else {
			return _recordShortDescription;
		}
	}

	@Override
	public void setRecordShortDescription(String recordShortDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recordShortDescription = recordShortDescription;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRecordShortDescription() {
		return getColumnOriginalValue("record_short_description");
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LovData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LovData toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LovData>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LovDataImpl lovDataImpl = new LovDataImpl();

		lovDataImpl.setDefaultLanguageId(getDefaultLanguageId());
		lovDataImpl.setId(getId());
		lovDataImpl.setLovId(getLovId());
		lovDataImpl.setLovType(getLovType());
		lovDataImpl.setRecordTypeCode(getRecordTypeCode());
		lovDataImpl.setRecordShortDescription(getRecordShortDescription());
		lovDataImpl.setStatus(getStatus());
		lovDataImpl.setOriginalEntityId(getOriginalEntityId());
		lovDataImpl.setEntityResourceId(getEntityResourceId());

		lovDataImpl.resetOriginalValues();

		return lovDataImpl;
	}

	@Override
	public LovData cloneWithOriginalValues() {
		LovDataImpl lovDataImpl = new LovDataImpl();

		lovDataImpl.setDefaultLanguageId(
			this.<String>getColumnOriginalValue("defaultLanguageId"));
		lovDataImpl.setId(this.<Long>getColumnOriginalValue("id"));
		lovDataImpl.setLovId(this.<Long>getColumnOriginalValue("lov_id"));
		lovDataImpl.setLovType(this.<String>getColumnOriginalValue("lov_type"));
		lovDataImpl.setRecordTypeCode(
			this.<String>getColumnOriginalValue("record_type_Code"));
		lovDataImpl.setRecordShortDescription(
			this.<String>getColumnOriginalValue("record_short_description"));
		lovDataImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		lovDataImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		lovDataImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));

		return lovDataImpl;
	}

	@Override
	public int compareTo(LovData lovData) {
		long primaryKey = lovData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LovData)) {
			return false;
		}

		LovData lovData = (LovData)object;

		long primaryKey = lovData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LovData> toCacheModel() {
		LovDataCacheModel lovDataCacheModel = new LovDataCacheModel();

		lovDataCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = lovDataCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			lovDataCacheModel.defaultLanguageId = null;
		}

		lovDataCacheModel.id = getId();

		lovDataCacheModel.lovId = getLovId();

		lovDataCacheModel.lovType = getLovType();

		String lovType = lovDataCacheModel.lovType;

		if ((lovType != null) && (lovType.length() == 0)) {
			lovDataCacheModel.lovType = null;
		}

		lovDataCacheModel.recordTypeCode = getRecordTypeCode();

		String recordTypeCode = lovDataCacheModel.recordTypeCode;

		if ((recordTypeCode != null) && (recordTypeCode.length() == 0)) {
			lovDataCacheModel.recordTypeCode = null;
		}

		lovDataCacheModel.recordShortDescription = getRecordShortDescription();

		String recordShortDescription =
			lovDataCacheModel.recordShortDescription;

		if ((recordShortDescription != null) &&
			(recordShortDescription.length() == 0)) {

			lovDataCacheModel.recordShortDescription = null;
		}

		lovDataCacheModel.status = getStatus();

		lovDataCacheModel.originalEntityId = getOriginalEntityId();

		lovDataCacheModel.entityResourceId = getEntityResourceId();

		return lovDataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LovData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LovData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LovData)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LovData>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LovData.class, ModelWrapper.class);

	}

	private String _defaultLanguageId;
	private long _id;
	private long _lovId;
	private String _lovType;
	private String _recordTypeCode;
	private String _recordShortDescription;
	private int _status;
	private long _originalEntityId;
	private long _entityResourceId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LovData, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LovData)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("defaultLanguageId", _defaultLanguageId);
		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("lov_id", _lovId);
		_columnOriginalValues.put("lov_type", _lovType);
		_columnOriginalValues.put("record_type_Code", _recordTypeCode);
		_columnOriginalValues.put(
			"record_short_description", _recordShortDescription);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("lov_id", "lovId");
		attributeNames.put("lov_type", "lovType");
		attributeNames.put("record_type_Code", "recordTypeCode");
		attributeNames.put(
			"record_short_description", "recordShortDescription");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("defaultLanguageId", 1L);

		columnBitmasks.put("id", 2L);

		columnBitmasks.put("lov_id", 4L);

		columnBitmasks.put("lov_type", 8L);

		columnBitmasks.put("record_type_Code", 16L);

		columnBitmasks.put("record_short_description", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("originalEntityId", 128L);

		columnBitmasks.put("entityResourceId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LovData _escapedModel;

}