/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.LovData;
import com.ejada.telemony.db.service.LovDataLocalServiceUtil;

/**
 * The extended model base implementation for the LovData service. Represents a row in the &quot;LOVDATA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LovDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovDataImpl
 * @see LovData
 * @generated
 */
public abstract class LovDataBaseImpl
	extends LovDataModelImpl implements LovData {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lov data model instance should use the <code>LovData</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LovDataLocalServiceUtil.addLovData(this);
		}
		else {
			LovDataLocalServiceUtil.updateLovData(this);
		}
	}

}