/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Lovs;
import com.ejada.telemony.db.model.LovsLocalization;
import com.ejada.telemony.db.model.LovsModel;
import com.ejada.telemony.db.service.LovsLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Lovs service. Represents a row in the &quot;LOVS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LovsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LovsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovsImpl
 * @generated
 */
public class LovsModelImpl extends BaseModelImpl<Lovs> implements LovsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lovs model instance should use the <code>Lovs</code> interface instead.
	 */
	public static final String TABLE_NAME = "LOVS";

	public static final Object[][] TABLE_COLUMNS = {
		{"defaultLanguageId", Types.VARCHAR}, {"id", Types.BIGINT},
		{"code", Types.VARCHAR}, {"channelId", Types.BIGINT},
		{"eventCode", Types.VARCHAR}, {"count", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"version", Types.INTEGER},
		{"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("eventCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("count", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LOVS (defaultLanguageId VARCHAR(75) null,id LONG not null primary key,code VARCHAR(75) null,channelId LONG,eventCode VARCHAR(75) null,count INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LOVS";

	public static final String ORDER_BY_JPQL = " ORDER BY lovs.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY LOVS.id ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Lovs"));

	public LovsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lovs.class;
	}

	@Override
	public String getModelClassName() {
		return Lovs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Lovs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Lovs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lovs, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Lovs)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Lovs, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Lovs, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Lovs)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Lovs, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Lovs, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Lovs, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Lovs, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Lovs, Object>>();

			attributeGetterFunctions.put(
				"defaultLanguageId", Lovs::getDefaultLanguageId);
			attributeGetterFunctions.put("id", Lovs::getId);
			attributeGetterFunctions.put("code", Lovs::getCode);
			attributeGetterFunctions.put("channelId", Lovs::getChannelId);
			attributeGetterFunctions.put("eventCode", Lovs::getEventCode);
			attributeGetterFunctions.put("count", Lovs::getCount);
			attributeGetterFunctions.put("groupId", Lovs::getGroupId);
			attributeGetterFunctions.put("companyId", Lovs::getCompanyId);
			attributeGetterFunctions.put("userId", Lovs::getUserId);
			attributeGetterFunctions.put("userName", Lovs::getUserName);
			attributeGetterFunctions.put("createDate", Lovs::getCreateDate);
			attributeGetterFunctions.put("modifiedDate", Lovs::getModifiedDate);
			attributeGetterFunctions.put("status", Lovs::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Lovs::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Lovs::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Lovs::getStatusDate);
			attributeGetterFunctions.put("uuid_", Lovs::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Lovs::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Lovs::getEntityResourceId);
			attributeGetterFunctions.put("version", Lovs::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Lovs::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Lovs, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Lovs, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Lovs, ?>>();

			attributeSetterBiConsumers.put(
				"defaultLanguageId",
				(BiConsumer<Lovs, String>)Lovs::setDefaultLanguageId);
			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Lovs, Long>)Lovs::setId);
			attributeSetterBiConsumers.put(
				"code", (BiConsumer<Lovs, String>)Lovs::setCode);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Lovs, Long>)Lovs::setChannelId);
			attributeSetterBiConsumers.put(
				"eventCode", (BiConsumer<Lovs, String>)Lovs::setEventCode);
			attributeSetterBiConsumers.put(
				"count", (BiConsumer<Lovs, Integer>)Lovs::setCount);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Lovs, Long>)Lovs::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Lovs, Long>)Lovs::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Lovs, Long>)Lovs::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Lovs, String>)Lovs::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Lovs, Date>)Lovs::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate", (BiConsumer<Lovs, Date>)Lovs::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Lovs, Integer>)Lovs::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Lovs, Long>)Lovs::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Lovs, String>)Lovs::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate", (BiConsumer<Lovs, Date>)Lovs::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Lovs, String>)Lovs::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Lovs, Long>)Lovs::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Lovs, Long>)Lovs::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Lovs, Integer>)Lovs::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Lovs, String>)Lovs::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<LovsLocalization> lovsLocalizations =
			LovsLocalServiceUtil.getLovsLocalizations(getPrimaryKey());

		String[] availableLanguageIds = new String[lovsLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			LovsLocalization lovsLocalization = lovsLocalizations.get(i);

			availableLanguageIds[i] = lovsLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getName() {
		return getName(getDefaultLanguageId(), false);
	}

	@Override
	public String getName(String languageId) {
		return getName(languageId, true);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getName(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getName(languageId);
	}

	@Override
	public String getNameMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToNameMap(), getDefaultLanguageId(), "Name");
	}

	@Override
	public Map<String, String> getLanguageIdToNameMap() {
		Map<String, String> languageIdToNameMap = new HashMap<String, String>();

		List<LovsLocalization> lovsLocalizations =
			LovsLocalServiceUtil.getLovsLocalizations(getPrimaryKey());

		for (LovsLocalization lovsLocalization : lovsLocalizations) {
			languageIdToNameMap.put(
				lovsLocalization.getLanguageId(), lovsLocalization.getName());
		}

		return languageIdToNameMap;
	}

	private String _getName(String languageId) {
		LovsLocalization lovsLocalization =
			LovsLocalServiceUtil.fetchLovsLocalization(
				getPrimaryKey(), languageId);

		if (lovsLocalization == null) {
			return "";
		}

		return lovsLocalization.getName();
	}

	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultLanguageId = defaultLanguageId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("id"));
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code");
	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@Override
	public String getEventCode() {
		if (_eventCode == null) {
			return "";
		}
		else {
			return _eventCode;
		}
	}

	@Override
	public void setEventCode(String eventCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventCode = eventCode;
	}

	@Override
	public int getCount() {
		return _count;
	}

	@Override
	public void setCount(int count) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_count = count;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Lovs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Lovs toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Lovs>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LovsImpl lovsImpl = new LovsImpl();

		lovsImpl.setDefaultLanguageId(getDefaultLanguageId());
		lovsImpl.setId(getId());
		lovsImpl.setCode(getCode());
		lovsImpl.setChannelId(getChannelId());
		lovsImpl.setEventCode(getEventCode());
		lovsImpl.setCount(getCount());
		lovsImpl.setGroupId(getGroupId());
		lovsImpl.setCompanyId(getCompanyId());
		lovsImpl.setUserId(getUserId());
		lovsImpl.setUserName(getUserName());
		lovsImpl.setCreateDate(getCreateDate());
		lovsImpl.setModifiedDate(getModifiedDate());
		lovsImpl.setStatus(getStatus());
		lovsImpl.setStatusByUserId(getStatusByUserId());
		lovsImpl.setStatusByUserName(getStatusByUserName());
		lovsImpl.setStatusDate(getStatusDate());
		lovsImpl.setUuid_(getUuid_());
		lovsImpl.setOriginalEntityId(getOriginalEntityId());
		lovsImpl.setEntityResourceId(getEntityResourceId());
		lovsImpl.setVersion(getVersion());
		lovsImpl.setWorkflowAction(getWorkflowAction());

		lovsImpl.resetOriginalValues();

		return lovsImpl;
	}

	@Override
	public Lovs cloneWithOriginalValues() {
		LovsImpl lovsImpl = new LovsImpl();

		lovsImpl.setDefaultLanguageId(
			this.<String>getColumnOriginalValue("defaultLanguageId"));
		lovsImpl.setId(this.<Long>getColumnOriginalValue("id"));
		lovsImpl.setCode(this.<String>getColumnOriginalValue("code"));
		lovsImpl.setChannelId(this.<Long>getColumnOriginalValue("channelId"));
		lovsImpl.setEventCode(this.<String>getColumnOriginalValue("eventCode"));
		lovsImpl.setCount(this.<Integer>getColumnOriginalValue("count"));
		lovsImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		lovsImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		lovsImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		lovsImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		lovsImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		lovsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		lovsImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		lovsImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		lovsImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		lovsImpl.setStatusDate(this.<Date>getColumnOriginalValue("statusDate"));
		lovsImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		lovsImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		lovsImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		lovsImpl.setVersion(this.<Integer>getColumnOriginalValue("version"));
		lovsImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return lovsImpl;
	}

	@Override
	public int compareTo(Lovs lovs) {
		long primaryKey = lovs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Lovs)) {
			return false;
		}

		Lovs lovs = (Lovs)object;

		long primaryKey = lovs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Lovs> toCacheModel() {
		LovsCacheModel lovsCacheModel = new LovsCacheModel();

		lovsCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = lovsCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			lovsCacheModel.defaultLanguageId = null;
		}

		lovsCacheModel.id = getId();

		lovsCacheModel.code = getCode();

		String code = lovsCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			lovsCacheModel.code = null;
		}

		lovsCacheModel.channelId = getChannelId();

		lovsCacheModel.eventCode = getEventCode();

		String eventCode = lovsCacheModel.eventCode;

		if ((eventCode != null) && (eventCode.length() == 0)) {
			lovsCacheModel.eventCode = null;
		}

		lovsCacheModel.count = getCount();

		lovsCacheModel.groupId = getGroupId();

		lovsCacheModel.companyId = getCompanyId();

		lovsCacheModel.userId = getUserId();

		lovsCacheModel.userName = getUserName();

		String userName = lovsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			lovsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			lovsCacheModel.createDate = createDate.getTime();
		}
		else {
			lovsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			lovsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			lovsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		lovsCacheModel.status = getStatus();

		lovsCacheModel.statusByUserId = getStatusByUserId();

		lovsCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = lovsCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			lovsCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			lovsCacheModel.statusDate = statusDate.getTime();
		}
		else {
			lovsCacheModel.statusDate = Long.MIN_VALUE;
		}

		lovsCacheModel.uuid_ = getUuid_();

		String uuid_ = lovsCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			lovsCacheModel.uuid_ = null;
		}

		lovsCacheModel.originalEntityId = getOriginalEntityId();

		lovsCacheModel.entityResourceId = getEntityResourceId();

		lovsCacheModel.version = getVersion();

		lovsCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = lovsCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			lovsCacheModel.workflowAction = null;
		}

		return lovsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Lovs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Lovs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lovs, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Lovs)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Lovs>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Lovs.class, ModelWrapper.class);

	}

	private String _defaultLanguageId;
	private long _id;
	private String _code;
	private long _channelId;
	private String _eventCode;
	private int _count;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<Lovs, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Lovs)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("defaultLanguageId", _defaultLanguageId);
		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("eventCode", _eventCode);
		_columnOriginalValues.put("count", _count);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("defaultLanguageId", 1L);

		columnBitmasks.put("id", 2L);

		columnBitmasks.put("code", 4L);

		columnBitmasks.put("channelId", 8L);

		columnBitmasks.put("eventCode", 16L);

		columnBitmasks.put("count", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		columnBitmasks.put("uuid_", 65536L);

		columnBitmasks.put("originalEntityId", 131072L);

		columnBitmasks.put("entityResourceId", 262144L);

		columnBitmasks.put("version", 524288L);

		columnBitmasks.put("workflowAction", 1048576L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Lovs _escapedModel;

}