/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.LovsLocalization;
import com.ejada.telemony.db.model.LovsLocalizationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LovsLocalization service. Represents a row in the &quot;LovsLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LovsLocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LovsLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LovsLocalizationImpl
 * @generated
 */
public class LovsLocalizationModelImpl
	extends BaseModelImpl<LovsLocalization> implements LovsLocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lovs localization model instance should use the <code>LovsLocalization</code> interface instead.
	 */
	public static final String TABLE_NAME = "LovsLocalization";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"lovsLocalizationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"id_", Types.BIGINT},
		{"languageId", Types.VARCHAR}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lovsLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LovsLocalization (mvccVersion LONG default 0 not null,lovsLocalizationId LONG not null primary key,companyId LONG,id_ LONG,languageId VARCHAR(75) null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LovsLocalization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY lovsLocalization.lovsLocalizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LovsLocalization.lovsLocalizationId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOVSLOCALIZATIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.LovsLocalization"));

	public LovsLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lovsLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLovsLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lovsLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LovsLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return LovsLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LovsLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LovsLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovsLocalization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LovsLocalization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LovsLocalization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LovsLocalization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LovsLocalization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LovsLocalization, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LovsLocalization, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LovsLocalization, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LovsLocalization, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LovsLocalization, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", LovsLocalization::getMvccVersion);
			attributeGetterFunctions.put(
				"lovsLocalizationId", LovsLocalization::getLovsLocalizationId);
			attributeGetterFunctions.put(
				"companyId", LovsLocalization::getCompanyId);
			attributeGetterFunctions.put("id", LovsLocalization::getId);
			attributeGetterFunctions.put(
				"languageId", LovsLocalization::getLanguageId);
			attributeGetterFunctions.put("name", LovsLocalization::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LovsLocalization, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LovsLocalization, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LovsLocalization, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<LovsLocalization, Long>)
					LovsLocalization::setMvccVersion);
			attributeSetterBiConsumers.put(
				"lovsLocalizationId",
				(BiConsumer<LovsLocalization, Long>)
					LovsLocalization::setLovsLocalizationId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LovsLocalization, Long>)
					LovsLocalization::setCompanyId);
			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<LovsLocalization, Long>)LovsLocalization::setId);
			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<LovsLocalization, String>)
					LovsLocalization::setLanguageId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<LovsLocalization, String>)
					LovsLocalization::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getLovsLocalizationId() {
		return _lovsLocalizationId;
	}

	@Override
	public void setLovsLocalizationId(long lovsLocalizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lovsLocalizationId = lovsLocalizationId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("id_"));
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LovsLocalization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LovsLocalization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LovsLocalization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LovsLocalizationImpl lovsLocalizationImpl = new LovsLocalizationImpl();

		lovsLocalizationImpl.setMvccVersion(getMvccVersion());
		lovsLocalizationImpl.setLovsLocalizationId(getLovsLocalizationId());
		lovsLocalizationImpl.setCompanyId(getCompanyId());
		lovsLocalizationImpl.setId(getId());
		lovsLocalizationImpl.setLanguageId(getLanguageId());
		lovsLocalizationImpl.setName(getName());

		lovsLocalizationImpl.resetOriginalValues();

		return lovsLocalizationImpl;
	}

	@Override
	public LovsLocalization cloneWithOriginalValues() {
		LovsLocalizationImpl lovsLocalizationImpl = new LovsLocalizationImpl();

		lovsLocalizationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		lovsLocalizationImpl.setLovsLocalizationId(
			this.<Long>getColumnOriginalValue("lovsLocalizationId"));
		lovsLocalizationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		lovsLocalizationImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		lovsLocalizationImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		lovsLocalizationImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return lovsLocalizationImpl;
	}

	@Override
	public int compareTo(LovsLocalization lovsLocalization) {
		long primaryKey = lovsLocalization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LovsLocalization)) {
			return false;
		}

		LovsLocalization lovsLocalization = (LovsLocalization)object;

		long primaryKey = lovsLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LovsLocalization> toCacheModel() {
		LovsLocalizationCacheModel lovsLocalizationCacheModel =
			new LovsLocalizationCacheModel();

		lovsLocalizationCacheModel.mvccVersion = getMvccVersion();

		lovsLocalizationCacheModel.lovsLocalizationId = getLovsLocalizationId();

		lovsLocalizationCacheModel.companyId = getCompanyId();

		lovsLocalizationCacheModel.id = getId();

		lovsLocalizationCacheModel.languageId = getLanguageId();

		String languageId = lovsLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			lovsLocalizationCacheModel.languageId = null;
		}

		lovsLocalizationCacheModel.name = getName();

		String name = lovsLocalizationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			lovsLocalizationCacheModel.name = null;
		}

		return lovsLocalizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LovsLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LovsLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LovsLocalization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LovsLocalization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LovsLocalization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LovsLocalization.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _lovsLocalizationId;
	private long _companyId;
	private long _id;
	private String _languageId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LovsLocalization, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LovsLocalization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("lovsLocalizationId", _lovsLocalizationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("name", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("lovsLocalizationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("id_", 8L);

		columnBitmasks.put("languageId", 16L);

		columnBitmasks.put("name", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LovsLocalization _escapedModel;

}