/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Persona;
import com.ejada.telemony.db.model.PersonaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Persona service. Represents a row in the &quot;PERSONA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PersonaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersonaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersonaImpl
 * @generated
 */
@JSON(strict = true)
public class PersonaModelImpl
	extends BaseModelImpl<Persona> implements PersonaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persona model instance should use the <code>Persona</code> interface instead.
	 */
	public static final String TABLE_NAME = "PERSONA";

	public static final Object[][] TABLE_COLUMNS = {
		{"personaId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"darkThemeId", Types.BIGINT}, {"lightThemeId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"startAge", Types.INTEGER},
		{"endAge", Types.INTEGER}, {"nationality", Types.VARCHAR},
		{"customerSegment", Types.VARCHAR}, {"personaStatus", Types.VARCHAR},
		{"sector", Types.VARCHAR}, {"minIncome", Types.INTEGER},
		{"maxIncome", Types.INTEGER}, {"description", Types.VARCHAR},
		{"gender", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"dateFrom", Types.TIMESTAMP}, {"dateTo", Types.TIMESTAMP},
		{"defaultPersona", Types.BOOLEAN}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"uuid_", Types.VARCHAR},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT},
		{"version", Types.INTEGER}, {"workflowAction", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("personaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("darkThemeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lightThemeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startAge", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("endAge", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customerSegment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("personaStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sector", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("minIncome", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("maxIncome", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dateFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateTo", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("defaultPersona", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PERSONA (personaId LONG not null primary key,channelId LONG,darkThemeId LONG,lightThemeId LONG,name VARCHAR(75) null,startAge INTEGER,endAge INTEGER,nationality VARCHAR(75) null,customerSegment VARCHAR(75) null,personaStatus VARCHAR(75) null,sector VARCHAR(75) null,minIncome INTEGER,maxIncome INTEGER,description VARCHAR(75) null,gender VARCHAR(75) null,priority INTEGER,dateFrom DATE null,dateTo DATE null,defaultPersona BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PERSONA";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persona.personaId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY PERSONA.personaId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DARKTHEMEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEFAULTPERSONA_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LIGHTTHEMEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERSONAID_COLUMN_BITMASK = 64L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Persona"));

	public PersonaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _personaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPersonaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _personaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Persona.class;
	}

	@Override
	public String getModelClassName() {
		return Persona.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Persona, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Persona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Persona, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Persona)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Persona, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Persona, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Persona)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Persona, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Persona, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Persona, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Persona, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Persona, Object>>();

			attributeGetterFunctions.put("personaId", Persona::getPersonaId);
			attributeGetterFunctions.put("channelId", Persona::getChannelId);
			attributeGetterFunctions.put(
				"darkThemeId", Persona::getDarkThemeId);
			attributeGetterFunctions.put(
				"lightThemeId", Persona::getLightThemeId);
			attributeGetterFunctions.put("name", Persona::getName);
			attributeGetterFunctions.put("startAge", Persona::getStartAge);
			attributeGetterFunctions.put("endAge", Persona::getEndAge);
			attributeGetterFunctions.put(
				"nationality", Persona::getNationality);
			attributeGetterFunctions.put(
				"customerSegment", Persona::getCustomerSegment);
			attributeGetterFunctions.put(
				"personaStatus", Persona::getPersonaStatus);
			attributeGetterFunctions.put("sector", Persona::getSector);
			attributeGetterFunctions.put("minIncome", Persona::getMinIncome);
			attributeGetterFunctions.put("maxIncome", Persona::getMaxIncome);
			attributeGetterFunctions.put(
				"description", Persona::getDescription);
			attributeGetterFunctions.put("gender", Persona::getGender);
			attributeGetterFunctions.put("priority", Persona::getPriority);
			attributeGetterFunctions.put("dateFrom", Persona::getDateFrom);
			attributeGetterFunctions.put("dateTo", Persona::getDateTo);
			attributeGetterFunctions.put(
				"defaultPersona", Persona::getDefaultPersona);
			attributeGetterFunctions.put("groupId", Persona::getGroupId);
			attributeGetterFunctions.put("companyId", Persona::getCompanyId);
			attributeGetterFunctions.put("userId", Persona::getUserId);
			attributeGetterFunctions.put("userName", Persona::getUserName);
			attributeGetterFunctions.put("createDate", Persona::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Persona::getModifiedDate);
			attributeGetterFunctions.put("status", Persona::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Persona::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Persona::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Persona::getStatusDate);
			attributeGetterFunctions.put("uuid_", Persona::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Persona::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Persona::getEntityResourceId);
			attributeGetterFunctions.put("version", Persona::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Persona::getWorkflowAction);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Persona, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Persona, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Persona, ?>>();

			attributeSetterBiConsumers.put(
				"personaId", (BiConsumer<Persona, Long>)Persona::setPersonaId);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Persona, Long>)Persona::setChannelId);
			attributeSetterBiConsumers.put(
				"darkThemeId",
				(BiConsumer<Persona, Long>)Persona::setDarkThemeId);
			attributeSetterBiConsumers.put(
				"lightThemeId",
				(BiConsumer<Persona, Long>)Persona::setLightThemeId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Persona, String>)Persona::setName);
			attributeSetterBiConsumers.put(
				"startAge", (BiConsumer<Persona, Integer>)Persona::setStartAge);
			attributeSetterBiConsumers.put(
				"endAge", (BiConsumer<Persona, Integer>)Persona::setEndAge);
			attributeSetterBiConsumers.put(
				"nationality",
				(BiConsumer<Persona, String>)Persona::setNationality);
			attributeSetterBiConsumers.put(
				"customerSegment",
				(BiConsumer<Persona, String>)Persona::setCustomerSegment);
			attributeSetterBiConsumers.put(
				"personaStatus",
				(BiConsumer<Persona, String>)Persona::setPersonaStatus);
			attributeSetterBiConsumers.put(
				"sector", (BiConsumer<Persona, String>)Persona::setSector);
			attributeSetterBiConsumers.put(
				"minIncome",
				(BiConsumer<Persona, Integer>)Persona::setMinIncome);
			attributeSetterBiConsumers.put(
				"maxIncome",
				(BiConsumer<Persona, Integer>)Persona::setMaxIncome);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<Persona, String>)Persona::setDescription);
			attributeSetterBiConsumers.put(
				"gender", (BiConsumer<Persona, String>)Persona::setGender);
			attributeSetterBiConsumers.put(
				"priority", (BiConsumer<Persona, Integer>)Persona::setPriority);
			attributeSetterBiConsumers.put(
				"dateFrom", (BiConsumer<Persona, Date>)Persona::setDateFrom);
			attributeSetterBiConsumers.put(
				"dateTo", (BiConsumer<Persona, Date>)Persona::setDateTo);
			attributeSetterBiConsumers.put(
				"defaultPersona",
				(BiConsumer<Persona, Boolean>)Persona::setDefaultPersona);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Persona, Long>)Persona::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Persona, Long>)Persona::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Persona, Long>)Persona::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Persona, String>)Persona::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Persona, Date>)Persona::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Persona, Date>)Persona::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Persona, Integer>)Persona::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Persona, Long>)Persona::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Persona, String>)Persona::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Persona, Date>)Persona::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Persona, String>)Persona::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Persona, Long>)Persona::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Persona, Long>)Persona::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Persona, Integer>)Persona::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Persona, String>)Persona::setWorkflowAction);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getPersonaId() {
		return _personaId;
	}

	@Override
	public void setPersonaId(long personaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_personaId = personaId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public Long getDarkThemeId() {
		return _darkThemeId;
	}

	@Override
	public void setDarkThemeId(Long darkThemeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_darkThemeId = darkThemeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalDarkThemeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("darkThemeId"));
	}

	@JSON
	@Override
	public Long getLightThemeId() {
		return _lightThemeId;
	}

	@Override
	public void setLightThemeId(Long lightThemeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lightThemeId = lightThemeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalLightThemeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("lightThemeId"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public int getStartAge() {
		return _startAge;
	}

	@Override
	public void setStartAge(int startAge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startAge = startAge;
	}

	@JSON
	@Override
	public int getEndAge() {
		return _endAge;
	}

	@Override
	public void setEndAge(int endAge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endAge = endAge;
	}

	@JSON
	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationality = nationality;
	}

	@JSON
	@Override
	public String getCustomerSegment() {
		if (_customerSegment == null) {
			return "";
		}
		else {
			return _customerSegment;
		}
	}

	@Override
	public void setCustomerSegment(String customerSegment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerSegment = customerSegment;
	}

	@JSON
	@Override
	public String getPersonaStatus() {
		if (_personaStatus == null) {
			return "";
		}
		else {
			return _personaStatus;
		}
	}

	@Override
	public void setPersonaStatus(String personaStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_personaStatus = personaStatus;
	}

	@JSON
	@Override
	public String getSector() {
		if (_sector == null) {
			return "";
		}
		else {
			return _sector;
		}
	}

	@Override
	public void setSector(String sector) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sector = sector;
	}

	@JSON
	@Override
	public int getMinIncome() {
		return _minIncome;
	}

	@Override
	public void setMinIncome(int minIncome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_minIncome = minIncome;
	}

	@JSON
	@Override
	public int getMaxIncome() {
		return _maxIncome;
	}

	@Override
	public void setMaxIncome(int maxIncome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maxIncome = maxIncome;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getGender() {
		if (_gender == null) {
			return "";
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public Date getDateFrom() {
		return _dateFrom;
	}

	@Override
	public void setDateFrom(Date dateFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateFrom = dateFrom;
	}

	@JSON
	@Override
	public Date getDateTo() {
		return _dateTo;
	}

	@Override
	public void setDateTo(Date dateTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateTo = dateTo;
	}

	@JSON
	@Override
	public boolean getDefaultPersona() {
		return _defaultPersona;
	}

	@JSON
	@Override
	public boolean isDefaultPersona() {
		return _defaultPersona;
	}

	@Override
	public void setDefaultPersona(boolean defaultPersona) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultPersona = defaultPersona;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDefaultPersona() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("defaultPersona"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Persona.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Persona toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Persona>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersonaImpl personaImpl = new PersonaImpl();

		personaImpl.setPersonaId(getPersonaId());
		personaImpl.setChannelId(getChannelId());
		personaImpl.setDarkThemeId(getDarkThemeId());
		personaImpl.setLightThemeId(getLightThemeId());
		personaImpl.setName(getName());
		personaImpl.setStartAge(getStartAge());
		personaImpl.setEndAge(getEndAge());
		personaImpl.setNationality(getNationality());
		personaImpl.setCustomerSegment(getCustomerSegment());
		personaImpl.setPersonaStatus(getPersonaStatus());
		personaImpl.setSector(getSector());
		personaImpl.setMinIncome(getMinIncome());
		personaImpl.setMaxIncome(getMaxIncome());
		personaImpl.setDescription(getDescription());
		personaImpl.setGender(getGender());
		personaImpl.setPriority(getPriority());
		personaImpl.setDateFrom(getDateFrom());
		personaImpl.setDateTo(getDateTo());
		personaImpl.setDefaultPersona(isDefaultPersona());
		personaImpl.setGroupId(getGroupId());
		personaImpl.setCompanyId(getCompanyId());
		personaImpl.setUserId(getUserId());
		personaImpl.setUserName(getUserName());
		personaImpl.setCreateDate(getCreateDate());
		personaImpl.setModifiedDate(getModifiedDate());
		personaImpl.setStatus(getStatus());
		personaImpl.setStatusByUserId(getStatusByUserId());
		personaImpl.setStatusByUserName(getStatusByUserName());
		personaImpl.setStatusDate(getStatusDate());
		personaImpl.setUuid_(getUuid_());
		personaImpl.setOriginalEntityId(getOriginalEntityId());
		personaImpl.setEntityResourceId(getEntityResourceId());
		personaImpl.setVersion(getVersion());
		personaImpl.setWorkflowAction(getWorkflowAction());

		personaImpl.resetOriginalValues();

		return personaImpl;
	}

	@Override
	public Persona cloneWithOriginalValues() {
		PersonaImpl personaImpl = new PersonaImpl();

		personaImpl.setPersonaId(
			this.<Long>getColumnOriginalValue("personaId"));
		personaImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		personaImpl.setDarkThemeId(
			this.<Long>getColumnOriginalValue("darkThemeId"));
		personaImpl.setLightThemeId(
			this.<Long>getColumnOriginalValue("lightThemeId"));
		personaImpl.setName(this.<String>getColumnOriginalValue("name"));
		personaImpl.setStartAge(
			this.<Integer>getColumnOriginalValue("startAge"));
		personaImpl.setEndAge(this.<Integer>getColumnOriginalValue("endAge"));
		personaImpl.setNationality(
			this.<String>getColumnOriginalValue("nationality"));
		personaImpl.setCustomerSegment(
			this.<String>getColumnOriginalValue("customerSegment"));
		personaImpl.setPersonaStatus(
			this.<String>getColumnOriginalValue("personaStatus"));
		personaImpl.setSector(this.<String>getColumnOriginalValue("sector"));
		personaImpl.setMinIncome(
			this.<Integer>getColumnOriginalValue("minIncome"));
		personaImpl.setMaxIncome(
			this.<Integer>getColumnOriginalValue("maxIncome"));
		personaImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		personaImpl.setGender(this.<String>getColumnOriginalValue("gender"));
		personaImpl.setPriority(
			this.<Integer>getColumnOriginalValue("priority"));
		personaImpl.setDateFrom(this.<Date>getColumnOriginalValue("dateFrom"));
		personaImpl.setDateTo(this.<Date>getColumnOriginalValue("dateTo"));
		personaImpl.setDefaultPersona(
			this.<Boolean>getColumnOriginalValue("defaultPersona"));
		personaImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		personaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		personaImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		personaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		personaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		personaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		personaImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		personaImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		personaImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		personaImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		personaImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		personaImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		personaImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		personaImpl.setVersion(this.<Integer>getColumnOriginalValue("version"));
		personaImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));

		return personaImpl;
	}

	@Override
	public int compareTo(Persona persona) {
		long primaryKey = persona.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Persona)) {
			return false;
		}

		Persona persona = (Persona)object;

		long primaryKey = persona.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Persona> toCacheModel() {
		PersonaCacheModel personaCacheModel = new PersonaCacheModel();

		personaCacheModel.personaId = getPersonaId();

		personaCacheModel.channelId = getChannelId();

		Long darkThemeId = getDarkThemeId();

		if (darkThemeId != null) {
			personaCacheModel.darkThemeId = darkThemeId;
		}

		Long lightThemeId = getLightThemeId();

		if (lightThemeId != null) {
			personaCacheModel.lightThemeId = lightThemeId;
		}

		personaCacheModel.name = getName();

		String name = personaCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			personaCacheModel.name = null;
		}

		personaCacheModel.startAge = getStartAge();

		personaCacheModel.endAge = getEndAge();

		personaCacheModel.nationality = getNationality();

		String nationality = personaCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			personaCacheModel.nationality = null;
		}

		personaCacheModel.customerSegment = getCustomerSegment();

		String customerSegment = personaCacheModel.customerSegment;

		if ((customerSegment != null) && (customerSegment.length() == 0)) {
			personaCacheModel.customerSegment = null;
		}

		personaCacheModel.personaStatus = getPersonaStatus();

		String personaStatus = personaCacheModel.personaStatus;

		if ((personaStatus != null) && (personaStatus.length() == 0)) {
			personaCacheModel.personaStatus = null;
		}

		personaCacheModel.sector = getSector();

		String sector = personaCacheModel.sector;

		if ((sector != null) && (sector.length() == 0)) {
			personaCacheModel.sector = null;
		}

		personaCacheModel.minIncome = getMinIncome();

		personaCacheModel.maxIncome = getMaxIncome();

		personaCacheModel.description = getDescription();

		String description = personaCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			personaCacheModel.description = null;
		}

		personaCacheModel.gender = getGender();

		String gender = personaCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			personaCacheModel.gender = null;
		}

		personaCacheModel.priority = getPriority();

		Date dateFrom = getDateFrom();

		if (dateFrom != null) {
			personaCacheModel.dateFrom = dateFrom.getTime();
		}
		else {
			personaCacheModel.dateFrom = Long.MIN_VALUE;
		}

		Date dateTo = getDateTo();

		if (dateTo != null) {
			personaCacheModel.dateTo = dateTo.getTime();
		}
		else {
			personaCacheModel.dateTo = Long.MIN_VALUE;
		}

		personaCacheModel.defaultPersona = isDefaultPersona();

		personaCacheModel.groupId = getGroupId();

		personaCacheModel.companyId = getCompanyId();

		personaCacheModel.userId = getUserId();

		personaCacheModel.userName = getUserName();

		String userName = personaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			personaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			personaCacheModel.createDate = createDate.getTime();
		}
		else {
			personaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			personaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			personaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		personaCacheModel.status = getStatus();

		personaCacheModel.statusByUserId = getStatusByUserId();

		personaCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = personaCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			personaCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			personaCacheModel.statusDate = statusDate.getTime();
		}
		else {
			personaCacheModel.statusDate = Long.MIN_VALUE;
		}

		personaCacheModel.uuid_ = getUuid_();

		String uuid_ = personaCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			personaCacheModel.uuid_ = null;
		}

		personaCacheModel.originalEntityId = getOriginalEntityId();

		personaCacheModel.entityResourceId = getEntityResourceId();

		personaCacheModel.version = getVersion();

		personaCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = personaCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			personaCacheModel.workflowAction = null;
		}

		return personaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Persona, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Persona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Persona, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Persona)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Persona>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Persona.class, ModelWrapper.class);

	}

	private long _personaId;
	private long _channelId;
	private Long _darkThemeId;
	private Long _lightThemeId;
	private String _name;
	private int _startAge;
	private int _endAge;
	private String _nationality;
	private String _customerSegment;
	private String _personaStatus;
	private String _sector;
	private int _minIncome;
	private int _maxIncome;
	private String _description;
	private String _gender;
	private int _priority;
	private Date _dateFrom;
	private Date _dateTo;
	private boolean _defaultPersona;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;

	public <T> T getColumnValue(String columnName) {
		Function<Persona, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Persona)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("personaId", _personaId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("darkThemeId", _darkThemeId);
		_columnOriginalValues.put("lightThemeId", _lightThemeId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("startAge", _startAge);
		_columnOriginalValues.put("endAge", _endAge);
		_columnOriginalValues.put("nationality", _nationality);
		_columnOriginalValues.put("customerSegment", _customerSegment);
		_columnOriginalValues.put("personaStatus", _personaStatus);
		_columnOriginalValues.put("sector", _sector);
		_columnOriginalValues.put("minIncome", _minIncome);
		_columnOriginalValues.put("maxIncome", _maxIncome);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("dateFrom", _dateFrom);
		_columnOriginalValues.put("dateTo", _dateTo);
		_columnOriginalValues.put("defaultPersona", _defaultPersona);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("personaId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("darkThemeId", 4L);

		columnBitmasks.put("lightThemeId", 8L);

		columnBitmasks.put("name", 16L);

		columnBitmasks.put("startAge", 32L);

		columnBitmasks.put("endAge", 64L);

		columnBitmasks.put("nationality", 128L);

		columnBitmasks.put("customerSegment", 256L);

		columnBitmasks.put("personaStatus", 512L);

		columnBitmasks.put("sector", 1024L);

		columnBitmasks.put("minIncome", 2048L);

		columnBitmasks.put("maxIncome", 4096L);

		columnBitmasks.put("description", 8192L);

		columnBitmasks.put("gender", 16384L);

		columnBitmasks.put("priority", 32768L);

		columnBitmasks.put("dateFrom", 65536L);

		columnBitmasks.put("dateTo", 131072L);

		columnBitmasks.put("defaultPersona", 262144L);

		columnBitmasks.put("groupId", 524288L);

		columnBitmasks.put("companyId", 1048576L);

		columnBitmasks.put("userId", 2097152L);

		columnBitmasks.put("userName", 4194304L);

		columnBitmasks.put("createDate", 8388608L);

		columnBitmasks.put("modifiedDate", 16777216L);

		columnBitmasks.put("status", 33554432L);

		columnBitmasks.put("statusByUserId", 67108864L);

		columnBitmasks.put("statusByUserName", 134217728L);

		columnBitmasks.put("statusDate", 268435456L);

		columnBitmasks.put("uuid_", 536870912L);

		columnBitmasks.put("originalEntityId", 1073741824L);

		columnBitmasks.put("entityResourceId", 2147483648L);

		columnBitmasks.put("version", 4294967296L);

		columnBitmasks.put("workflowAction", 8589934592L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Persona _escapedModel;

}