/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.ResourceLocalization;
import com.ejada.telemony.db.model.ResourceLocalizationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ResourceLocalization service. Represents a row in the &quot;ResourceLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ResourceLocalizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceLocalizationImpl
 * @generated
 */
public class ResourceLocalizationModelImpl
	extends BaseModelImpl<ResourceLocalization>
	implements ResourceLocalizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource localization model instance should use the <code>ResourceLocalization</code> interface instead.
	 */
	public static final String TABLE_NAME = "ResourceLocalization";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"resourceLocalizationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"resourceId", Types.BIGINT},
		{"languageId", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"attachName", Types.VARCHAR}, {"attach", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"routeId", Types.VARCHAR},
		{"url", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourceLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("attachName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("attach", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("routeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ResourceLocalization (mvccVersion LONG default 0 not null,resourceLocalizationId LONG not null primary key,companyId LONG,resourceId LONG,languageId VARCHAR(75) null,name VARCHAR(75) null,attachName VARCHAR(75) null,attach VARCHAR(75) null,description VARCHAR(75) null,routeId VARCHAR(75) null,url VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ResourceLocalization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY resourceLocalization.resourceLocalizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ResourceLocalization.resourceLocalizationId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCELOCALIZATIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.ResourceLocalization"));

	public ResourceLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resourceLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResourceLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resourceLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ResourceLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return ResourceLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ResourceLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ResourceLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ResourceLocalization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ResourceLocalization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ResourceLocalization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ResourceLocalization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ResourceLocalization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ResourceLocalization, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ResourceLocalization, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ResourceLocalization, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ResourceLocalization, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ResourceLocalization, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ResourceLocalization::getMvccVersion);
			attributeGetterFunctions.put(
				"resourceLocalizationId",
				ResourceLocalization::getResourceLocalizationId);
			attributeGetterFunctions.put(
				"companyId", ResourceLocalization::getCompanyId);
			attributeGetterFunctions.put(
				"resourceId", ResourceLocalization::getResourceId);
			attributeGetterFunctions.put(
				"languageId", ResourceLocalization::getLanguageId);
			attributeGetterFunctions.put("name", ResourceLocalization::getName);
			attributeGetterFunctions.put(
				"attachName", ResourceLocalization::getAttachName);
			attributeGetterFunctions.put(
				"attach", ResourceLocalization::getAttach);
			attributeGetterFunctions.put(
				"description", ResourceLocalization::getDescription);
			attributeGetterFunctions.put(
				"routeId", ResourceLocalization::getRouteId);
			attributeGetterFunctions.put("url", ResourceLocalization::getUrl);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ResourceLocalization, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ResourceLocalization, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ResourceLocalization, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ResourceLocalization, Long>)
					ResourceLocalization::setMvccVersion);
			attributeSetterBiConsumers.put(
				"resourceLocalizationId",
				(BiConsumer<ResourceLocalization, Long>)
					ResourceLocalization::setResourceLocalizationId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ResourceLocalization, Long>)
					ResourceLocalization::setCompanyId);
			attributeSetterBiConsumers.put(
				"resourceId",
				(BiConsumer<ResourceLocalization, Long>)
					ResourceLocalization::setResourceId);
			attributeSetterBiConsumers.put(
				"languageId",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setLanguageId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setName);
			attributeSetterBiConsumers.put(
				"attachName",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setAttachName);
			attributeSetterBiConsumers.put(
				"attach",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setAttach);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setDescription);
			attributeSetterBiConsumers.put(
				"routeId",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setRouteId);
			attributeSetterBiConsumers.put(
				"url",
				(BiConsumer<ResourceLocalization, String>)
					ResourceLocalization::setUrl);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getResourceLocalizationId() {
		return _resourceLocalizationId;
	}

	@Override
	public void setResourceLocalizationId(long resourceLocalizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceLocalizationId = resourceLocalizationId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getResourceId() {
		return _resourceId;
	}

	@Override
	public void setResourceId(long resourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceId = resourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("resourceId"));
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public String getAttachName() {
		if (_attachName == null) {
			return "";
		}
		else {
			return _attachName;
		}
	}

	@Override
	public void setAttachName(String attachName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attachName = attachName;
	}

	@Override
	public String getAttach() {
		if (_attach == null) {
			return "";
		}
		else {
			return _attach;
		}
	}

	@Override
	public void setAttach(String attach) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attach = attach;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getRouteId() {
		if (_routeId == null) {
			return "";
		}
		else {
			return _routeId;
		}
	}

	@Override
	public void setRouteId(String routeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_routeId = routeId;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ResourceLocalization.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ResourceLocalization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ResourceLocalization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResourceLocalizationImpl resourceLocalizationImpl =
			new ResourceLocalizationImpl();

		resourceLocalizationImpl.setMvccVersion(getMvccVersion());
		resourceLocalizationImpl.setResourceLocalizationId(
			getResourceLocalizationId());
		resourceLocalizationImpl.setCompanyId(getCompanyId());
		resourceLocalizationImpl.setResourceId(getResourceId());
		resourceLocalizationImpl.setLanguageId(getLanguageId());
		resourceLocalizationImpl.setName(getName());
		resourceLocalizationImpl.setAttachName(getAttachName());
		resourceLocalizationImpl.setAttach(getAttach());
		resourceLocalizationImpl.setDescription(getDescription());
		resourceLocalizationImpl.setRouteId(getRouteId());
		resourceLocalizationImpl.setUrl(getUrl());

		resourceLocalizationImpl.resetOriginalValues();

		return resourceLocalizationImpl;
	}

	@Override
	public ResourceLocalization cloneWithOriginalValues() {
		ResourceLocalizationImpl resourceLocalizationImpl =
			new ResourceLocalizationImpl();

		resourceLocalizationImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		resourceLocalizationImpl.setResourceLocalizationId(
			this.<Long>getColumnOriginalValue("resourceLocalizationId"));
		resourceLocalizationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		resourceLocalizationImpl.setResourceId(
			this.<Long>getColumnOriginalValue("resourceId"));
		resourceLocalizationImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		resourceLocalizationImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		resourceLocalizationImpl.setAttachName(
			this.<String>getColumnOriginalValue("attachName"));
		resourceLocalizationImpl.setAttach(
			this.<String>getColumnOriginalValue("attach"));
		resourceLocalizationImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		resourceLocalizationImpl.setRouteId(
			this.<String>getColumnOriginalValue("routeId"));
		resourceLocalizationImpl.setUrl(
			this.<String>getColumnOriginalValue("url"));

		return resourceLocalizationImpl;
	}

	@Override
	public int compareTo(ResourceLocalization resourceLocalization) {
		long primaryKey = resourceLocalization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ResourceLocalization)) {
			return false;
		}

		ResourceLocalization resourceLocalization =
			(ResourceLocalization)object;

		long primaryKey = resourceLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ResourceLocalization> toCacheModel() {
		ResourceLocalizationCacheModel resourceLocalizationCacheModel =
			new ResourceLocalizationCacheModel();

		resourceLocalizationCacheModel.mvccVersion = getMvccVersion();

		resourceLocalizationCacheModel.resourceLocalizationId =
			getResourceLocalizationId();

		resourceLocalizationCacheModel.companyId = getCompanyId();

		resourceLocalizationCacheModel.resourceId = getResourceId();

		resourceLocalizationCacheModel.languageId = getLanguageId();

		String languageId = resourceLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			resourceLocalizationCacheModel.languageId = null;
		}

		resourceLocalizationCacheModel.name = getName();

		String name = resourceLocalizationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			resourceLocalizationCacheModel.name = null;
		}

		resourceLocalizationCacheModel.attachName = getAttachName();

		String attachName = resourceLocalizationCacheModel.attachName;

		if ((attachName != null) && (attachName.length() == 0)) {
			resourceLocalizationCacheModel.attachName = null;
		}

		resourceLocalizationCacheModel.attach = getAttach();

		String attach = resourceLocalizationCacheModel.attach;

		if ((attach != null) && (attach.length() == 0)) {
			resourceLocalizationCacheModel.attach = null;
		}

		resourceLocalizationCacheModel.description = getDescription();

		String description = resourceLocalizationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			resourceLocalizationCacheModel.description = null;
		}

		resourceLocalizationCacheModel.routeId = getRouteId();

		String routeId = resourceLocalizationCacheModel.routeId;

		if ((routeId != null) && (routeId.length() == 0)) {
			resourceLocalizationCacheModel.routeId = null;
		}

		resourceLocalizationCacheModel.url = getUrl();

		String url = resourceLocalizationCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			resourceLocalizationCacheModel.url = null;
		}

		return resourceLocalizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ResourceLocalization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ResourceLocalization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ResourceLocalization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ResourceLocalization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ResourceLocalization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ResourceLocalization.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _resourceLocalizationId;
	private long _companyId;
	private long _resourceId;
	private String _languageId;
	private String _name;
	private String _attachName;
	private String _attach;
	private String _description;
	private String _routeId;
	private String _url;

	public <T> T getColumnValue(String columnName) {
		Function<ResourceLocalization, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ResourceLocalization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"resourceLocalizationId", _resourceLocalizationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("resourceId", _resourceId);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("attachName", _attachName);
		_columnOriginalValues.put("attach", _attach);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("routeId", _routeId);
		_columnOriginalValues.put("url", _url);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("resourceLocalizationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("resourceId", 8L);

		columnBitmasks.put("languageId", 16L);

		columnBitmasks.put("name", 32L);

		columnBitmasks.put("attachName", 64L);

		columnBitmasks.put("attach", 128L);

		columnBitmasks.put("description", 256L);

		columnBitmasks.put("routeId", 512L);

		columnBitmasks.put("url", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ResourceLocalization _escapedModel;

}