/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Resource;
import com.ejada.telemony.db.service.ResourceLocalServiceUtil;

/**
 * The extended model base implementation for the Resource service. Represents a row in the &quot;Resource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceImpl
 * @see Resource
 * @generated
 */
public abstract class ResourceBaseImpl
	extends ResourceModelImpl implements Resource {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource model instance should use the <code>Resource</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ResourceLocalServiceUtil.addResource(this);
		}
		else {
			ResourceLocalServiceUtil.updateResource(this);
		}
	}

}