/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Resource;
import com.ejada.telemony.db.model.ResourceLocalization;
import com.ejada.telemony.db.model.ResourceModel;
import com.ejada.telemony.db.service.ResourceLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Resource service. Represents a row in the &quot;Resource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ResourceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceImpl
 * @generated
 */
@JSON(strict = true)
public class ResourceModelImpl
	extends BaseModelImpl<Resource> implements ResourceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource model instance should use the <code>Resource</code> interface instead.
	 */
	public static final String TABLE_NAME = "Resource";

	public static final Object[][] TABLE_COLUMNS = {
		{"defaultLanguageId", Types.VARCHAR}, {"resourceId", Types.BIGINT},
		{"channelId", Types.BIGINT}, {"resourceCode", Types.VARCHAR},
		{"resourceType", Types.VARCHAR}, {"urlType", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"version", Types.INTEGER},
		{"workflowAction", Types.VARCHAR}, {"featureId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resourceType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("urlType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("featureId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Resource (defaultLanguageId VARCHAR(75) null,resourceId LONG not null primary key,channelId LONG,resourceCode VARCHAR(75) null,resourceType VARCHAR(75) null,urlType VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null,featureId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Resource";

	public static final String ORDER_BY_JPQL =
		" ORDER BY resource.resourceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Resource.resourceId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCETYPE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCEID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Resource"));

	public ResourceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resourceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResourceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resourceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Resource.class;
	}

	@Override
	public String getModelClassName() {
		return Resource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Resource, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Resource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Resource, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Resource)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Resource, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Resource, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Resource)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Resource, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Resource, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Resource, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Resource, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Resource, Object>>();

			attributeGetterFunctions.put(
				"defaultLanguageId", Resource::getDefaultLanguageId);
			attributeGetterFunctions.put("resourceId", Resource::getResourceId);
			attributeGetterFunctions.put("channelId", Resource::getChannelId);
			attributeGetterFunctions.put(
				"resourceCode", Resource::getResourceCode);
			attributeGetterFunctions.put(
				"resourceType", Resource::getResourceType);
			attributeGetterFunctions.put("urlType", Resource::getUrlType);
			attributeGetterFunctions.put("groupId", Resource::getGroupId);
			attributeGetterFunctions.put("companyId", Resource::getCompanyId);
			attributeGetterFunctions.put("userId", Resource::getUserId);
			attributeGetterFunctions.put("userName", Resource::getUserName);
			attributeGetterFunctions.put("createDate", Resource::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Resource::getModifiedDate);
			attributeGetterFunctions.put("status", Resource::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Resource::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Resource::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Resource::getStatusDate);
			attributeGetterFunctions.put("uuid_", Resource::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Resource::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Resource::getEntityResourceId);
			attributeGetterFunctions.put("version", Resource::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Resource::getWorkflowAction);
			attributeGetterFunctions.put("featureId", Resource::getFeatureId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Resource, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Resource, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Resource, ?>>();

			attributeSetterBiConsumers.put(
				"defaultLanguageId",
				(BiConsumer<Resource, String>)Resource::setDefaultLanguageId);
			attributeSetterBiConsumers.put(
				"resourceId",
				(BiConsumer<Resource, Long>)Resource::setResourceId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<Resource, Long>)Resource::setChannelId);
			attributeSetterBiConsumers.put(
				"resourceCode",
				(BiConsumer<Resource, String>)Resource::setResourceCode);
			attributeSetterBiConsumers.put(
				"resourceType",
				(BiConsumer<Resource, String>)Resource::setResourceType);
			attributeSetterBiConsumers.put(
				"urlType", (BiConsumer<Resource, String>)Resource::setUrlType);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Resource, Long>)Resource::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Resource, Long>)Resource::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Resource, Long>)Resource::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Resource, String>)Resource::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Resource, Date>)Resource::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Resource, Date>)Resource::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Resource, Integer>)Resource::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Resource, Long>)Resource::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Resource, String>)Resource::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Resource, Date>)Resource::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Resource, String>)Resource::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Resource, Long>)Resource::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Resource, Long>)Resource::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Resource, Integer>)Resource::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Resource, String>)Resource::setWorkflowAction);
			attributeSetterBiConsumers.put(
				"featureId",
				(BiConsumer<Resource, Long>)Resource::setFeatureId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		String[] availableLanguageIds =
			new String[resourceLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			ResourceLocalization resourceLocalization =
				resourceLocalizations.get(i);

			availableLanguageIds[i] = resourceLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getName() {
		return getName(getDefaultLanguageId(), false);
	}

	@Override
	public String getName(String languageId) {
		return getName(languageId, true);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getName(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getName(languageId);
	}

	@Override
	public String getNameMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToNameMap(), getDefaultLanguageId(), "Name");
	}

	@Override
	public Map<String, String> getLanguageIdToNameMap() {
		Map<String, String> languageIdToNameMap = new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToNameMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getName());
		}

		return languageIdToNameMap;
	}

	private String _getName(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getName();
	}

	@Override
	public String getAttachName() {
		return getAttachName(getDefaultLanguageId(), false);
	}

	@Override
	public String getAttachName(String languageId) {
		return getAttachName(languageId, true);
	}

	@Override
	public String getAttachName(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getAttachName(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getAttachName(languageId);
	}

	@Override
	public String getAttachNameMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToAttachNameMap(), getDefaultLanguageId(),
			"AttachName");
	}

	@Override
	public Map<String, String> getLanguageIdToAttachNameMap() {
		Map<String, String> languageIdToAttachNameMap =
			new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToAttachNameMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getAttachName());
		}

		return languageIdToAttachNameMap;
	}

	private String _getAttachName(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getAttachName();
	}

	@Override
	public String getAttach() {
		return getAttach(getDefaultLanguageId(), false);
	}

	@Override
	public String getAttach(String languageId) {
		return getAttach(languageId, true);
	}

	@Override
	public String getAttach(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getAttach(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getAttach(languageId);
	}

	@Override
	public String getAttachMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToAttachMap(), getDefaultLanguageId(), "Attach");
	}

	@Override
	public Map<String, String> getLanguageIdToAttachMap() {
		Map<String, String> languageIdToAttachMap =
			new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToAttachMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getAttach());
		}

		return languageIdToAttachMap;
	}

	private String _getAttach(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getAttach();
	}

	@Override
	public String getDescription() {
		return getDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getDescription(String languageId) {
		return getDescription(languageId, true);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getDescription(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getDescription(languageId);
	}

	@Override
	public String getDescriptionMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToDescriptionMap(), getDefaultLanguageId(),
			"Description");
	}

	@Override
	public Map<String, String> getLanguageIdToDescriptionMap() {
		Map<String, String> languageIdToDescriptionMap =
			new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToDescriptionMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getDescription());
		}

		return languageIdToDescriptionMap;
	}

	private String _getDescription(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getDescription();
	}

	@Override
	public String getRouteId() {
		return getRouteId(getDefaultLanguageId(), false);
	}

	@Override
	public String getRouteId(String languageId) {
		return getRouteId(languageId, true);
	}

	@Override
	public String getRouteId(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getRouteId(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getRouteId(languageId);
	}

	@Override
	public String getRouteIdMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToRouteIdMap(), getDefaultLanguageId(), "RouteId");
	}

	@Override
	public Map<String, String> getLanguageIdToRouteIdMap() {
		Map<String, String> languageIdToRouteIdMap =
			new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToRouteIdMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getRouteId());
		}

		return languageIdToRouteIdMap;
	}

	private String _getRouteId(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getRouteId();
	}

	@Override
	public String getUrl() {
		return getUrl(getDefaultLanguageId(), false);
	}

	@Override
	public String getUrl(String languageId) {
		return getUrl(languageId, true);
	}

	@Override
	public String getUrl(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(
				new Function<String, String>() {

					@Override
					public String apply(String languageId) {
						return _getUrl(languageId);
					}

				},
				languageId, getDefaultLanguageId());
		}

		return _getUrl(languageId);
	}

	@Override
	public String getUrlMapAsXML() {
		return LocalizationUtil.getXml(
			getLanguageIdToUrlMap(), getDefaultLanguageId(), "Url");
	}

	@Override
	public Map<String, String> getLanguageIdToUrlMap() {
		Map<String, String> languageIdToUrlMap = new HashMap<String, String>();

		List<ResourceLocalization> resourceLocalizations =
			ResourceLocalServiceUtil.getResourceLocalizations(getPrimaryKey());

		for (ResourceLocalization resourceLocalization :
				resourceLocalizations) {

			languageIdToUrlMap.put(
				resourceLocalization.getLanguageId(),
				resourceLocalization.getUrl());
		}

		return languageIdToUrlMap;
	}

	private String _getUrl(String languageId) {
		ResourceLocalization resourceLocalization =
			ResourceLocalServiceUtil.fetchResourceLocalization(
				getPrimaryKey(), languageId);

		if (resourceLocalization == null) {
			return "";
		}

		return resourceLocalization.getUrl();
	}

	@JSON
	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultLanguageId = defaultLanguageId;
	}

	@JSON
	@Override
	public long getResourceId() {
		return _resourceId;
	}

	@Override
	public void setResourceId(long resourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceId = resourceId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getResourceCode() {
		if (_resourceCode == null) {
			return "";
		}
		else {
			return _resourceCode;
		}
	}

	@Override
	public void setResourceCode(String resourceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceCode = resourceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalResourceCode() {
		return getColumnOriginalValue("resourceCode");
	}

	@JSON
	@Override
	public String getResourceType() {
		if (_resourceType == null) {
			return "";
		}
		else {
			return _resourceType;
		}
	}

	@Override
	public void setResourceType(String resourceType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceType = resourceType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalResourceType() {
		return getColumnOriginalValue("resourceType");
	}

	@JSON
	@Override
	public String getUrlType() {
		if (_urlType == null) {
			return "";
		}
		else {
			return _urlType;
		}
	}

	@Override
	public void setUrlType(String urlType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_urlType = urlType;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@JSON
	@Override
	public long getFeatureId() {
		return _featureId;
	}

	@Override
	public void setFeatureId(long featureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureId = featureId;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Resource.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Resource toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Resource>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ResourceImpl resourceImpl = new ResourceImpl();

		resourceImpl.setDefaultLanguageId(getDefaultLanguageId());
		resourceImpl.setResourceId(getResourceId());
		resourceImpl.setChannelId(getChannelId());
		resourceImpl.setResourceCode(getResourceCode());
		resourceImpl.setResourceType(getResourceType());
		resourceImpl.setUrlType(getUrlType());
		resourceImpl.setGroupId(getGroupId());
		resourceImpl.setCompanyId(getCompanyId());
		resourceImpl.setUserId(getUserId());
		resourceImpl.setUserName(getUserName());
		resourceImpl.setCreateDate(getCreateDate());
		resourceImpl.setModifiedDate(getModifiedDate());
		resourceImpl.setStatus(getStatus());
		resourceImpl.setStatusByUserId(getStatusByUserId());
		resourceImpl.setStatusByUserName(getStatusByUserName());
		resourceImpl.setStatusDate(getStatusDate());
		resourceImpl.setUuid_(getUuid_());
		resourceImpl.setOriginalEntityId(getOriginalEntityId());
		resourceImpl.setEntityResourceId(getEntityResourceId());
		resourceImpl.setVersion(getVersion());
		resourceImpl.setWorkflowAction(getWorkflowAction());
		resourceImpl.setFeatureId(getFeatureId());

		resourceImpl.resetOriginalValues();

		return resourceImpl;
	}

	@Override
	public Resource cloneWithOriginalValues() {
		ResourceImpl resourceImpl = new ResourceImpl();

		resourceImpl.setDefaultLanguageId(
			this.<String>getColumnOriginalValue("defaultLanguageId"));
		resourceImpl.setResourceId(
			this.<Long>getColumnOriginalValue("resourceId"));
		resourceImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		resourceImpl.setResourceCode(
			this.<String>getColumnOriginalValue("resourceCode"));
		resourceImpl.setResourceType(
			this.<String>getColumnOriginalValue("resourceType"));
		resourceImpl.setUrlType(this.<String>getColumnOriginalValue("urlType"));
		resourceImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		resourceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		resourceImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		resourceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		resourceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		resourceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		resourceImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		resourceImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		resourceImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		resourceImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		resourceImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		resourceImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		resourceImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		resourceImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		resourceImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));
		resourceImpl.setFeatureId(
			this.<Long>getColumnOriginalValue("featureId"));

		return resourceImpl;
	}

	@Override
	public int compareTo(Resource resource) {
		long primaryKey = resource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Resource)) {
			return false;
		}

		Resource resource = (Resource)object;

		long primaryKey = resource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Resource> toCacheModel() {
		ResourceCacheModel resourceCacheModel = new ResourceCacheModel();

		resourceCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = resourceCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			resourceCacheModel.defaultLanguageId = null;
		}

		resourceCacheModel.resourceId = getResourceId();

		resourceCacheModel.channelId = getChannelId();

		resourceCacheModel.resourceCode = getResourceCode();

		String resourceCode = resourceCacheModel.resourceCode;

		if ((resourceCode != null) && (resourceCode.length() == 0)) {
			resourceCacheModel.resourceCode = null;
		}

		resourceCacheModel.resourceType = getResourceType();

		String resourceType = resourceCacheModel.resourceType;

		if ((resourceType != null) && (resourceType.length() == 0)) {
			resourceCacheModel.resourceType = null;
		}

		resourceCacheModel.urlType = getUrlType();

		String urlType = resourceCacheModel.urlType;

		if ((urlType != null) && (urlType.length() == 0)) {
			resourceCacheModel.urlType = null;
		}

		resourceCacheModel.groupId = getGroupId();

		resourceCacheModel.companyId = getCompanyId();

		resourceCacheModel.userId = getUserId();

		resourceCacheModel.userName = getUserName();

		String userName = resourceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			resourceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			resourceCacheModel.createDate = createDate.getTime();
		}
		else {
			resourceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			resourceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			resourceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		resourceCacheModel.status = getStatus();

		resourceCacheModel.statusByUserId = getStatusByUserId();

		resourceCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = resourceCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			resourceCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			resourceCacheModel.statusDate = statusDate.getTime();
		}
		else {
			resourceCacheModel.statusDate = Long.MIN_VALUE;
		}

		resourceCacheModel.uuid_ = getUuid_();

		String uuid_ = resourceCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			resourceCacheModel.uuid_ = null;
		}

		resourceCacheModel.originalEntityId = getOriginalEntityId();

		resourceCacheModel.entityResourceId = getEntityResourceId();

		resourceCacheModel.version = getVersion();

		resourceCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = resourceCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			resourceCacheModel.workflowAction = null;
		}

		resourceCacheModel.featureId = getFeatureId();

		return resourceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Resource, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Resource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Resource, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Resource)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Resource>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Resource.class, ModelWrapper.class);

	}

	private String _defaultLanguageId;
	private long _resourceId;
	private long _channelId;
	private String _resourceCode;
	private String _resourceType;
	private String _urlType;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;
	private long _featureId;

	public <T> T getColumnValue(String columnName) {
		Function<Resource, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Resource)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("defaultLanguageId", _defaultLanguageId);
		_columnOriginalValues.put("resourceId", _resourceId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("resourceCode", _resourceCode);
		_columnOriginalValues.put("resourceType", _resourceType);
		_columnOriginalValues.put("urlType", _urlType);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
		_columnOriginalValues.put("featureId", _featureId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("defaultLanguageId", 1L);

		columnBitmasks.put("resourceId", 2L);

		columnBitmasks.put("channelId", 4L);

		columnBitmasks.put("resourceCode", 8L);

		columnBitmasks.put("resourceType", 16L);

		columnBitmasks.put("urlType", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusByUserId", 8192L);

		columnBitmasks.put("statusByUserName", 16384L);

		columnBitmasks.put("statusDate", 32768L);

		columnBitmasks.put("uuid_", 65536L);

		columnBitmasks.put("originalEntityId", 131072L);

		columnBitmasks.put("entityResourceId", 262144L);

		columnBitmasks.put("version", 524288L);

		columnBitmasks.put("workflowAction", 1048576L);

		columnBitmasks.put("featureId", 2097152L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Resource _escapedModel;

}