/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Segment;
import com.ejada.telemony.db.model.SegmentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Segment service. Represents a row in the &quot;SEGMENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SegmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SegmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SegmentImpl
 * @generated
 */
@JSON(strict = true)
public class SegmentModelImpl
	extends BaseModelImpl<Segment> implements SegmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a segment model instance should use the <code>Segment</code> interface instead.
	 */
	public static final String TABLE_NAME = "SEGMENT";

	public static final Object[][] TABLE_COLUMNS = {
		{"segmentId", Types.BIGINT}, {"featureId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"segmentStatus", Types.BOOLEAN},
		{"method", Types.VARCHAR}, {"popUpTitle", Types.VARCHAR},
		{"popUpSubTitle", Types.VARCHAR}, {"status", Types.INTEGER},
		{"originalEntityId", Types.BIGINT}, {"entityResourceId", Types.BIGINT},
		{"childResourceId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("segmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("featureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("segmentStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("method", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("popUpTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("popUpSubTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childResourceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SEGMENT (segmentId LONG not null primary key,featureId LONG,name VARCHAR(75) null,segmentStatus BOOLEAN,method VARCHAR(75) null,popUpTitle VARCHAR(75) null,popUpSubTitle VARCHAR(75) null,status INTEGER,originalEntityId LONG,entityResourceId LONG,childResourceId LONG)";

	public static final String TABLE_SQL_DROP = "drop table SEGMENT";

	public static final String ORDER_BY_JPQL =
		" ORDER BY segment.segmentId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY SEGMENT.segmentId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHILDRESOURCEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FEATUREID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEGMENTID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Segment"));

	public SegmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _segmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSegmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _segmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Segment.class;
	}

	@Override
	public String getModelClassName() {
		return Segment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Segment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Segment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Segment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Segment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Segment, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Segment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Segment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Segment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Segment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Segment, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Segment, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Segment, Object>>();

			attributeGetterFunctions.put("segmentId", Segment::getSegmentId);
			attributeGetterFunctions.put("featureId", Segment::getFeatureId);
			attributeGetterFunctions.put("name", Segment::getName);
			attributeGetterFunctions.put(
				"segmentStatus", Segment::getSegmentStatus);
			attributeGetterFunctions.put("method", Segment::getMethod);
			attributeGetterFunctions.put("popUpTitle", Segment::getPopUpTitle);
			attributeGetterFunctions.put(
				"popUpSubTitle", Segment::getPopUpSubTitle);
			attributeGetterFunctions.put("status", Segment::getStatus);
			attributeGetterFunctions.put(
				"originalEntityId", Segment::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Segment::getEntityResourceId);
			attributeGetterFunctions.put(
				"childResourceId", Segment::getChildResourceId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Segment, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Segment, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Segment, ?>>();

			attributeSetterBiConsumers.put(
				"segmentId", (BiConsumer<Segment, Long>)Segment::setSegmentId);
			attributeSetterBiConsumers.put(
				"featureId", (BiConsumer<Segment, Long>)Segment::setFeatureId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Segment, String>)Segment::setName);
			attributeSetterBiConsumers.put(
				"segmentStatus",
				(BiConsumer<Segment, Boolean>)Segment::setSegmentStatus);
			attributeSetterBiConsumers.put(
				"method", (BiConsumer<Segment, String>)Segment::setMethod);
			attributeSetterBiConsumers.put(
				"popUpTitle",
				(BiConsumer<Segment, String>)Segment::setPopUpTitle);
			attributeSetterBiConsumers.put(
				"popUpSubTitle",
				(BiConsumer<Segment, String>)Segment::setPopUpSubTitle);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Segment, Integer>)Segment::setStatus);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Segment, Long>)Segment::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Segment, Long>)Segment::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"childResourceId",
				(BiConsumer<Segment, Long>)Segment::setChildResourceId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getSegmentId() {
		return _segmentId;
	}

	@Override
	public void setSegmentId(long segmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_segmentId = segmentId;
	}

	@JSON
	@Override
	public long getFeatureId() {
		return _featureId;
	}

	@Override
	public void setFeatureId(long featureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_featureId = featureId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFeatureId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("featureId"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public Boolean getSegmentStatus() {
		return _segmentStatus;
	}

	@Override
	public void setSegmentStatus(Boolean segmentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_segmentStatus = segmentStatus;
	}

	@JSON
	@Override
	public String getMethod() {
		if (_method == null) {
			return "";
		}
		else {
			return _method;
		}
	}

	@Override
	public void setMethod(String method) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_method = method;
	}

	@JSON
	@Override
	public String getPopUpTitle() {
		if (_popUpTitle == null) {
			return "";
		}
		else {
			return _popUpTitle;
		}
	}

	@Override
	public void setPopUpTitle(String popUpTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_popUpTitle = popUpTitle;
	}

	@JSON
	@Override
	public String getPopUpSubTitle() {
		if (_popUpSubTitle == null) {
			return "";
		}
		else {
			return _popUpSubTitle;
		}
	}

	@Override
	public void setPopUpSubTitle(String popUpSubTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_popUpSubTitle = popUpSubTitle;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public long getChildResourceId() {
		return _childResourceId;
	}

	@Override
	public void setChildResourceId(long childResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_childResourceId = childResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChildResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("childResourceId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Segment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Segment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Segment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SegmentImpl segmentImpl = new SegmentImpl();

		segmentImpl.setSegmentId(getSegmentId());
		segmentImpl.setFeatureId(getFeatureId());
		segmentImpl.setName(getName());
		segmentImpl.setSegmentStatus(getSegmentStatus());
		segmentImpl.setMethod(getMethod());
		segmentImpl.setPopUpTitle(getPopUpTitle());
		segmentImpl.setPopUpSubTitle(getPopUpSubTitle());
		segmentImpl.setStatus(getStatus());
		segmentImpl.setOriginalEntityId(getOriginalEntityId());
		segmentImpl.setEntityResourceId(getEntityResourceId());
		segmentImpl.setChildResourceId(getChildResourceId());

		segmentImpl.resetOriginalValues();

		return segmentImpl;
	}

	@Override
	public Segment cloneWithOriginalValues() {
		SegmentImpl segmentImpl = new SegmentImpl();

		segmentImpl.setSegmentId(
			this.<Long>getColumnOriginalValue("segmentId"));
		segmentImpl.setFeatureId(
			this.<Long>getColumnOriginalValue("featureId"));
		segmentImpl.setName(this.<String>getColumnOriginalValue("name"));
		segmentImpl.setSegmentStatus(
			this.<Boolean>getColumnOriginalValue("segmentStatus"));
		segmentImpl.setMethod(this.<String>getColumnOriginalValue("method"));
		segmentImpl.setPopUpTitle(
			this.<String>getColumnOriginalValue("popUpTitle"));
		segmentImpl.setPopUpSubTitle(
			this.<String>getColumnOriginalValue("popUpSubTitle"));
		segmentImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		segmentImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		segmentImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		segmentImpl.setChildResourceId(
			this.<Long>getColumnOriginalValue("childResourceId"));

		return segmentImpl;
	}

	@Override
	public int compareTo(Segment segment) {
		long primaryKey = segment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Segment)) {
			return false;
		}

		Segment segment = (Segment)object;

		long primaryKey = segment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Segment> toCacheModel() {
		SegmentCacheModel segmentCacheModel = new SegmentCacheModel();

		segmentCacheModel.segmentId = getSegmentId();

		segmentCacheModel.featureId = getFeatureId();

		segmentCacheModel.name = getName();

		String name = segmentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			segmentCacheModel.name = null;
		}

		Boolean segmentStatus = getSegmentStatus();

		if (segmentStatus != null) {
			segmentCacheModel.segmentStatus = segmentStatus;
		}

		segmentCacheModel.method = getMethod();

		String method = segmentCacheModel.method;

		if ((method != null) && (method.length() == 0)) {
			segmentCacheModel.method = null;
		}

		segmentCacheModel.popUpTitle = getPopUpTitle();

		String popUpTitle = segmentCacheModel.popUpTitle;

		if ((popUpTitle != null) && (popUpTitle.length() == 0)) {
			segmentCacheModel.popUpTitle = null;
		}

		segmentCacheModel.popUpSubTitle = getPopUpSubTitle();

		String popUpSubTitle = segmentCacheModel.popUpSubTitle;

		if ((popUpSubTitle != null) && (popUpSubTitle.length() == 0)) {
			segmentCacheModel.popUpSubTitle = null;
		}

		segmentCacheModel.status = getStatus();

		segmentCacheModel.originalEntityId = getOriginalEntityId();

		segmentCacheModel.entityResourceId = getEntityResourceId();

		segmentCacheModel.childResourceId = getChildResourceId();

		return segmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Segment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Segment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Segment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Segment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Segment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Segment.class, ModelWrapper.class);

	}

	private long _segmentId;
	private long _featureId;
	private String _name;
	private Boolean _segmentStatus;
	private String _method;
	private String _popUpTitle;
	private String _popUpSubTitle;
	private int _status;
	private long _originalEntityId;
	private long _entityResourceId;
	private long _childResourceId;

	public <T> T getColumnValue(String columnName) {
		Function<Segment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Segment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("segmentId", _segmentId);
		_columnOriginalValues.put("featureId", _featureId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("segmentStatus", _segmentStatus);
		_columnOriginalValues.put("method", _method);
		_columnOriginalValues.put("popUpTitle", _popUpTitle);
		_columnOriginalValues.put("popUpSubTitle", _popUpSubTitle);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("childResourceId", _childResourceId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("segmentId", 1L);

		columnBitmasks.put("featureId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("segmentStatus", 8L);

		columnBitmasks.put("method", 16L);

		columnBitmasks.put("popUpTitle", 32L);

		columnBitmasks.put("popUpSubTitle", 64L);

		columnBitmasks.put("status", 128L);

		columnBitmasks.put("originalEntityId", 256L);

		columnBitmasks.put("entityResourceId", 512L);

		columnBitmasks.put("childResourceId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Segment _escapedModel;

}