/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Themes;
import com.ejada.telemony.db.service.ThemesLocalServiceUtil;

/**
 * The extended model base implementation for the Themes service. Represents a row in the &quot;THEMES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThemesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ThemesImpl
 * @see Themes
 * @generated
 */
public abstract class ThemesBaseImpl extends ThemesModelImpl implements Themes {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a themes model instance should use the <code>Themes</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ThemesLocalServiceUtil.addThemes(this);
		}
		else {
			ThemesLocalServiceUtil.updateThemes(this);
		}
	}

}