/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.Themes;
import com.ejada.telemony.db.model.ThemesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Themes service. Represents a row in the &quot;THEMES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ThemesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThemesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ThemesImpl
 * @generated
 */
@JSON(strict = true)
public class ThemesModelImpl
	extends BaseModelImpl<Themes> implements ThemesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a themes model instance should use the <code>Themes</code> interface instead.
	 */
	public static final String TABLE_NAME = "THEMES";

	public static final Object[][] TABLE_COLUMNS = {
		{"themeId", Types.BIGINT}, {"channelId", Types.BIGINT},
		{"themeEnName", Types.VARCHAR}, {"themeArName", Types.VARCHAR},
		{"darkTheme", Types.BOOLEAN}, {"primaryColors", Types.VARCHAR},
		{"secondaryColors", Types.VARCHAR}, {"neutralColors", Types.VARCHAR},
		{"successColors", Types.VARCHAR}, {"errorColors", Types.VARCHAR},
		{"warningColors", Types.VARCHAR}, {"supportColors", Types.VARCHAR},
		{"gradientColors", Types.VARCHAR}, {"splashBg", Types.VARCHAR},
		{"splashAnimation", Types.VARCHAR}, {"headerBg", Types.VARCHAR},
		{"balanceBg", Types.VARCHAR}, {"defaultTheme", Types.BOOLEAN},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"uuid_", Types.VARCHAR}, {"originalEntityId", Types.BIGINT},
		{"entityResourceId", Types.BIGINT}, {"version", Types.INTEGER},
		{"workflowAction", Types.VARCHAR}, {"importRequestId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("themeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("themeEnName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("themeArName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("darkTheme", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("primaryColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("neutralColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("successColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("warningColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("supportColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gradientColors", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("splashBg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("splashAnimation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("headerBg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("balanceBg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("defaultTheme", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("originalEntityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workflowAction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importRequestId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table THEMES (themeId LONG not null primary key,channelId LONG,themeEnName VARCHAR(75) null,themeArName VARCHAR(75) null,darkTheme BOOLEAN,primaryColors VARCHAR(75) null,secondaryColors VARCHAR(75) null,neutralColors VARCHAR(75) null,successColors VARCHAR(75) null,errorColors VARCHAR(75) null,warningColors VARCHAR(75) null,supportColors VARCHAR(75) null,gradientColors VARCHAR(75) null,splashBg VARCHAR(75) null,splashAnimation VARCHAR(75) null,headerBg VARCHAR(75) null,balanceBg VARCHAR(75) null,defaultTheme BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,uuid_ VARCHAR(75) null,originalEntityId LONG,entityResourceId LONG,version INTEGER,workflowAction VARCHAR(75) null,importRequestId LONG)";

	public static final String TABLE_SQL_DROP = "drop table THEMES";

	public static final String ORDER_BY_JPQL = " ORDER BY themes.themeId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY THEMES.themeId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DARKTHEME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEFAULTTHEME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTITYRESOURCEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long THEMEID_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.Themes"));

	public ThemesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _themeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setThemeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _themeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Themes.class;
	}

	@Override
	public String getModelClassName() {
		return Themes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Themes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Themes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Themes, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Themes)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Themes, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Themes, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Themes)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Themes, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Themes, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Themes, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Themes, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Themes, Object>>();

			attributeGetterFunctions.put("themeId", Themes::getThemeId);
			attributeGetterFunctions.put("channelId", Themes::getChannelId);
			attributeGetterFunctions.put("themeEnName", Themes::getThemeEnName);
			attributeGetterFunctions.put("themeArName", Themes::getThemeArName);
			attributeGetterFunctions.put("darkTheme", Themes::getDarkTheme);
			attributeGetterFunctions.put(
				"primaryColors", Themes::getPrimaryColors);
			attributeGetterFunctions.put(
				"secondaryColors", Themes::getSecondaryColors);
			attributeGetterFunctions.put(
				"neutralColors", Themes::getNeutralColors);
			attributeGetterFunctions.put(
				"successColors", Themes::getSuccessColors);
			attributeGetterFunctions.put("errorColors", Themes::getErrorColors);
			attributeGetterFunctions.put(
				"warningColors", Themes::getWarningColors);
			attributeGetterFunctions.put(
				"supportColors", Themes::getSupportColors);
			attributeGetterFunctions.put(
				"gradientColors", Themes::getGradientColors);
			attributeGetterFunctions.put("splashBg", Themes::getSplashBg);
			attributeGetterFunctions.put(
				"splashAnimation", Themes::getSplashAnimation);
			attributeGetterFunctions.put("headerBg", Themes::getHeaderBg);
			attributeGetterFunctions.put("balanceBg", Themes::getBalanceBg);
			attributeGetterFunctions.put(
				"defaultTheme", Themes::getDefaultTheme);
			attributeGetterFunctions.put("groupId", Themes::getGroupId);
			attributeGetterFunctions.put("companyId", Themes::getCompanyId);
			attributeGetterFunctions.put("userId", Themes::getUserId);
			attributeGetterFunctions.put("userName", Themes::getUserName);
			attributeGetterFunctions.put("createDate", Themes::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Themes::getModifiedDate);
			attributeGetterFunctions.put("status", Themes::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Themes::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Themes::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Themes::getStatusDate);
			attributeGetterFunctions.put("uuid_", Themes::getUuid_);
			attributeGetterFunctions.put(
				"originalEntityId", Themes::getOriginalEntityId);
			attributeGetterFunctions.put(
				"entityResourceId", Themes::getEntityResourceId);
			attributeGetterFunctions.put("version", Themes::getVersion);
			attributeGetterFunctions.put(
				"workflowAction", Themes::getWorkflowAction);
			attributeGetterFunctions.put(
				"importRequestId", Themes::getImportRequestId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Themes, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Themes, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Themes, ?>>();

			attributeSetterBiConsumers.put(
				"themeId", (BiConsumer<Themes, Long>)Themes::setThemeId);
			attributeSetterBiConsumers.put(
				"channelId", (BiConsumer<Themes, Long>)Themes::setChannelId);
			attributeSetterBiConsumers.put(
				"themeEnName",
				(BiConsumer<Themes, String>)Themes::setThemeEnName);
			attributeSetterBiConsumers.put(
				"themeArName",
				(BiConsumer<Themes, String>)Themes::setThemeArName);
			attributeSetterBiConsumers.put(
				"darkTheme", (BiConsumer<Themes, Boolean>)Themes::setDarkTheme);
			attributeSetterBiConsumers.put(
				"primaryColors",
				(BiConsumer<Themes, String>)Themes::setPrimaryColors);
			attributeSetterBiConsumers.put(
				"secondaryColors",
				(BiConsumer<Themes, String>)Themes::setSecondaryColors);
			attributeSetterBiConsumers.put(
				"neutralColors",
				(BiConsumer<Themes, String>)Themes::setNeutralColors);
			attributeSetterBiConsumers.put(
				"successColors",
				(BiConsumer<Themes, String>)Themes::setSuccessColors);
			attributeSetterBiConsumers.put(
				"errorColors",
				(BiConsumer<Themes, String>)Themes::setErrorColors);
			attributeSetterBiConsumers.put(
				"warningColors",
				(BiConsumer<Themes, String>)Themes::setWarningColors);
			attributeSetterBiConsumers.put(
				"supportColors",
				(BiConsumer<Themes, String>)Themes::setSupportColors);
			attributeSetterBiConsumers.put(
				"gradientColors",
				(BiConsumer<Themes, String>)Themes::setGradientColors);
			attributeSetterBiConsumers.put(
				"splashBg", (BiConsumer<Themes, String>)Themes::setSplashBg);
			attributeSetterBiConsumers.put(
				"splashAnimation",
				(BiConsumer<Themes, String>)Themes::setSplashAnimation);
			attributeSetterBiConsumers.put(
				"headerBg", (BiConsumer<Themes, String>)Themes::setHeaderBg);
			attributeSetterBiConsumers.put(
				"balanceBg", (BiConsumer<Themes, String>)Themes::setBalanceBg);
			attributeSetterBiConsumers.put(
				"defaultTheme",
				(BiConsumer<Themes, Boolean>)Themes::setDefaultTheme);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Themes, Long>)Themes::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Themes, Long>)Themes::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Themes, Long>)Themes::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Themes, String>)Themes::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Themes, Date>)Themes::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Themes, Date>)Themes::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Themes, Integer>)Themes::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Themes, Long>)Themes::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Themes, String>)Themes::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate", (BiConsumer<Themes, Date>)Themes::setStatusDate);
			attributeSetterBiConsumers.put(
				"uuid_", (BiConsumer<Themes, String>)Themes::setUuid_);
			attributeSetterBiConsumers.put(
				"originalEntityId",
				(BiConsumer<Themes, Long>)Themes::setOriginalEntityId);
			attributeSetterBiConsumers.put(
				"entityResourceId",
				(BiConsumer<Themes, Long>)Themes::setEntityResourceId);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<Themes, Integer>)Themes::setVersion);
			attributeSetterBiConsumers.put(
				"workflowAction",
				(BiConsumer<Themes, String>)Themes::setWorkflowAction);
			attributeSetterBiConsumers.put(
				"importRequestId",
				(BiConsumer<Themes, Long>)Themes::setImportRequestId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getThemeId() {
		return _themeId;
	}

	@Override
	public void setThemeId(long themeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themeId = themeId;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getThemeEnName() {
		if (_themeEnName == null) {
			return "";
		}
		else {
			return _themeEnName;
		}
	}

	@Override
	public void setThemeEnName(String themeEnName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themeEnName = themeEnName;
	}

	@JSON
	@Override
	public String getThemeArName() {
		if (_themeArName == null) {
			return "";
		}
		else {
			return _themeArName;
		}
	}

	@Override
	public void setThemeArName(String themeArName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themeArName = themeArName;
	}

	@JSON
	@Override
	public boolean getDarkTheme() {
		return _darkTheme;
	}

	@JSON
	@Override
	public boolean isDarkTheme() {
		return _darkTheme;
	}

	@Override
	public void setDarkTheme(boolean darkTheme) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_darkTheme = darkTheme;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDarkTheme() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("darkTheme"));
	}

	@JSON
	@Override
	public String getPrimaryColors() {
		if (_primaryColors == null) {
			return "";
		}
		else {
			return _primaryColors;
		}
	}

	@Override
	public void setPrimaryColors(String primaryColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_primaryColors = primaryColors;
	}

	@JSON
	@Override
	public String getSecondaryColors() {
		if (_secondaryColors == null) {
			return "";
		}
		else {
			return _secondaryColors;
		}
	}

	@Override
	public void setSecondaryColors(String secondaryColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondaryColors = secondaryColors;
	}

	@JSON
	@Override
	public String getNeutralColors() {
		if (_neutralColors == null) {
			return "";
		}
		else {
			return _neutralColors;
		}
	}

	@Override
	public void setNeutralColors(String neutralColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_neutralColors = neutralColors;
	}

	@JSON
	@Override
	public String getSuccessColors() {
		if (_successColors == null) {
			return "";
		}
		else {
			return _successColors;
		}
	}

	@Override
	public void setSuccessColors(String successColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_successColors = successColors;
	}

	@JSON
	@Override
	public String getErrorColors() {
		if (_errorColors == null) {
			return "";
		}
		else {
			return _errorColors;
		}
	}

	@Override
	public void setErrorColors(String errorColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorColors = errorColors;
	}

	@JSON
	@Override
	public String getWarningColors() {
		if (_warningColors == null) {
			return "";
		}
		else {
			return _warningColors;
		}
	}

	@Override
	public void setWarningColors(String warningColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_warningColors = warningColors;
	}

	@JSON
	@Override
	public String getSupportColors() {
		if (_supportColors == null) {
			return "";
		}
		else {
			return _supportColors;
		}
	}

	@Override
	public void setSupportColors(String supportColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_supportColors = supportColors;
	}

	@JSON
	@Override
	public String getGradientColors() {
		if (_gradientColors == null) {
			return "";
		}
		else {
			return _gradientColors;
		}
	}

	@Override
	public void setGradientColors(String gradientColors) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gradientColors = gradientColors;
	}

	@JSON
	@Override
	public String getSplashBg() {
		if (_splashBg == null) {
			return "";
		}
		else {
			return _splashBg;
		}
	}

	@Override
	public void setSplashBg(String splashBg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_splashBg = splashBg;
	}

	@JSON
	@Override
	public String getSplashAnimation() {
		if (_splashAnimation == null) {
			return "";
		}
		else {
			return _splashAnimation;
		}
	}

	@Override
	public void setSplashAnimation(String splashAnimation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_splashAnimation = splashAnimation;
	}

	@JSON
	@Override
	public String getHeaderBg() {
		if (_headerBg == null) {
			return "";
		}
		else {
			return _headerBg;
		}
	}

	@Override
	public void setHeaderBg(String headerBg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_headerBg = headerBg;
	}

	@JSON
	@Override
	public String getBalanceBg() {
		if (_balanceBg == null) {
			return "";
		}
		else {
			return _balanceBg;
		}
	}

	@Override
	public void setBalanceBg(String balanceBg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_balanceBg = balanceBg;
	}

	@JSON
	@Override
	public boolean getDefaultTheme() {
		return _defaultTheme;
	}

	@JSON
	@Override
	public boolean isDefaultTheme() {
		return _defaultTheme;
	}

	@Override
	public void setDefaultTheme(boolean defaultTheme) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_defaultTheme = defaultTheme;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDefaultTheme() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("defaultTheme"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getUuid_() {
		if (_uuid_ == null) {
			return "";
		}
		else {
			return _uuid_;
		}
	}

	@Override
	public void setUuid_(String uuid_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid_ = uuid_;
	}

	@JSON
	@Override
	public long getOriginalEntityId() {
		return _originalEntityId;
	}

	@Override
	public void setOriginalEntityId(long originalEntityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalEntityId = originalEntityId;
	}

	@JSON
	@Override
	public long getEntityResourceId() {
		return _entityResourceId;
	}

	@Override
	public void setEntityResourceId(long entityResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityResourceId = entityResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntityResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entityResourceId"));
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getWorkflowAction() {
		if (_workflowAction == null) {
			return "";
		}
		else {
			return _workflowAction;
		}
	}

	@Override
	public void setWorkflowAction(String workflowAction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowAction = workflowAction;
	}

	@JSON
	@Override
	public long getImportRequestId() {
		return _importRequestId;
	}

	@Override
	public void setImportRequestId(long importRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importRequestId = importRequestId;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Themes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Themes toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Themes>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThemesImpl themesImpl = new ThemesImpl();

		themesImpl.setThemeId(getThemeId());
		themesImpl.setChannelId(getChannelId());
		themesImpl.setThemeEnName(getThemeEnName());
		themesImpl.setThemeArName(getThemeArName());
		themesImpl.setDarkTheme(isDarkTheme());
		themesImpl.setPrimaryColors(getPrimaryColors());
		themesImpl.setSecondaryColors(getSecondaryColors());
		themesImpl.setNeutralColors(getNeutralColors());
		themesImpl.setSuccessColors(getSuccessColors());
		themesImpl.setErrorColors(getErrorColors());
		themesImpl.setWarningColors(getWarningColors());
		themesImpl.setSupportColors(getSupportColors());
		themesImpl.setGradientColors(getGradientColors());
		themesImpl.setSplashBg(getSplashBg());
		themesImpl.setSplashAnimation(getSplashAnimation());
		themesImpl.setHeaderBg(getHeaderBg());
		themesImpl.setBalanceBg(getBalanceBg());
		themesImpl.setDefaultTheme(isDefaultTheme());
		themesImpl.setGroupId(getGroupId());
		themesImpl.setCompanyId(getCompanyId());
		themesImpl.setUserId(getUserId());
		themesImpl.setUserName(getUserName());
		themesImpl.setCreateDate(getCreateDate());
		themesImpl.setModifiedDate(getModifiedDate());
		themesImpl.setStatus(getStatus());
		themesImpl.setStatusByUserId(getStatusByUserId());
		themesImpl.setStatusByUserName(getStatusByUserName());
		themesImpl.setStatusDate(getStatusDate());
		themesImpl.setUuid_(getUuid_());
		themesImpl.setOriginalEntityId(getOriginalEntityId());
		themesImpl.setEntityResourceId(getEntityResourceId());
		themesImpl.setVersion(getVersion());
		themesImpl.setWorkflowAction(getWorkflowAction());
		themesImpl.setImportRequestId(getImportRequestId());

		themesImpl.resetOriginalValues();

		return themesImpl;
	}

	@Override
	public Themes cloneWithOriginalValues() {
		ThemesImpl themesImpl = new ThemesImpl();

		themesImpl.setThemeId(this.<Long>getColumnOriginalValue("themeId"));
		themesImpl.setChannelId(this.<Long>getColumnOriginalValue("channelId"));
		themesImpl.setThemeEnName(
			this.<String>getColumnOriginalValue("themeEnName"));
		themesImpl.setThemeArName(
			this.<String>getColumnOriginalValue("themeArName"));
		themesImpl.setDarkTheme(
			this.<Boolean>getColumnOriginalValue("darkTheme"));
		themesImpl.setPrimaryColors(
			this.<String>getColumnOriginalValue("primaryColors"));
		themesImpl.setSecondaryColors(
			this.<String>getColumnOriginalValue("secondaryColors"));
		themesImpl.setNeutralColors(
			this.<String>getColumnOriginalValue("neutralColors"));
		themesImpl.setSuccessColors(
			this.<String>getColumnOriginalValue("successColors"));
		themesImpl.setErrorColors(
			this.<String>getColumnOriginalValue("errorColors"));
		themesImpl.setWarningColors(
			this.<String>getColumnOriginalValue("warningColors"));
		themesImpl.setSupportColors(
			this.<String>getColumnOriginalValue("supportColors"));
		themesImpl.setGradientColors(
			this.<String>getColumnOriginalValue("gradientColors"));
		themesImpl.setSplashBg(this.<String>getColumnOriginalValue("splashBg"));
		themesImpl.setSplashAnimation(
			this.<String>getColumnOriginalValue("splashAnimation"));
		themesImpl.setHeaderBg(this.<String>getColumnOriginalValue("headerBg"));
		themesImpl.setBalanceBg(
			this.<String>getColumnOriginalValue("balanceBg"));
		themesImpl.setDefaultTheme(
			this.<Boolean>getColumnOriginalValue("defaultTheme"));
		themesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		themesImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		themesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		themesImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		themesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		themesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		themesImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		themesImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		themesImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		themesImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		themesImpl.setUuid_(this.<String>getColumnOriginalValue("uuid_"));
		themesImpl.setOriginalEntityId(
			this.<Long>getColumnOriginalValue("originalEntityId"));
		themesImpl.setEntityResourceId(
			this.<Long>getColumnOriginalValue("entityResourceId"));
		themesImpl.setVersion(this.<Integer>getColumnOriginalValue("version"));
		themesImpl.setWorkflowAction(
			this.<String>getColumnOriginalValue("workflowAction"));
		themesImpl.setImportRequestId(
			this.<Long>getColumnOriginalValue("importRequestId"));

		return themesImpl;
	}

	@Override
	public int compareTo(Themes themes) {
		long primaryKey = themes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Themes)) {
			return false;
		}

		Themes themes = (Themes)object;

		long primaryKey = themes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Themes> toCacheModel() {
		ThemesCacheModel themesCacheModel = new ThemesCacheModel();

		themesCacheModel.themeId = getThemeId();

		themesCacheModel.channelId = getChannelId();

		themesCacheModel.themeEnName = getThemeEnName();

		String themeEnName = themesCacheModel.themeEnName;

		if ((themeEnName != null) && (themeEnName.length() == 0)) {
			themesCacheModel.themeEnName = null;
		}

		themesCacheModel.themeArName = getThemeArName();

		String themeArName = themesCacheModel.themeArName;

		if ((themeArName != null) && (themeArName.length() == 0)) {
			themesCacheModel.themeArName = null;
		}

		themesCacheModel.darkTheme = isDarkTheme();

		themesCacheModel.primaryColors = getPrimaryColors();

		String primaryColors = themesCacheModel.primaryColors;

		if ((primaryColors != null) && (primaryColors.length() == 0)) {
			themesCacheModel.primaryColors = null;
		}

		themesCacheModel.secondaryColors = getSecondaryColors();

		String secondaryColors = themesCacheModel.secondaryColors;

		if ((secondaryColors != null) && (secondaryColors.length() == 0)) {
			themesCacheModel.secondaryColors = null;
		}

		themesCacheModel.neutralColors = getNeutralColors();

		String neutralColors = themesCacheModel.neutralColors;

		if ((neutralColors != null) && (neutralColors.length() == 0)) {
			themesCacheModel.neutralColors = null;
		}

		themesCacheModel.successColors = getSuccessColors();

		String successColors = themesCacheModel.successColors;

		if ((successColors != null) && (successColors.length() == 0)) {
			themesCacheModel.successColors = null;
		}

		themesCacheModel.errorColors = getErrorColors();

		String errorColors = themesCacheModel.errorColors;

		if ((errorColors != null) && (errorColors.length() == 0)) {
			themesCacheModel.errorColors = null;
		}

		themesCacheModel.warningColors = getWarningColors();

		String warningColors = themesCacheModel.warningColors;

		if ((warningColors != null) && (warningColors.length() == 0)) {
			themesCacheModel.warningColors = null;
		}

		themesCacheModel.supportColors = getSupportColors();

		String supportColors = themesCacheModel.supportColors;

		if ((supportColors != null) && (supportColors.length() == 0)) {
			themesCacheModel.supportColors = null;
		}

		themesCacheModel.gradientColors = getGradientColors();

		String gradientColors = themesCacheModel.gradientColors;

		if ((gradientColors != null) && (gradientColors.length() == 0)) {
			themesCacheModel.gradientColors = null;
		}

		themesCacheModel.splashBg = getSplashBg();

		String splashBg = themesCacheModel.splashBg;

		if ((splashBg != null) && (splashBg.length() == 0)) {
			themesCacheModel.splashBg = null;
		}

		themesCacheModel.splashAnimation = getSplashAnimation();

		String splashAnimation = themesCacheModel.splashAnimation;

		if ((splashAnimation != null) && (splashAnimation.length() == 0)) {
			themesCacheModel.splashAnimation = null;
		}

		themesCacheModel.headerBg = getHeaderBg();

		String headerBg = themesCacheModel.headerBg;

		if ((headerBg != null) && (headerBg.length() == 0)) {
			themesCacheModel.headerBg = null;
		}

		themesCacheModel.balanceBg = getBalanceBg();

		String balanceBg = themesCacheModel.balanceBg;

		if ((balanceBg != null) && (balanceBg.length() == 0)) {
			themesCacheModel.balanceBg = null;
		}

		themesCacheModel.defaultTheme = isDefaultTheme();

		themesCacheModel.groupId = getGroupId();

		themesCacheModel.companyId = getCompanyId();

		themesCacheModel.userId = getUserId();

		themesCacheModel.userName = getUserName();

		String userName = themesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			themesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			themesCacheModel.createDate = createDate.getTime();
		}
		else {
			themesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			themesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			themesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		themesCacheModel.status = getStatus();

		themesCacheModel.statusByUserId = getStatusByUserId();

		themesCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = themesCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			themesCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			themesCacheModel.statusDate = statusDate.getTime();
		}
		else {
			themesCacheModel.statusDate = Long.MIN_VALUE;
		}

		themesCacheModel.uuid_ = getUuid_();

		String uuid_ = themesCacheModel.uuid_;

		if ((uuid_ != null) && (uuid_.length() == 0)) {
			themesCacheModel.uuid_ = null;
		}

		themesCacheModel.originalEntityId = getOriginalEntityId();

		themesCacheModel.entityResourceId = getEntityResourceId();

		themesCacheModel.version = getVersion();

		themesCacheModel.workflowAction = getWorkflowAction();

		String workflowAction = themesCacheModel.workflowAction;

		if ((workflowAction != null) && (workflowAction.length() == 0)) {
			themesCacheModel.workflowAction = null;
		}

		themesCacheModel.importRequestId = getImportRequestId();

		return themesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Themes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Themes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Themes, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Themes)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Themes>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Themes.class, ModelWrapper.class);

	}

	private long _themeId;
	private long _channelId;
	private String _themeEnName;
	private String _themeArName;
	private boolean _darkTheme;
	private String _primaryColors;
	private String _secondaryColors;
	private String _neutralColors;
	private String _successColors;
	private String _errorColors;
	private String _warningColors;
	private String _supportColors;
	private String _gradientColors;
	private String _splashBg;
	private String _splashAnimation;
	private String _headerBg;
	private String _balanceBg;
	private boolean _defaultTheme;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _uuid_;
	private long _originalEntityId;
	private long _entityResourceId;
	private int _version;
	private String _workflowAction;
	private long _importRequestId;

	public <T> T getColumnValue(String columnName) {
		Function<Themes, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Themes)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("themeId", _themeId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("themeEnName", _themeEnName);
		_columnOriginalValues.put("themeArName", _themeArName);
		_columnOriginalValues.put("darkTheme", _darkTheme);
		_columnOriginalValues.put("primaryColors", _primaryColors);
		_columnOriginalValues.put("secondaryColors", _secondaryColors);
		_columnOriginalValues.put("neutralColors", _neutralColors);
		_columnOriginalValues.put("successColors", _successColors);
		_columnOriginalValues.put("errorColors", _errorColors);
		_columnOriginalValues.put("warningColors", _warningColors);
		_columnOriginalValues.put("supportColors", _supportColors);
		_columnOriginalValues.put("gradientColors", _gradientColors);
		_columnOriginalValues.put("splashBg", _splashBg);
		_columnOriginalValues.put("splashAnimation", _splashAnimation);
		_columnOriginalValues.put("headerBg", _headerBg);
		_columnOriginalValues.put("balanceBg", _balanceBg);
		_columnOriginalValues.put("defaultTheme", _defaultTheme);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("uuid_", _uuid_);
		_columnOriginalValues.put("originalEntityId", _originalEntityId);
		_columnOriginalValues.put("entityResourceId", _entityResourceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("workflowAction", _workflowAction);
		_columnOriginalValues.put("importRequestId", _importRequestId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("themeId", 1L);

		columnBitmasks.put("channelId", 2L);

		columnBitmasks.put("themeEnName", 4L);

		columnBitmasks.put("themeArName", 8L);

		columnBitmasks.put("darkTheme", 16L);

		columnBitmasks.put("primaryColors", 32L);

		columnBitmasks.put("secondaryColors", 64L);

		columnBitmasks.put("neutralColors", 128L);

		columnBitmasks.put("successColors", 256L);

		columnBitmasks.put("errorColors", 512L);

		columnBitmasks.put("warningColors", 1024L);

		columnBitmasks.put("supportColors", 2048L);

		columnBitmasks.put("gradientColors", 4096L);

		columnBitmasks.put("splashBg", 8192L);

		columnBitmasks.put("splashAnimation", 16384L);

		columnBitmasks.put("headerBg", 32768L);

		columnBitmasks.put("balanceBg", 65536L);

		columnBitmasks.put("defaultTheme", 131072L);

		columnBitmasks.put("groupId", 262144L);

		columnBitmasks.put("companyId", 524288L);

		columnBitmasks.put("userId", 1048576L);

		columnBitmasks.put("userName", 2097152L);

		columnBitmasks.put("createDate", 4194304L);

		columnBitmasks.put("modifiedDate", 8388608L);

		columnBitmasks.put("status", 16777216L);

		columnBitmasks.put("statusByUserId", 33554432L);

		columnBitmasks.put("statusByUserName", 67108864L);

		columnBitmasks.put("statusDate", 134217728L);

		columnBitmasks.put("uuid_", 268435456L);

		columnBitmasks.put("originalEntityId", 536870912L);

		columnBitmasks.put("entityResourceId", 1073741824L);

		columnBitmasks.put("version", 2147483648L);

		columnBitmasks.put("workflowAction", 4294967296L);

		columnBitmasks.put("importRequestId", 8589934592L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Themes _escapedModel;

}