/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.model.impl;

import com.ejada.telemony.db.model.UserLogs;
import com.ejada.telemony.db.model.UserLogsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserLogs service. Represents a row in the &quot;USER_LOGS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserLogsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserLogsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserLogsImpl
 * @generated
 */
@JSON(strict = true)
public class UserLogsModelImpl
	extends BaseModelImpl<UserLogs> implements UserLogsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user logs model instance should use the <code>UserLogs</code> interface instead.
	 */
	public static final String TABLE_NAME = "USER_LOGS";

	public static final Object[][] TABLE_COLUMNS = {
		{"logsId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"userActivity", Types.VARCHAR}, {"logTime", Types.TIMESTAMP},
		{"channelId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("logsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userActivity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table USER_LOGS (logsId LONG not null primary key,userName VARCHAR(75) null,userActivity VARCHAR(75) null,logTime DATE null,channelId LONG)";

	public static final String TABLE_SQL_DROP = "drop table USER_LOGS";

	public static final String ORDER_BY_JPQL = " ORDER BY userLogs.logsId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY USER_LOGS.logsId ASC";

	public static final String DATA_SOURCE = "extDS";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGSID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.ejada.telemony.db.service.util.ServiceProps.get(
			"lock.expiration.time.com.ejada.telemony.db.model.UserLogs"));

	public UserLogsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserLogs.class;
	}

	@Override
	public String getModelClassName() {
		return UserLogs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserLogs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserLogs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserLogs, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((UserLogs)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserLogs, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserLogs, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserLogs)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserLogs, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserLogs, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<UserLogs, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<UserLogs, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<UserLogs, Object>>();

			attributeGetterFunctions.put("logsId", UserLogs::getLogsId);
			attributeGetterFunctions.put("userName", UserLogs::getUserName);
			attributeGetterFunctions.put(
				"userActivity", UserLogs::getUserActivity);
			attributeGetterFunctions.put("logTime", UserLogs::getLogTime);
			attributeGetterFunctions.put("channelId", UserLogs::getChannelId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<UserLogs, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UserLogs, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<UserLogs, ?>>();

			attributeSetterBiConsumers.put(
				"logsId", (BiConsumer<UserLogs, Long>)UserLogs::setLogsId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<UserLogs, String>)UserLogs::setUserName);
			attributeSetterBiConsumers.put(
				"userActivity",
				(BiConsumer<UserLogs, String>)UserLogs::setUserActivity);
			attributeSetterBiConsumers.put(
				"logTime", (BiConsumer<UserLogs, Date>)UserLogs::setLogTime);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<UserLogs, Long>)UserLogs::setChannelId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLogsId() {
		return _logsId;
	}

	@Override
	public void setLogsId(long logsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logsId = logsId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getUserActivity() {
		if (_userActivity == null) {
			return "";
		}
		else {
			return _userActivity;
		}
	}

	@Override
	public void setUserActivity(String userActivity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userActivity = userActivity;
	}

	@JSON
	@Override
	public Date getLogTime() {
		return _logTime;
	}

	@Override
	public void setLogTime(Date logTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logTime = logTime;
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, UserLogs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserLogs toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserLogs>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserLogsImpl userLogsImpl = new UserLogsImpl();

		userLogsImpl.setLogsId(getLogsId());
		userLogsImpl.setUserName(getUserName());
		userLogsImpl.setUserActivity(getUserActivity());
		userLogsImpl.setLogTime(getLogTime());
		userLogsImpl.setChannelId(getChannelId());

		userLogsImpl.resetOriginalValues();

		return userLogsImpl;
	}

	@Override
	public UserLogs cloneWithOriginalValues() {
		UserLogsImpl userLogsImpl = new UserLogsImpl();

		userLogsImpl.setLogsId(this.<Long>getColumnOriginalValue("logsId"));
		userLogsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		userLogsImpl.setUserActivity(
			this.<String>getColumnOriginalValue("userActivity"));
		userLogsImpl.setLogTime(this.<Date>getColumnOriginalValue("logTime"));
		userLogsImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));

		return userLogsImpl;
	}

	@Override
	public int compareTo(UserLogs userLogs) {
		long primaryKey = userLogs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserLogs)) {
			return false;
		}

		UserLogs userLogs = (UserLogs)object;

		long primaryKey = userLogs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserLogs> toCacheModel() {
		UserLogsCacheModel userLogsCacheModel = new UserLogsCacheModel();

		userLogsCacheModel.logsId = getLogsId();

		userLogsCacheModel.userName = getUserName();

		String userName = userLogsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			userLogsCacheModel.userName = null;
		}

		userLogsCacheModel.userActivity = getUserActivity();

		String userActivity = userLogsCacheModel.userActivity;

		if ((userActivity != null) && (userActivity.length() == 0)) {
			userLogsCacheModel.userActivity = null;
		}

		Date logTime = getLogTime();

		if (logTime != null) {
			userLogsCacheModel.logTime = logTime.getTime();
		}
		else {
			userLogsCacheModel.logTime = Long.MIN_VALUE;
		}

		userLogsCacheModel.channelId = getChannelId();

		return userLogsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserLogs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserLogs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserLogs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserLogs)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserLogs>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserLogs.class, ModelWrapper.class);

	}

	private long _logsId;
	private String _userName;
	private String _userActivity;
	private Date _logTime;
	private long _channelId;

	public <T> T getColumnValue(String columnName) {
		Function<UserLogs, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserLogs)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("logsId", _logsId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("userActivity", _userActivity);
		_columnOriginalValues.put("logTime", _logTime);
		_columnOriginalValues.put("channelId", _channelId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("logsId", 1L);

		columnBitmasks.put("userName", 2L);

		columnBitmasks.put("userActivity", 4L);

		columnBitmasks.put("logTime", 8L);

		columnBitmasks.put("channelId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserLogs _escapedModel;

}