dependencies {
	compileOnly group: "com.liferay.portal", name: "release.dxp.api"

	compileOnly project(":modules:telemoney-db:telemoney-db-service")
	compileOnly project(":modules:telemoney-db:telemoney-db-api")
	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.0.2"
	
	
}