/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ejada.telemony.db.service.base;

import com.ejada.telemony.db.model.Resource;
import com.ejada.telemony.db.service.ResourceService;
import com.ejada.telemony.db.service.ResourceServiceUtil;
import com.ejada.telemony.db.service.persistence.AppConfigItemPersistence;
import com.ejada.telemony.db.service.persistence.AppEnvironmentPersistence;
import com.ejada.telemony.db.service.persistence.AppVersionPersistence;
import com.ejada.telemony.db.service.persistence.BannerContentLocalizationPersistence;
import com.ejada.telemony.db.service.persistence.BannerContentPersistence;
import com.ejada.telemony.db.service.persistence.BannerPersistence;
import com.ejada.telemony.db.service.persistence.BlocksPersistence;
import com.ejada.telemony.db.service.persistence.ChannelsPersistence;
import com.ejada.telemony.db.service.persistence.ConfigurationEntityPersistence;
import com.ejada.telemony.db.service.persistence.FeatureLovMapPersistence;
import com.ejada.telemony.db.service.persistence.FeaturePersistence;
import com.ejada.telemony.db.service.persistence.GlobalVersionPersistence;
import com.ejada.telemony.db.service.persistence.ImportRequestPersistence;
import com.ejada.telemony.db.service.persistence.LanguagesPersistence;
import com.ejada.telemony.db.service.persistence.LocalizationPersistence;
import com.ejada.telemony.db.service.persistence.LovDataLocalizationPersistence;
import com.ejada.telemony.db.service.persistence.LovDataPersistence;
import com.ejada.telemony.db.service.persistence.LovsLocalizationPersistence;
import com.ejada.telemony.db.service.persistence.LovsPersistence;
import com.ejada.telemony.db.service.persistence.PersonaPersistence;
import com.ejada.telemony.db.service.persistence.ResourceLocalizationPersistence;
import com.ejada.telemony.db.service.persistence.ResourcePersistence;
import com.ejada.telemony.db.service.persistence.SegmentPersistence;
import com.ejada.telemony.db.service.persistence.ThemesPersistence;
import com.ejada.telemony.db.service.persistence.UserLogsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.service.persistence.WorkflowInstanceLinkPersistence;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the resource remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ejada.telemony.db.service.impl.ResourceServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.ejada.telemony.db.service.impl.ResourceServiceImpl
 * @generated
 */
public abstract class ResourceServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, ResourceService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ResourceService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ResourceServiceUtil</code>.
	 */

	/**
	 * Returns the app config item local service.
	 *
	 * @return the app config item local service
	 */
	public com.ejada.telemony.db.service.AppConfigItemLocalService
		getAppConfigItemLocalService() {

		return appConfigItemLocalService;
	}

	/**
	 * Sets the app config item local service.
	 *
	 * @param appConfigItemLocalService the app config item local service
	 */
	public void setAppConfigItemLocalService(
		com.ejada.telemony.db.service.AppConfigItemLocalService
			appConfigItemLocalService) {

		this.appConfigItemLocalService = appConfigItemLocalService;
	}

	/**
	 * Returns the app config item remote service.
	 *
	 * @return the app config item remote service
	 */
	public com.ejada.telemony.db.service.AppConfigItemService
		getAppConfigItemService() {

		return appConfigItemService;
	}

	/**
	 * Sets the app config item remote service.
	 *
	 * @param appConfigItemService the app config item remote service
	 */
	public void setAppConfigItemService(
		com.ejada.telemony.db.service.AppConfigItemService
			appConfigItemService) {

		this.appConfigItemService = appConfigItemService;
	}

	/**
	 * Returns the app config item persistence.
	 *
	 * @return the app config item persistence
	 */
	public AppConfigItemPersistence getAppConfigItemPersistence() {
		return appConfigItemPersistence;
	}

	/**
	 * Sets the app config item persistence.
	 *
	 * @param appConfigItemPersistence the app config item persistence
	 */
	public void setAppConfigItemPersistence(
		AppConfigItemPersistence appConfigItemPersistence) {

		this.appConfigItemPersistence = appConfigItemPersistence;
	}

	/**
	 * Returns the app environment local service.
	 *
	 * @return the app environment local service
	 */
	public com.ejada.telemony.db.service.AppEnvironmentLocalService
		getAppEnvironmentLocalService() {

		return appEnvironmentLocalService;
	}

	/**
	 * Sets the app environment local service.
	 *
	 * @param appEnvironmentLocalService the app environment local service
	 */
	public void setAppEnvironmentLocalService(
		com.ejada.telemony.db.service.AppEnvironmentLocalService
			appEnvironmentLocalService) {

		this.appEnvironmentLocalService = appEnvironmentLocalService;
	}

	/**
	 * Returns the app environment remote service.
	 *
	 * @return the app environment remote service
	 */
	public com.ejada.telemony.db.service.AppEnvironmentService
		getAppEnvironmentService() {

		return appEnvironmentService;
	}

	/**
	 * Sets the app environment remote service.
	 *
	 * @param appEnvironmentService the app environment remote service
	 */
	public void setAppEnvironmentService(
		com.ejada.telemony.db.service.AppEnvironmentService
			appEnvironmentService) {

		this.appEnvironmentService = appEnvironmentService;
	}

	/**
	 * Returns the app environment persistence.
	 *
	 * @return the app environment persistence
	 */
	public AppEnvironmentPersistence getAppEnvironmentPersistence() {
		return appEnvironmentPersistence;
	}

	/**
	 * Sets the app environment persistence.
	 *
	 * @param appEnvironmentPersistence the app environment persistence
	 */
	public void setAppEnvironmentPersistence(
		AppEnvironmentPersistence appEnvironmentPersistence) {

		this.appEnvironmentPersistence = appEnvironmentPersistence;
	}

	/**
	 * Returns the app version local service.
	 *
	 * @return the app version local service
	 */
	public com.ejada.telemony.db.service.AppVersionLocalService
		getAppVersionLocalService() {

		return appVersionLocalService;
	}

	/**
	 * Sets the app version local service.
	 *
	 * @param appVersionLocalService the app version local service
	 */
	public void setAppVersionLocalService(
		com.ejada.telemony.db.service.AppVersionLocalService
			appVersionLocalService) {

		this.appVersionLocalService = appVersionLocalService;
	}

	/**
	 * Returns the app version remote service.
	 *
	 * @return the app version remote service
	 */
	public com.ejada.telemony.db.service.AppVersionService
		getAppVersionService() {

		return appVersionService;
	}

	/**
	 * Sets the app version remote service.
	 *
	 * @param appVersionService the app version remote service
	 */
	public void setAppVersionService(
		com.ejada.telemony.db.service.AppVersionService appVersionService) {

		this.appVersionService = appVersionService;
	}

	/**
	 * Returns the app version persistence.
	 *
	 * @return the app version persistence
	 */
	public AppVersionPersistence getAppVersionPersistence() {
		return appVersionPersistence;
	}

	/**
	 * Sets the app version persistence.
	 *
	 * @param appVersionPersistence the app version persistence
	 */
	public void setAppVersionPersistence(
		AppVersionPersistence appVersionPersistence) {

		this.appVersionPersistence = appVersionPersistence;
	}

	/**
	 * Returns the banner local service.
	 *
	 * @return the banner local service
	 */
	public com.ejada.telemony.db.service.BannerLocalService
		getBannerLocalService() {

		return bannerLocalService;
	}

	/**
	 * Sets the banner local service.
	 *
	 * @param bannerLocalService the banner local service
	 */
	public void setBannerLocalService(
		com.ejada.telemony.db.service.BannerLocalService bannerLocalService) {

		this.bannerLocalService = bannerLocalService;
	}

	/**
	 * Returns the banner remote service.
	 *
	 * @return the banner remote service
	 */
	public com.ejada.telemony.db.service.BannerService getBannerService() {
		return bannerService;
	}

	/**
	 * Sets the banner remote service.
	 *
	 * @param bannerService the banner remote service
	 */
	public void setBannerService(
		com.ejada.telemony.db.service.BannerService bannerService) {

		this.bannerService = bannerService;
	}

	/**
	 * Returns the banner persistence.
	 *
	 * @return the banner persistence
	 */
	public BannerPersistence getBannerPersistence() {
		return bannerPersistence;
	}

	/**
	 * Sets the banner persistence.
	 *
	 * @param bannerPersistence the banner persistence
	 */
	public void setBannerPersistence(BannerPersistence bannerPersistence) {
		this.bannerPersistence = bannerPersistence;
	}

	/**
	 * Returns the banner content local service.
	 *
	 * @return the banner content local service
	 */
	public com.ejada.telemony.db.service.BannerContentLocalService
		getBannerContentLocalService() {

		return bannerContentLocalService;
	}

	/**
	 * Sets the banner content local service.
	 *
	 * @param bannerContentLocalService the banner content local service
	 */
	public void setBannerContentLocalService(
		com.ejada.telemony.db.service.BannerContentLocalService
			bannerContentLocalService) {

		this.bannerContentLocalService = bannerContentLocalService;
	}

	/**
	 * Returns the banner content remote service.
	 *
	 * @return the banner content remote service
	 */
	public com.ejada.telemony.db.service.BannerContentService
		getBannerContentService() {

		return bannerContentService;
	}

	/**
	 * Sets the banner content remote service.
	 *
	 * @param bannerContentService the banner content remote service
	 */
	public void setBannerContentService(
		com.ejada.telemony.db.service.BannerContentService
			bannerContentService) {

		this.bannerContentService = bannerContentService;
	}

	/**
	 * Returns the banner content persistence.
	 *
	 * @return the banner content persistence
	 */
	public BannerContentPersistence getBannerContentPersistence() {
		return bannerContentPersistence;
	}

	/**
	 * Sets the banner content persistence.
	 *
	 * @param bannerContentPersistence the banner content persistence
	 */
	public void setBannerContentPersistence(
		BannerContentPersistence bannerContentPersistence) {

		this.bannerContentPersistence = bannerContentPersistence;
	}

	/**
	 * Returns the banner content localization persistence.
	 *
	 * @return the banner content localization persistence
	 */
	public BannerContentLocalizationPersistence
		getBannerContentLocalizationPersistence() {

		return bannerContentLocalizationPersistence;
	}

	/**
	 * Sets the banner content localization persistence.
	 *
	 * @param bannerContentLocalizationPersistence the banner content localization persistence
	 */
	public void setBannerContentLocalizationPersistence(
		BannerContentLocalizationPersistence
			bannerContentLocalizationPersistence) {

		this.bannerContentLocalizationPersistence =
			bannerContentLocalizationPersistence;
	}

	/**
	 * Returns the biller local service.
	 *
	 * @return the biller local service
	 */
	public com.ejada.telemony.db.service.BillerLocalService
		getBillerLocalService() {

		return billerLocalService;
	}

	/**
	 * Sets the biller local service.
	 *
	 * @param billerLocalService the biller local service
	 */
	public void setBillerLocalService(
		com.ejada.telemony.db.service.BillerLocalService billerLocalService) {

		this.billerLocalService = billerLocalService;
	}

	/**
	 * Returns the blocks local service.
	 *
	 * @return the blocks local service
	 */
	public com.ejada.telemony.db.service.BlocksLocalService
		getBlocksLocalService() {

		return blocksLocalService;
	}

	/**
	 * Sets the blocks local service.
	 *
	 * @param blocksLocalService the blocks local service
	 */
	public void setBlocksLocalService(
		com.ejada.telemony.db.service.BlocksLocalService blocksLocalService) {

		this.blocksLocalService = blocksLocalService;
	}

	/**
	 * Returns the blocks persistence.
	 *
	 * @return the blocks persistence
	 */
	public BlocksPersistence getBlocksPersistence() {
		return blocksPersistence;
	}

	/**
	 * Sets the blocks persistence.
	 *
	 * @param blocksPersistence the blocks persistence
	 */
	public void setBlocksPersistence(BlocksPersistence blocksPersistence) {
		this.blocksPersistence = blocksPersistence;
	}

	/**
	 * Returns the channels local service.
	 *
	 * @return the channels local service
	 */
	public com.ejada.telemony.db.service.ChannelsLocalService
		getChannelsLocalService() {

		return channelsLocalService;
	}

	/**
	 * Sets the channels local service.
	 *
	 * @param channelsLocalService the channels local service
	 */
	public void setChannelsLocalService(
		com.ejada.telemony.db.service.ChannelsLocalService
			channelsLocalService) {

		this.channelsLocalService = channelsLocalService;
	}

	/**
	 * Returns the channels persistence.
	 *
	 * @return the channels persistence
	 */
	public ChannelsPersistence getChannelsPersistence() {
		return channelsPersistence;
	}

	/**
	 * Sets the channels persistence.
	 *
	 * @param channelsPersistence the channels persistence
	 */
	public void setChannelsPersistence(
		ChannelsPersistence channelsPersistence) {

		this.channelsPersistence = channelsPersistence;
	}

	/**
	 * Returns the configuration local service.
	 *
	 * @return the configuration local service
	 */
	public com.ejada.telemony.db.service.ConfigurationLocalService
		getConfigurationLocalService() {

		return configurationLocalService;
	}

	/**
	 * Sets the configuration local service.
	 *
	 * @param configurationLocalService the configuration local service
	 */
	public void setConfigurationLocalService(
		com.ejada.telemony.db.service.ConfigurationLocalService
			configurationLocalService) {

		this.configurationLocalService = configurationLocalService;
	}

	/**
	 * Returns the configuration entity local service.
	 *
	 * @return the configuration entity local service
	 */
	public com.ejada.telemony.db.service.ConfigurationEntityLocalService
		getConfigurationEntityLocalService() {

		return configurationEntityLocalService;
	}

	/**
	 * Sets the configuration entity local service.
	 *
	 * @param configurationEntityLocalService the configuration entity local service
	 */
	public void setConfigurationEntityLocalService(
		com.ejada.telemony.db.service.ConfigurationEntityLocalService
			configurationEntityLocalService) {

		this.configurationEntityLocalService = configurationEntityLocalService;
	}

	/**
	 * Returns the configuration entity remote service.
	 *
	 * @return the configuration entity remote service
	 */
	public com.ejada.telemony.db.service.ConfigurationEntityService
		getConfigurationEntityService() {

		return configurationEntityService;
	}

	/**
	 * Sets the configuration entity remote service.
	 *
	 * @param configurationEntityService the configuration entity remote service
	 */
	public void setConfigurationEntityService(
		com.ejada.telemony.db.service.ConfigurationEntityService
			configurationEntityService) {

		this.configurationEntityService = configurationEntityService;
	}

	/**
	 * Returns the configuration entity persistence.
	 *
	 * @return the configuration entity persistence
	 */
	public ConfigurationEntityPersistence getConfigurationEntityPersistence() {
		return configurationEntityPersistence;
	}

	/**
	 * Sets the configuration entity persistence.
	 *
	 * @param configurationEntityPersistence the configuration entity persistence
	 */
	public void setConfigurationEntityPersistence(
		ConfigurationEntityPersistence configurationEntityPersistence) {

		this.configurationEntityPersistence = configurationEntityPersistence;
	}

	/**
	 * Returns the custom web content local service.
	 *
	 * @return the custom web content local service
	 */
	public com.ejada.telemony.db.service.CustomWebContentLocalService
		getCustomWebContentLocalService() {

		return customWebContentLocalService;
	}

	/**
	 * Sets the custom web content local service.
	 *
	 * @param customWebContentLocalService the custom web content local service
	 */
	public void setCustomWebContentLocalService(
		com.ejada.telemony.db.service.CustomWebContentLocalService
			customWebContentLocalService) {

		this.customWebContentLocalService = customWebContentLocalService;
	}

	/**
	 * Returns the custom web content remote service.
	 *
	 * @return the custom web content remote service
	 */
	public com.ejada.telemony.db.service.CustomWebContentService
		getCustomWebContentService() {

		return customWebContentService;
	}

	/**
	 * Sets the custom web content remote service.
	 *
	 * @param customWebContentService the custom web content remote service
	 */
	public void setCustomWebContentService(
		com.ejada.telemony.db.service.CustomWebContentService
			customWebContentService) {

		this.customWebContentService = customWebContentService;
	}

	/**
	 * Returns the error code local service.
	 *
	 * @return the error code local service
	 */
	public com.ejada.telemony.db.service.ErrorCodeLocalService
		getErrorCodeLocalService() {

		return errorCodeLocalService;
	}

	/**
	 * Sets the error code local service.
	 *
	 * @param errorCodeLocalService the error code local service
	 */
	public void setErrorCodeLocalService(
		com.ejada.telemony.db.service.ErrorCodeLocalService
			errorCodeLocalService) {

		this.errorCodeLocalService = errorCodeLocalService;
	}

	/**
	 * Returns the esb local service.
	 *
	 * @return the esb local service
	 */
	public com.ejada.telemony.db.service.ESBLocalService getESBLocalService() {
		return esbLocalService;
	}

	/**
	 * Sets the esb local service.
	 *
	 * @param esbLocalService the esb local service
	 */
	public void setESBLocalService(
		com.ejada.telemony.db.service.ESBLocalService esbLocalService) {

		this.esbLocalService = esbLocalService;
	}

	/**
	 * Returns the feature local service.
	 *
	 * @return the feature local service
	 */
	public com.ejada.telemony.db.service.FeatureLocalService
		getFeatureLocalService() {

		return featureLocalService;
	}

	/**
	 * Sets the feature local service.
	 *
	 * @param featureLocalService the feature local service
	 */
	public void setFeatureLocalService(
		com.ejada.telemony.db.service.FeatureLocalService featureLocalService) {

		this.featureLocalService = featureLocalService;
	}

	/**
	 * Returns the feature remote service.
	 *
	 * @return the feature remote service
	 */
	public com.ejada.telemony.db.service.FeatureService getFeatureService() {
		return featureService;
	}

	/**
	 * Sets the feature remote service.
	 *
	 * @param featureService the feature remote service
	 */
	public void setFeatureService(
		com.ejada.telemony.db.service.FeatureService featureService) {

		this.featureService = featureService;
	}

	/**
	 * Returns the feature persistence.
	 *
	 * @return the feature persistence
	 */
	public FeaturePersistence getFeaturePersistence() {
		return featurePersistence;
	}

	/**
	 * Sets the feature persistence.
	 *
	 * @param featurePersistence the feature persistence
	 */
	public void setFeaturePersistence(FeaturePersistence featurePersistence) {
		this.featurePersistence = featurePersistence;
	}

	/**
	 * Returns the feature lov map local service.
	 *
	 * @return the feature lov map local service
	 */
	public com.ejada.telemony.db.service.FeatureLovMapLocalService
		getFeatureLovMapLocalService() {

		return featureLovMapLocalService;
	}

	/**
	 * Sets the feature lov map local service.
	 *
	 * @param featureLovMapLocalService the feature lov map local service
	 */
	public void setFeatureLovMapLocalService(
		com.ejada.telemony.db.service.FeatureLovMapLocalService
			featureLovMapLocalService) {

		this.featureLovMapLocalService = featureLovMapLocalService;
	}

	/**
	 * Returns the feature lov map remote service.
	 *
	 * @return the feature lov map remote service
	 */
	public com.ejada.telemony.db.service.FeatureLovMapService
		getFeatureLovMapService() {

		return featureLovMapService;
	}

	/**
	 * Sets the feature lov map remote service.
	 *
	 * @param featureLovMapService the feature lov map remote service
	 */
	public void setFeatureLovMapService(
		com.ejada.telemony.db.service.FeatureLovMapService
			featureLovMapService) {

		this.featureLovMapService = featureLovMapService;
	}

	/**
	 * Returns the feature lov map persistence.
	 *
	 * @return the feature lov map persistence
	 */
	public FeatureLovMapPersistence getFeatureLovMapPersistence() {
		return featureLovMapPersistence;
	}

	/**
	 * Sets the feature lov map persistence.
	 *
	 * @param featureLovMapPersistence the feature lov map persistence
	 */
	public void setFeatureLovMapPersistence(
		FeatureLovMapPersistence featureLovMapPersistence) {

		this.featureLovMapPersistence = featureLovMapPersistence;
	}

	/**
	 * Returns the global version local service.
	 *
	 * @return the global version local service
	 */
	public com.ejada.telemony.db.service.GlobalVersionLocalService
		getGlobalVersionLocalService() {

		return globalVersionLocalService;
	}

	/**
	 * Sets the global version local service.
	 *
	 * @param globalVersionLocalService the global version local service
	 */
	public void setGlobalVersionLocalService(
		com.ejada.telemony.db.service.GlobalVersionLocalService
			globalVersionLocalService) {

		this.globalVersionLocalService = globalVersionLocalService;
	}

	/**
	 * Returns the global version persistence.
	 *
	 * @return the global version persistence
	 */
	public GlobalVersionPersistence getGlobalVersionPersistence() {
		return globalVersionPersistence;
	}

	/**
	 * Sets the global version persistence.
	 *
	 * @param globalVersionPersistence the global version persistence
	 */
	public void setGlobalVersionPersistence(
		GlobalVersionPersistence globalVersionPersistence) {

		this.globalVersionPersistence = globalVersionPersistence;
	}

	/**
	 * Returns the import request local service.
	 *
	 * @return the import request local service
	 */
	public com.ejada.telemony.db.service.ImportRequestLocalService
		getImportRequestLocalService() {

		return importRequestLocalService;
	}

	/**
	 * Sets the import request local service.
	 *
	 * @param importRequestLocalService the import request local service
	 */
	public void setImportRequestLocalService(
		com.ejada.telemony.db.service.ImportRequestLocalService
			importRequestLocalService) {

		this.importRequestLocalService = importRequestLocalService;
	}

	/**
	 * Returns the import request remote service.
	 *
	 * @return the import request remote service
	 */
	public com.ejada.telemony.db.service.ImportRequestService
		getImportRequestService() {

		return importRequestService;
	}

	/**
	 * Sets the import request remote service.
	 *
	 * @param importRequestService the import request remote service
	 */
	public void setImportRequestService(
		com.ejada.telemony.db.service.ImportRequestService
			importRequestService) {

		this.importRequestService = importRequestService;
	}

	/**
	 * Returns the import request persistence.
	 *
	 * @return the import request persistence
	 */
	public ImportRequestPersistence getImportRequestPersistence() {
		return importRequestPersistence;
	}

	/**
	 * Sets the import request persistence.
	 *
	 * @param importRequestPersistence the import request persistence
	 */
	public void setImportRequestPersistence(
		ImportRequestPersistence importRequestPersistence) {

		this.importRequestPersistence = importRequestPersistence;
	}

	/**
	 * Returns the ivr local service.
	 *
	 * @return the ivr local service
	 */
	public com.ejada.telemony.db.service.IVRLocalService getIVRLocalService() {
		return ivrLocalService;
	}

	/**
	 * Sets the ivr local service.
	 *
	 * @param ivrLocalService the ivr local service
	 */
	public void setIVRLocalService(
		com.ejada.telemony.db.service.IVRLocalService ivrLocalService) {

		this.ivrLocalService = ivrLocalService;
	}

	/**
	 * Returns the languages local service.
	 *
	 * @return the languages local service
	 */
	public com.ejada.telemony.db.service.LanguagesLocalService
		getLanguagesLocalService() {

		return languagesLocalService;
	}

	/**
	 * Sets the languages local service.
	 *
	 * @param languagesLocalService the languages local service
	 */
	public void setLanguagesLocalService(
		com.ejada.telemony.db.service.LanguagesLocalService
			languagesLocalService) {

		this.languagesLocalService = languagesLocalService;
	}

	/**
	 * Returns the languages remote service.
	 *
	 * @return the languages remote service
	 */
	public com.ejada.telemony.db.service.LanguagesService
		getLanguagesService() {

		return languagesService;
	}

	/**
	 * Sets the languages remote service.
	 *
	 * @param languagesService the languages remote service
	 */
	public void setLanguagesService(
		com.ejada.telemony.db.service.LanguagesService languagesService) {

		this.languagesService = languagesService;
	}

	/**
	 * Returns the languages persistence.
	 *
	 * @return the languages persistence
	 */
	public LanguagesPersistence getLanguagesPersistence() {
		return languagesPersistence;
	}

	/**
	 * Sets the languages persistence.
	 *
	 * @param languagesPersistence the languages persistence
	 */
	public void setLanguagesPersistence(
		LanguagesPersistence languagesPersistence) {

		this.languagesPersistence = languagesPersistence;
	}

	/**
	 * Returns the localization local service.
	 *
	 * @return the localization local service
	 */
	public com.ejada.telemony.db.service.LocalizationLocalService
		getLocalizationLocalService() {

		return localizationLocalService;
	}

	/**
	 * Sets the localization local service.
	 *
	 * @param localizationLocalService the localization local service
	 */
	public void setLocalizationLocalService(
		com.ejada.telemony.db.service.LocalizationLocalService
			localizationLocalService) {

		this.localizationLocalService = localizationLocalService;
	}

	/**
	 * Returns the localization remote service.
	 *
	 * @return the localization remote service
	 */
	public com.ejada.telemony.db.service.LocalizationService
		getLocalizationService() {

		return localizationService;
	}

	/**
	 * Sets the localization remote service.
	 *
	 * @param localizationService the localization remote service
	 */
	public void setLocalizationService(
		com.ejada.telemony.db.service.LocalizationService localizationService) {

		this.localizationService = localizationService;
	}

	/**
	 * Returns the localization persistence.
	 *
	 * @return the localization persistence
	 */
	public LocalizationPersistence getLocalizationPersistence() {
		return localizationPersistence;
	}

	/**
	 * Sets the localization persistence.
	 *
	 * @param localizationPersistence the localization persistence
	 */
	public void setLocalizationPersistence(
		LocalizationPersistence localizationPersistence) {

		this.localizationPersistence = localizationPersistence;
	}

	/**
	 * Returns the lov data local service.
	 *
	 * @return the lov data local service
	 */
	public com.ejada.telemony.db.service.LovDataLocalService
		getLovDataLocalService() {

		return lovDataLocalService;
	}

	/**
	 * Sets the lov data local service.
	 *
	 * @param lovDataLocalService the lov data local service
	 */
	public void setLovDataLocalService(
		com.ejada.telemony.db.service.LovDataLocalService lovDataLocalService) {

		this.lovDataLocalService = lovDataLocalService;
	}

	/**
	 * Returns the lov data persistence.
	 *
	 * @return the lov data persistence
	 */
	public LovDataPersistence getLovDataPersistence() {
		return lovDataPersistence;
	}

	/**
	 * Sets the lov data persistence.
	 *
	 * @param lovDataPersistence the lov data persistence
	 */
	public void setLovDataPersistence(LovDataPersistence lovDataPersistence) {
		this.lovDataPersistence = lovDataPersistence;
	}

	/**
	 * Returns the lov data localization persistence.
	 *
	 * @return the lov data localization persistence
	 */
	public LovDataLocalizationPersistence getLovDataLocalizationPersistence() {
		return lovDataLocalizationPersistence;
	}

	/**
	 * Sets the lov data localization persistence.
	 *
	 * @param lovDataLocalizationPersistence the lov data localization persistence
	 */
	public void setLovDataLocalizationPersistence(
		LovDataLocalizationPersistence lovDataLocalizationPersistence) {

		this.lovDataLocalizationPersistence = lovDataLocalizationPersistence;
	}

	/**
	 * Returns the lovs local service.
	 *
	 * @return the lovs local service
	 */
	public com.ejada.telemony.db.service.LovsLocalService
		getLovsLocalService() {

		return lovsLocalService;
	}

	/**
	 * Sets the lovs local service.
	 *
	 * @param lovsLocalService the lovs local service
	 */
	public void setLovsLocalService(
		com.ejada.telemony.db.service.LovsLocalService lovsLocalService) {

		this.lovsLocalService = lovsLocalService;
	}

	/**
	 * Returns the lovs persistence.
	 *
	 * @return the lovs persistence
	 */
	public LovsPersistence getLovsPersistence() {
		return lovsPersistence;
	}

	/**
	 * Sets the lovs persistence.
	 *
	 * @param lovsPersistence the lovs persistence
	 */
	public void setLovsPersistence(LovsPersistence lovsPersistence) {
		this.lovsPersistence = lovsPersistence;
	}

	/**
	 * Returns the lovs localization persistence.
	 *
	 * @return the lovs localization persistence
	 */
	public LovsLocalizationPersistence getLovsLocalizationPersistence() {
		return lovsLocalizationPersistence;
	}

	/**
	 * Sets the lovs localization persistence.
	 *
	 * @param lovsLocalizationPersistence the lovs localization persistence
	 */
	public void setLovsLocalizationPersistence(
		LovsLocalizationPersistence lovsLocalizationPersistence) {

		this.lovsLocalizationPersistence = lovsLocalizationPersistence;
	}

	/**
	 * Returns the moi local service.
	 *
	 * @return the moi local service
	 */
	public com.ejada.telemony.db.service.MOILocalService getMOILocalService() {
		return moiLocalService;
	}

	/**
	 * Sets the moi local service.
	 *
	 * @param moiLocalService the moi local service
	 */
	public void setMOILocalService(
		com.ejada.telemony.db.service.MOILocalService moiLocalService) {

		this.moiLocalService = moiLocalService;
	}

	/**
	 * Returns the non customer local service.
	 *
	 * @return the non customer local service
	 */
	public com.ejada.telemony.db.service.NonCustomerLocalService
		getNonCustomerLocalService() {

		return nonCustomerLocalService;
	}

	/**
	 * Sets the non customer local service.
	 *
	 * @param nonCustomerLocalService the non customer local service
	 */
	public void setNonCustomerLocalService(
		com.ejada.telemony.db.service.NonCustomerLocalService
			nonCustomerLocalService) {

		this.nonCustomerLocalService = nonCustomerLocalService;
	}

	/**
	 * Returns the otp local service.
	 *
	 * @return the otp local service
	 */
	public com.ejada.telemony.db.service.OTPLocalService getOTPLocalService() {
		return otpLocalService;
	}

	/**
	 * Sets the otp local service.
	 *
	 * @param otpLocalService the otp local service
	 */
	public void setOTPLocalService(
		com.ejada.telemony.db.service.OTPLocalService otpLocalService) {

		this.otpLocalService = otpLocalService;
	}

	/**
	 * Returns the persona local service.
	 *
	 * @return the persona local service
	 */
	public com.ejada.telemony.db.service.PersonaLocalService
		getPersonaLocalService() {

		return personaLocalService;
	}

	/**
	 * Sets the persona local service.
	 *
	 * @param personaLocalService the persona local service
	 */
	public void setPersonaLocalService(
		com.ejada.telemony.db.service.PersonaLocalService personaLocalService) {

		this.personaLocalService = personaLocalService;
	}

	/**
	 * Returns the persona remote service.
	 *
	 * @return the persona remote service
	 */
	public com.ejada.telemony.db.service.PersonaService getPersonaService() {
		return personaService;
	}

	/**
	 * Sets the persona remote service.
	 *
	 * @param personaService the persona remote service
	 */
	public void setPersonaService(
		com.ejada.telemony.db.service.PersonaService personaService) {

		this.personaService = personaService;
	}

	/**
	 * Returns the persona persistence.
	 *
	 * @return the persona persistence
	 */
	public PersonaPersistence getPersonaPersistence() {
		return personaPersistence;
	}

	/**
	 * Sets the persona persistence.
	 *
	 * @param personaPersistence the persona persistence
	 */
	public void setPersonaPersistence(PersonaPersistence personaPersistence) {
		this.personaPersistence = personaPersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.ejada.telemony.db.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.ejada.telemony.db.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(
		ResourcePersistence resourcePersistence) {

		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the resource localization persistence.
	 *
	 * @return the resource localization persistence
	 */
	public ResourceLocalizationPersistence
		getResourceLocalizationPersistence() {

		return resourceLocalizationPersistence;
	}

	/**
	 * Sets the resource localization persistence.
	 *
	 * @param resourceLocalizationPersistence the resource localization persistence
	 */
	public void setResourceLocalizationPersistence(
		ResourceLocalizationPersistence resourceLocalizationPersistence) {

		this.resourceLocalizationPersistence = resourceLocalizationPersistence;
	}

	/**
	 * Returns the segment local service.
	 *
	 * @return the segment local service
	 */
	public com.ejada.telemony.db.service.SegmentLocalService
		getSegmentLocalService() {

		return segmentLocalService;
	}

	/**
	 * Sets the segment local service.
	 *
	 * @param segmentLocalService the segment local service
	 */
	public void setSegmentLocalService(
		com.ejada.telemony.db.service.SegmentLocalService segmentLocalService) {

		this.segmentLocalService = segmentLocalService;
	}

	/**
	 * Returns the segment remote service.
	 *
	 * @return the segment remote service
	 */
	public com.ejada.telemony.db.service.SegmentService getSegmentService() {
		return segmentService;
	}

	/**
	 * Sets the segment remote service.
	 *
	 * @param segmentService the segment remote service
	 */
	public void setSegmentService(
		com.ejada.telemony.db.service.SegmentService segmentService) {

		this.segmentService = segmentService;
	}

	/**
	 * Returns the segment persistence.
	 *
	 * @return the segment persistence
	 */
	public SegmentPersistence getSegmentPersistence() {
		return segmentPersistence;
	}

	/**
	 * Sets the segment persistence.
	 *
	 * @param segmentPersistence the segment persistence
	 */
	public void setSegmentPersistence(SegmentPersistence segmentPersistence) {
		this.segmentPersistence = segmentPersistence;
	}

	/**
	 * Returns the sms local service.
	 *
	 * @return the sms local service
	 */
	public com.ejada.telemony.db.service.SMSLocalService getSMSLocalService() {
		return smsLocalService;
	}

	/**
	 * Sets the sms local service.
	 *
	 * @param smsLocalService the sms local service
	 */
	public void setSMSLocalService(
		com.ejada.telemony.db.service.SMSLocalService smsLocalService) {

		this.smsLocalService = smsLocalService;
	}

	/**
	 * Returns the themes local service.
	 *
	 * @return the themes local service
	 */
	public com.ejada.telemony.db.service.ThemesLocalService
		getThemesLocalService() {

		return themesLocalService;
	}

	/**
	 * Sets the themes local service.
	 *
	 * @param themesLocalService the themes local service
	 */
	public void setThemesLocalService(
		com.ejada.telemony.db.service.ThemesLocalService themesLocalService) {

		this.themesLocalService = themesLocalService;
	}

	/**
	 * Returns the themes remote service.
	 *
	 * @return the themes remote service
	 */
	public com.ejada.telemony.db.service.ThemesService getThemesService() {
		return themesService;
	}

	/**
	 * Sets the themes remote service.
	 *
	 * @param themesService the themes remote service
	 */
	public void setThemesService(
		com.ejada.telemony.db.service.ThemesService themesService) {

		this.themesService = themesService;
	}

	/**
	 * Returns the themes persistence.
	 *
	 * @return the themes persistence
	 */
	public ThemesPersistence getThemesPersistence() {
		return themesPersistence;
	}

	/**
	 * Sets the themes persistence.
	 *
	 * @param themesPersistence the themes persistence
	 */
	public void setThemesPersistence(ThemesPersistence themesPersistence) {
		this.themesPersistence = themesPersistence;
	}

	/**
	 * Returns the user logs local service.
	 *
	 * @return the user logs local service
	 */
	public com.ejada.telemony.db.service.UserLogsLocalService
		getUserLogsLocalService() {

		return userLogsLocalService;
	}

	/**
	 * Sets the user logs local service.
	 *
	 * @param userLogsLocalService the user logs local service
	 */
	public void setUserLogsLocalService(
		com.ejada.telemony.db.service.UserLogsLocalService
			userLogsLocalService) {

		this.userLogsLocalService = userLogsLocalService;
	}

	/**
	 * Returns the user logs remote service.
	 *
	 * @return the user logs remote service
	 */
	public com.ejada.telemony.db.service.UserLogsService getUserLogsService() {
		return userLogsService;
	}

	/**
	 * Sets the user logs remote service.
	 *
	 * @param userLogsService the user logs remote service
	 */
	public void setUserLogsService(
		com.ejada.telemony.db.service.UserLogsService userLogsService) {

		this.userLogsService = userLogsService;
	}

	/**
	 * Returns the user logs persistence.
	 *
	 * @return the user logs persistence
	 */
	public UserLogsPersistence getUserLogsPersistence() {
		return userLogsPersistence;
	}

	/**
	 * Sets the user logs persistence.
	 *
	 * @param userLogsPersistence the user logs persistence
	 */
	public void setUserLogsPersistence(
		UserLogsPersistence userLogsPersistence) {

		this.userLogsPersistence = userLogsPersistence;
	}

	/**
	 * Returns the white list local service.
	 *
	 * @return the white list local service
	 */
	public com.ejada.telemony.db.service.WhiteListLocalService
		getWhiteListLocalService() {

		return whiteListLocalService;
	}

	/**
	 * Sets the white list local service.
	 *
	 * @param whiteListLocalService the white list local service
	 */
	public void setWhiteListLocalService(
		com.ejada.telemony.db.service.WhiteListLocalService
			whiteListLocalService) {

		this.whiteListLocalService = whiteListLocalService;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the workflow instance link local service.
	 *
	 * @return the workflow instance link local service
	 */
	public com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		getWorkflowInstanceLinkLocalService() {

		return workflowInstanceLinkLocalService;
	}

	/**
	 * Sets the workflow instance link local service.
	 *
	 * @param workflowInstanceLinkLocalService the workflow instance link local service
	 */
	public void setWorkflowInstanceLinkLocalService(
		com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
			workflowInstanceLinkLocalService) {

		this.workflowInstanceLinkLocalService =
			workflowInstanceLinkLocalService;
	}

	/**
	 * Returns the workflow instance link persistence.
	 *
	 * @return the workflow instance link persistence
	 */
	public WorkflowInstanceLinkPersistence
		getWorkflowInstanceLinkPersistence() {

		return workflowInstanceLinkPersistence;
	}

	/**
	 * Sets the workflow instance link persistence.
	 *
	 * @param workflowInstanceLinkPersistence the workflow instance link persistence
	 */
	public void setWorkflowInstanceLinkPersistence(
		WorkflowInstanceLinkPersistence workflowInstanceLinkPersistence) {

		this.workflowInstanceLinkPersistence = workflowInstanceLinkPersistence;
	}

	public void afterPropertiesSet() {
		ResourceServiceUtil.setService(resourceService);
	}

	public void destroy() {
		ResourceServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ResourceService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Resource.class;
	}

	protected String getModelClassName() {
		return Resource.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = resourcePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.ejada.telemony.db.service.AppConfigItemLocalService.class
	)
	protected com.ejada.telemony.db.service.AppConfigItemLocalService
		appConfigItemLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.AppConfigItemService.class
	)
	protected com.ejada.telemony.db.service.AppConfigItemService
		appConfigItemService;

	@BeanReference(type = AppConfigItemPersistence.class)
	protected AppConfigItemPersistence appConfigItemPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.AppEnvironmentLocalService.class
	)
	protected com.ejada.telemony.db.service.AppEnvironmentLocalService
		appEnvironmentLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.AppEnvironmentService.class
	)
	protected com.ejada.telemony.db.service.AppEnvironmentService
		appEnvironmentService;

	@BeanReference(type = AppEnvironmentPersistence.class)
	protected AppEnvironmentPersistence appEnvironmentPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.AppVersionLocalService.class
	)
	protected com.ejada.telemony.db.service.AppVersionLocalService
		appVersionLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.AppVersionService.class)
	protected com.ejada.telemony.db.service.AppVersionService appVersionService;

	@BeanReference(type = AppVersionPersistence.class)
	protected AppVersionPersistence appVersionPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.BannerLocalService.class
	)
	protected com.ejada.telemony.db.service.BannerLocalService
		bannerLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.BannerService.class)
	protected com.ejada.telemony.db.service.BannerService bannerService;

	@BeanReference(type = BannerPersistence.class)
	protected BannerPersistence bannerPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.BannerContentLocalService.class
	)
	protected com.ejada.telemony.db.service.BannerContentLocalService
		bannerContentLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.BannerContentService.class
	)
	protected com.ejada.telemony.db.service.BannerContentService
		bannerContentService;

	@BeanReference(type = BannerContentPersistence.class)
	protected BannerContentPersistence bannerContentPersistence;

	@BeanReference(type = BannerContentLocalizationPersistence.class)
	protected BannerContentLocalizationPersistence
		bannerContentLocalizationPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.BillerLocalService.class
	)
	protected com.ejada.telemony.db.service.BillerLocalService
		billerLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.BlocksLocalService.class
	)
	protected com.ejada.telemony.db.service.BlocksLocalService
		blocksLocalService;

	@BeanReference(type = BlocksPersistence.class)
	protected BlocksPersistence blocksPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.ChannelsLocalService.class
	)
	protected com.ejada.telemony.db.service.ChannelsLocalService
		channelsLocalService;

	@BeanReference(type = ChannelsPersistence.class)
	protected ChannelsPersistence channelsPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.ConfigurationLocalService.class
	)
	protected com.ejada.telemony.db.service.ConfigurationLocalService
		configurationLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.ConfigurationEntityLocalService.class
	)
	protected com.ejada.telemony.db.service.ConfigurationEntityLocalService
		configurationEntityLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.ConfigurationEntityService.class
	)
	protected com.ejada.telemony.db.service.ConfigurationEntityService
		configurationEntityService;

	@BeanReference(type = ConfigurationEntityPersistence.class)
	protected ConfigurationEntityPersistence configurationEntityPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.CustomWebContentLocalService.class
	)
	protected com.ejada.telemony.db.service.CustomWebContentLocalService
		customWebContentLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.CustomWebContentService.class
	)
	protected com.ejada.telemony.db.service.CustomWebContentService
		customWebContentService;

	@BeanReference(
		type = com.ejada.telemony.db.service.ErrorCodeLocalService.class
	)
	protected com.ejada.telemony.db.service.ErrorCodeLocalService
		errorCodeLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.ESBLocalService.class)
	protected com.ejada.telemony.db.service.ESBLocalService esbLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.FeatureLocalService.class
	)
	protected com.ejada.telemony.db.service.FeatureLocalService
		featureLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.FeatureService.class)
	protected com.ejada.telemony.db.service.FeatureService featureService;

	@BeanReference(type = FeaturePersistence.class)
	protected FeaturePersistence featurePersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.FeatureLovMapLocalService.class
	)
	protected com.ejada.telemony.db.service.FeatureLovMapLocalService
		featureLovMapLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.FeatureLovMapService.class
	)
	protected com.ejada.telemony.db.service.FeatureLovMapService
		featureLovMapService;

	@BeanReference(type = FeatureLovMapPersistence.class)
	protected FeatureLovMapPersistence featureLovMapPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.GlobalVersionLocalService.class
	)
	protected com.ejada.telemony.db.service.GlobalVersionLocalService
		globalVersionLocalService;

	@BeanReference(type = GlobalVersionPersistence.class)
	protected GlobalVersionPersistence globalVersionPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.ImportRequestLocalService.class
	)
	protected com.ejada.telemony.db.service.ImportRequestLocalService
		importRequestLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.ImportRequestService.class
	)
	protected com.ejada.telemony.db.service.ImportRequestService
		importRequestService;

	@BeanReference(type = ImportRequestPersistence.class)
	protected ImportRequestPersistence importRequestPersistence;

	@BeanReference(type = com.ejada.telemony.db.service.IVRLocalService.class)
	protected com.ejada.telemony.db.service.IVRLocalService ivrLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.LanguagesLocalService.class
	)
	protected com.ejada.telemony.db.service.LanguagesLocalService
		languagesLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.LanguagesService.class)
	protected com.ejada.telemony.db.service.LanguagesService languagesService;

	@BeanReference(type = LanguagesPersistence.class)
	protected LanguagesPersistence languagesPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.LocalizationLocalService.class
	)
	protected com.ejada.telemony.db.service.LocalizationLocalService
		localizationLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.LocalizationService.class
	)
	protected com.ejada.telemony.db.service.LocalizationService
		localizationService;

	@BeanReference(type = LocalizationPersistence.class)
	protected LocalizationPersistence localizationPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.LovDataLocalService.class
	)
	protected com.ejada.telemony.db.service.LovDataLocalService
		lovDataLocalService;

	@BeanReference(type = LovDataPersistence.class)
	protected LovDataPersistence lovDataPersistence;

	@BeanReference(type = LovDataLocalizationPersistence.class)
	protected LovDataLocalizationPersistence lovDataLocalizationPersistence;

	@BeanReference(type = com.ejada.telemony.db.service.LovsLocalService.class)
	protected com.ejada.telemony.db.service.LovsLocalService lovsLocalService;

	@BeanReference(type = LovsPersistence.class)
	protected LovsPersistence lovsPersistence;

	@BeanReference(type = LovsLocalizationPersistence.class)
	protected LovsLocalizationPersistence lovsLocalizationPersistence;

	@BeanReference(type = com.ejada.telemony.db.service.MOILocalService.class)
	protected com.ejada.telemony.db.service.MOILocalService moiLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.NonCustomerLocalService.class
	)
	protected com.ejada.telemony.db.service.NonCustomerLocalService
		nonCustomerLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.OTPLocalService.class)
	protected com.ejada.telemony.db.service.OTPLocalService otpLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.PersonaLocalService.class
	)
	protected com.ejada.telemony.db.service.PersonaLocalService
		personaLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.PersonaService.class)
	protected com.ejada.telemony.db.service.PersonaService personaService;

	@BeanReference(type = PersonaPersistence.class)
	protected PersonaPersistence personaPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.ResourceLocalService.class
	)
	protected com.ejada.telemony.db.service.ResourceLocalService
		resourceLocalService;

	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;

	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;

	@BeanReference(type = ResourceLocalizationPersistence.class)
	protected ResourceLocalizationPersistence resourceLocalizationPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.SegmentLocalService.class
	)
	protected com.ejada.telemony.db.service.SegmentLocalService
		segmentLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.SegmentService.class)
	protected com.ejada.telemony.db.service.SegmentService segmentService;

	@BeanReference(type = SegmentPersistence.class)
	protected SegmentPersistence segmentPersistence;

	@BeanReference(type = com.ejada.telemony.db.service.SMSLocalService.class)
	protected com.ejada.telemony.db.service.SMSLocalService smsLocalService;

	@BeanReference(
		type = com.ejada.telemony.db.service.ThemesLocalService.class
	)
	protected com.ejada.telemony.db.service.ThemesLocalService
		themesLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.ThemesService.class)
	protected com.ejada.telemony.db.service.ThemesService themesService;

	@BeanReference(type = ThemesPersistence.class)
	protected ThemesPersistence themesPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.UserLogsLocalService.class
	)
	protected com.ejada.telemony.db.service.UserLogsLocalService
		userLogsLocalService;

	@BeanReference(type = com.ejada.telemony.db.service.UserLogsService.class)
	protected com.ejada.telemony.db.service.UserLogsService userLogsService;

	@BeanReference(type = UserLogsPersistence.class)
	protected UserLogsPersistence userLogsPersistence;

	@BeanReference(
		type = com.ejada.telemony.db.service.WhiteListLocalService.class
	)
	protected com.ejada.telemony.db.service.WhiteListLocalService
		whiteListLocalService;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService.class
	)
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

	@ServiceReference(type = WorkflowInstanceLinkPersistence.class)
	protected WorkflowInstanceLinkPersistence workflowInstanceLinkPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		ResourceServiceBaseImpl.class);

}